### ISSUE TITLE
extending structures with types in fields

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#1003]
I get a universe error when extending structures which have a type in a field. Example:

``` lean
-- HoTT
open is_trunc

structure my_Pointed :=
  (carrier : Type)
  (point   : carrier)

structure my_hset :=
  (carrier : Type)
  (struct : is_trunc 0 carrier)

structure phset extends my_hset, my_Pointed
```

Error:

```
type mismatch at application
  my_hset.mk (ptrunctype.carrier s)
term
  ptrunctype.carrier s
has type
  Type.{l_1}
but is expected to have type
  Type.{l_2}
```

(the example works when you replace `Type` by `Type₀` twice)

**Comment by dselsam** [comment]
They don't have to be `0` they just need to be the same:

``` Lean
open is_trunc

universe l
structure my_Pointed :=
  (carrier : Type.{l})
  (point   : carrier)

structure my_hset :=
  (carrier : Type.{l})
  (struct : is_trunc 0 carrier)

structure phset extends my_hset, my_Pointed
```

**Comment by fpvandoorn** [comment]
Yes, it was just an example to indicate that I did nothing else wrong. 
But extending structures also makes sense for structures with fields depending on universe _variables_.

**Comment by dselsam** [comment]
This may not be helpful but you could also do:

``` Lean
-- HoTT                                                                                                                                    
open is_trunc

structure my_Pointed :=
  (carrier : Type)
  (point   : carrier)

structure my_hset :=
  (carrier : Type)
  (struct : is_trunc 0 carrier)

universe variable l
structure phset extends my_hset.{l}, my_Pointed.{l}
```

**Comment by fpvandoorn** [comment]
That is a nice workaround! Thanks.

**Comment by leodemoura** [comment]
The current system elaborates the structure, and then merges the fields that have the same name and same type.
There is no typing constraint that forces the two `carrier : Type` fields to be in the same universe.
Moreover, since the universe metavariables have not been assigned, they are assigned to two different parameters. I think this is the right behavior. 
Daniel's solution is the right way to address this problem.
I'm closing this issue.
