### ISSUE TITLE
Cannot compile under Cygwin

### ISSUE THREAD

**Issue by ysangkok** [leanprover/lean3#1031]
Compiling under Cygwin, I get this error:

```
/home/Janus/lean/src/util/file_lock.cpp: In destructor 'lean::file_lock::~file_lock()':
/home/Janus/lean/src/util/file_lock.cpp:98:19: error: 'close' was not declared in this scope
         close(m_fd);
                   ^
util/CMakeFiles/util.dir/build.make:686: recipe for target 'util/CMakeFiles/util.dir/file_lock.cpp.o' failed
```

I guess syscalls are not available in Cygwin and LEAN_WINDOWS is not defined. (should it be?)

**Comment by Kha** [comment]
I am not using Lean under Windows myself, but LEAN_WINDOWS should be controlled by the CYGWIN or CMAKE_SYSTEM_NAME environment variables: https://github.com/leanprover/lean/blob/master/src/CMakeLists.txt#L66
Do you get the "Windows detected" output from `cmake`? Does your shell export either of these variables?

**Comment by ysangkok** [comment]
@Kha: "Windows detected" is output, but my shell exports neither variable. I do get the following warning though:

```
CMake Warning (dev) at CMakeLists.txt:360 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "CYGWIN" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
```

**Comment by Kha** [comment]
> "Windows detected" is output

Hm, it should work then. My knowledge of CMake is very limited, but perhaps you could debug the problem by looking at the exact cmdline `file_lock.cpp` is compiled with (using `ninja -v` or `make -n` (I think), respectively).

**Comment by soonhokong** [comment]
1. The warning from CMake is not a real problem I think. We can change the CMakeLists.txt file to remove the warning.
2. In `file_lock.cpp` under CYGWIN, the build fails because `unistd.h` header file is not included. Note that this header is only included if `LEAN_WINDOWS` is _not_ defined. I've manually added it and the build passed this point.
3. There is another problem in [src/util/lp/lp_settings.cpp](https://github.com/leanprover/lean/blob/master/src/util/lp/lp_settings.cpp#L81-L83). It seems there is no `rand` function provided in CYGWIN. I think it's a CYGWIN peculiarity. I would rewrite `my_random` and `my_random_init` functions using functions in C++11's [random](http://en.cppreference.com/w/cpp/numeric/random) header. There are already examples in Lean codebase which use this header (for example, [gcd.cpp](https://github.com/leanprover/lean/blob/5051c0031e24ab5cf30c46a0295c37bfbfcb16ef/src/tests/util/numerics/gcd.cpp#L15-L16)). BTW, there is another problem related to [mkdir](https://github.com/leanprover/lean/blob/23079a75a78541434350bd5e84064552f734c30e/src/tests/util/lp/lp.cpp#L1515-L1519).

As a workaround for item 3, I replaced calls to `rand` with `0` just to see this change makes the code build. It did build. However, the generated binary didn't seem to work properly. It had a problem in importing `init` module for example. I guess this indicates a possible problem in `src/util/lean_path.cpp` (but I'm not sure for now).

**Comment by soonhokong** [comment]
@leodemoura, regarding item 2, we use the following two `#if` to wrap Windows-specific code:
- `#if defined(LEAN_WINDOWS) && !defined(LEAN_CYGWIN)`
- `#if defined(LEAN_WINDOWS)` or `#if LEAN_WINDOWS`

I guess we need to use the first one in everywhere. Is it correct? FYI, [here](https://github.com/leanprover/lean/search?l=cpp&q=LEAN_WINDOWS&type=Code&utf8=%E2%9C%93), you can see the occurrences where we use them.

**Comment by soonhokong** [comment]
@ysangkok, in the meantime, please try [msys2](https://github.com/leanprover/lean/blob/master/doc/make/msys2.md). I'm sure that this one is working.

**Comment by leodemoura** [comment]
@gebner @Kha @jroesch Do you see any reason for supporting cygwin? I think `msys2` is easier to install and use.
I don't even have cygwin anymore on my machines.

**Comment by gebner** [comment]
I'm in favor of dropping cygwin.  We don't test it, therefore it is most certainly broken, and we have msys2 as a good alternative.
