### ISSUE TITLE
Type of (n-1) with n:ℕ is ℕ

### ISSUE THREAD

**Issue by Dietr1ch** [leanprover/lean3#1064]
I'm trying out Lean on the browser version, and got this unexpected result.

It may be the intended result depending on how the `-` function is defined, but then again it would be a little weird as the expected output would be something like `ℕ ∪ {Undefined}` and not only `ℕ`.

( If I'm completely lost I'd be pleased to have some guidance on what to study first (= )

**Comment by robertylewis** [comment]
Subtraction on nat is defined here: https://github.com/leanprover/lean/blob/master/library/init/nat.lean#L55

It's "cutoff" subtraction. So `n - 1` is equal to 0 if `n` is 0, and the expected value otherwise. Try this:

``` lean
open nat
eval (0 : nat) - 2
```

Note that many of the theorems concerning `-` for nat have hypotheses about the order of the arguments. https://github.com/leanprover/lean/blob/master/library/data/nat/sub.lean

**Comment by avigad** [comment]
@Dietr1ch, this is the expected behavior: the subtraction function on the natural numbers is really truncated subtraction, which means that `m - n` returns `0` when `n > m`. See, for example, Section 6.4 of the tutorial, or the library files here:

  https://github.com/leanprover/lean/blob/master/library/data/nat/sub.lean

There are various ways to handle partial functions in type theory, such as using the `option` type. But in practice, it is usually more convenient to use truncated subtraction.

Note that there is also a `lean-user` mailing list, which is a good place to ask questions like this. You can easily join here:

  https://groups.google.com/forum/#!forum/lean-user

**Comment by Dietr1ch** [comment]
Oh thanks to both of you. I'll be using the mailing list first then (=
