### ISSUE TITLE
Check and variable (copied from stack overflow)

### ISSUE THREAD

**Issue by tomsib2001** [leanprover/lean3#1067]
I'm not sure if this is a trivial issue covered by the tutorial, but just in case:

The following code has a strange behavior

```
variable (toto : Type)
check eq.symm  --output: eq.symm : ?a toto = ?b toto → ?b toto = ?a toto
```

I would expect check to not take into account the irrelevant implicit variable toto when showing me the type of eq.symm.
Is this really intended?

edit: reference: http://stackoverflow.com/questions/37659392/why-does-lean-add-implicit-variables-to-lemmas-from-eq

**Comment by fpvandoorn** [comment]
This looks like a problem with the flag `pp.metavar_args`. It should default to `false`, but if I add the option `set_option pp.metavar_args false` manually it does give the more intuitive output

``` lean
eq.symm : ?a = ?b → ?b = ?a
```

The reason why Lean gives this output is just because the metavariables `?a` and `?b` can depend on the variable `toto` (so they are treated as functions applied to the argument `toto`). However, this information is not very useful as a user, so we hide it by default.

To get output which might be more useful you can use either of the following:

``` lean
print eq.symm -- theorem eq.symm : ∀ {A : Type} {a b : A}, a = b → b = a :=
              -- λ A a, eq.rec (eq.refl a)

check @eq.symm -- eq.symm : ∀ {A} {a b}, a = b → b = a
```

**Comment by tomsib2001** [comment]
Thank you!

**Comment by leodemoura** [comment]
This issue has been fixed in the `lean3` branch.
