### ISSUE TITLE
Can't use defined variable in definition if implicit variable

### ISSUE THREAD

**Issue by tomsib2001** [leanprover/lean3#1069]
Hi,
Lean complains on the following example with the message: "don't know how to synthesize placeholder". Is this expected behavior?

```
variable {n : nat}

definition m := n
check m
definition p := m
```

EDIT: removed useless "section" opening

**Comment by fpvandoorn** [comment]
Yes, this is the expected behavior. Declared variables become arguments of definitions and theorems where you use them. So the definition `m` has an implicit argument of type `nat`. Then when you use `m` in definition `p`, it cannot infer this implicit argument, so it raises an error. Note that `check m` is misleading, since `m` is interpreted as `@m _`, which indeed has type `nat` (it cannot figure out the argument of `m` in the `check`). Executing either `check @m` or `print m` gives more accurate information.

I don't know what you're trying here. You might want to make `n` an explicit variable. Or it might help to make the `n` a `parameter` instead of a `variable`. That will fix `n` for the section, so you can do things like this:

``` lean
section
parameter {n : nat}

definition m := n
check m
definition p := m
end
```

However, after you close the section, `n` becomes an implicit argument to the definitions, which cannot be inferred for definitions like `m`, so in that case you also want `n` to be explicit.

**Comment by tomsib2001** [comment]
Hi,
Thank you for your quick and detailed answer. I was actually trying to minimize an example from this error I had when I attempted to define the index of a subgroup inside the finsubg.lean file:

```
definition indexGH : nat := card (fin_lcosets H G)

check (coprime (card H) indexGH)

definition Hall := coprime (card H) indexGH
```

just before the Lagrange theorem (around line 173 on my current version). It tells me the same thing:

`don't know how to synthesize placeholder
A : Type,
_inst_1 : decidable_eq A,
_inst_2 : group A,
H : finset A,
is_finsubgH : is_finsubg H,
G : finset A,
is_finsubgG : is_finsubg G
⊢ Type
user-error: Minibuffer window is not active
don't know how to synthesize placeholder
A : Type,
_inst_1 : decidable_eq A,
_inst_2 : group A,
H : finset A,
is_finsubgH : is_finsubg H,
G : finset A,
is_finsubgG : is_finsubg G
⊢ Type
Mark set [2 times]
`

If I understand what you said, I should change the declaration

```
variables {A : Type} [decidable_eq A] [group A]
```

to parameters?

**Comment by robertylewis** [comment]
I don't think you want the variables `G` and `H` to be implicit in your definition `indexGH`. `indexGH` is basically a function of `G` and `H`, but you're asking Lean to figure out what these sets are with no information to infer that from. You can do the following:

``` lean
variables (G) (H) -- this makes G and H explicit instead of implicit
definition indexGH : nat := card (fin_lcosets H G)

check (coprime (card H) (indexGH G H))

definition Hall := coprime (card H) (indexGH G H)

variables {G} {H} -- this makes them implicit for what follows
```

Notice that `A` can stay implicit, since it can be inferred from `G : finset A`.

**Comment by leodemoura** [comment]
I'm closing this issue.
