### ISSUE TITLE
lean executable hangs forever 

### ISSUE THREAD

**Issue by jroesch** [leanprover/lean3#1089]
``` lean
import init.string
import init.bool
import system.IO

inductive token :=
   | eof : token
   | plus : token
   | var : string -> token

open token
open option

definition to_token : string → option token
| to_token [] := none
| to_token (c :: cs) := 
  let t : option token := match c with
    | 'x' := some (var "x")
    | 'y' := some (var "y")
    | '+' := some plus
    | _ := none
  end in t
```

Attempting to run this file through the lean executable `lean broken.lean` causes it to hang, and has not terminated ... yet.

**Comment by leodemoura** [comment]
From slack:

leodemoura [7:23 PM]  
It doesn't have special support for `char`. Then, it unfolds the literals and get terms of the form `succ (such (succ ...))`.
Each `succ` is consumed by a `nat.cases_on`.

jroesch [7:24 PM]  
right

leodemoura [7:24 PM]  
To handle this case nicely, we need special support for matching literals of decidable types.

jroesch [7:24 PM]  
that makes sense, I probably want a match like construct that works for types with dec eq

leodemoura [7:25 PM]  
Then, the compiler would use `if-then-else` instead of `cases_on`.
It is on my todo stack. I will need to redo the equation compiler as I  re-implement the elaborator.
Do you have more equation-compiler related features?

jroesch [7:28 PM]  
The literals was a big one, I was going to write a pass to coalesce them in the backend, but having match understand decidable equality would be a much better way

**Comment by leodemoura** [comment]
the issue has been addressed in the `lean3` branch
