### ISSUE TITLE
segmentation fault with to_expr

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#1098]
This causes a segmentation fault:

``` lean
open expr tactic

example (A : Type) (a : A) : A :=
by do to_expr `(sorry) >>= exact
```

Also this:

``` lean
open expr tactic

example (a : nat) : nat :=
by do to_expr `(nat.zero) >>= exact
```

**Comment by leodemoura** [comment]
The changes done this morning have fixed this issue.

BTW, the first example will fail since we don't know what is the expected type for the `sorry`.
We should use

```
example (A : Type) (a : A) : A :=
by do to_expr `((sorry : A)) >>= exact
```

Or use the `refine` tactic that will elaborate the `sorry` with respect to the current `target`.

```
example (A : Type) (a : A) : A :=
by refine `(sorry)
```

We can also define a different `to_expr` that elaborates the given `qexpr` using the current `target` as the  expected type.

**Comment by leodemoura** [comment]
Here is the `to_expr` that uses the current target to elaborate the given `qexpr`

```
open expr tatic

meta_definition to_expr_target (a : qexpr) : tactic expr :=
do tgt ← target,
   to_expr `((%%a : %%tgt))

example (A : Type) (a : A) : A :=
by do to_expr_target `(sorry) >>= exact
```

**Comment by leodemoura** [comment]
@avigad @dselsam I managed to reproduce the bug after I installed Ubuntu 16.04.
The commit above fixes the problem.
