### ISSUE TITLE
RFC : Strings

### ISSUE THREAD

**Issue by jroesch** [leanprover/lean3#1175]
This is a placeholder issue which I will expand will a full RFC post-PLDI. 

A 100 mile view: getting strings right is *very* hard, we should try not repeat the sins of the past and build a good story around interoperability for both byte strings (array of `u8`s) and unicode strings.

Specifically we should look at how the String ecosystem has developed in other languages, good examples to learn from are Haskell, and Rust. In both communities there has developed a family of String types, we should make doing the right thing easy, and support *all* common use cases. It is hard to build *real* systems without good support for Strings. 

In general I want to have a story for *all* native types, but this RFC will focus on just Strings.

excerpt from a Slack conversation:

I think its technically an extension

[3:54]  
but gets desugared to a method `fromString : String -> R`

[3:54]  
where `R` is the string type

[3:54]  
https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-String.html

[3:54]  
this allows us to keep simple strings while we experiment with different alternatives

[3:55]  
I like Rust’s structuring better

[3:55]  
there is just `String`, `CString`, `[u8]` and `OsString`

[3:55]  
with appropriate conversions for each

[3:55]  
String is like Haskell’s text and *must* be valid utf-8

[3:56]  
`CString` is a null terminated version of `[u8]`

[3:56]  
and `OsString` is for interfacing with native code, that has platform specific encodings

[3:56]  
they internally use a string encoding called `wtf-8`

[3:56]  
https://simonsapin.github.io/wtf-8/

[3:57]  
to deal with Windows & Unix compatibility

**Comment by gebner** [comment]
> In general I want to have a story for all native types, but this RFC will focus on just Strings.

You haven't defined "native", but I strongly hope that `string` does not become an uninterpreted meta-constant.  It would be a shame if you could not reason about anything involving strings.

From this point of view, Haskell-like strings are probably easier to accomodate, as they are just 

``` lean
@[irreducible] def string = list code_point
def code_point = fin 0x10ffff
```

We can and probably should hide the fact that it is implemented as a list, so that people don't try to use `list.length` or other incorrect operations.  This also makes it easier to replace the list by an alternative implementation later on.

> byte strings (array of u8s)

Should we store byte strings as byte arrays in memory?  It would make cons expensive, but at least Haskell's Data.Text gets away with having O(n) cons.

**Comment by leodemoura** [comment]
The commit above tries to "protect" the string implementation.
The idea is to make sure we don't write code that relies on the current implementation (`list char`).
