### ISSUE TITLE
Locals are shadowed by non-atomic constants in tactics/quote-scope

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1201]
```Lean
structure Foo : Type := (foo : ℕ)
open Foo
set_option pp.all true

example (P : Prop) : Π (foo : P), P
| foo := by exact foo -- error, resolves to Foo.foo
```
However if the outer `foo` is atomic (i.e. in the root namespace), then it will work. 

Reason: the parser parses both as the respective constants, and currently the elaborator invoked by `to_expr` depends on the following translation to "re-discover" the appropriate local: 
https://github.com/leanprover/lean/blob/lean3/src/frontends/lean/elaborator.cpp#L2791

It does not know to translate `Foo.foo` to `foo`, and moreover, we have lost the information about whether the user typed `Foo.foo` or `foo`. There will be a similar issue if there are multiple matching constants and so the parser returns a choice point. 

I did not try to reverse engineer the invariants, but the following two lines look suspicious to me: 
https://github.com/leanprover/lean/blob/lean3/src/frontends/lean/parser.cpp#L117
https://github.com/leanprover/lean/blob/lean3/src/frontends/lean/tactic_notation.cpp#L345

All tests pass in debug mode with these two lines commented out, and the example above works as expected.

**Comment by leodemoura** [comment]
The two lines are intended. If we remove them, we will introduce another bug. BTW, we will also *not* fix this one if we remove them. Here is a slightly more complicated example that will fail even if remove the two lines:

```lean
example (P : Prop) : P → P
| bla :=
  begin
    rename bla foo,
    exact foo
  end
```

The problem is that aliased terms (`foo -> Foo.foo`) are resolved at parsing time. Here are some possible fixes:
1- We resolve them at tactic-execution time. Cons: we may get the following counter-intuitive behavior. 
We define a tactic that contains `exact foo`. Then we invoke this tactic in two different places. In one, we have the alias `foo -> Foo.foo` and in another the alias `foo -> Bla.foo`. 
2- We store `foo` as a pair (given name, resolved name). The "given name" is what the user typed. We try to resolve it with the local scope. If it fails, then we try to use the "resolved name".

I'm inclined to use option 1 since we are already performing some "light" name resolution at tactic execution time anyway.

**Comment by leodemoura** [comment]
Implemented option 1 in the commit above.
