### ISSUE TITLE
type error with dunfold

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1260]
With the following header:
```Lean
inductive dvec {X : Type} (Y : X → Type) : list X → Type
| dnil {}  : dvec []
| dcons : Π {x : X}, Y x → Π {xs : list X}, dvec xs → dvec (x::xs)

namespace dvec

notation `⟦` l:(foldr `, ` (h t, dvec.dcons h t) dvec.dnil `⟧`) := l

def get {X : Type} [decidable_eq X] {Y : X → Type} (x₀ : X) [inhabited (Y x₀)] 
  : Π {xs : list X}, dvec Y xs → ℕ → Y x₀
| []      _                _      := default (Y x₀)
| (x::xs) (dvec.dcons y ys) 0     := if H : x = x₀ then eq.rec_on H y else default (Y x₀)
| (x::xs) (dvec.dcons y ys) (n+1) := get ys n

end dvec

constant tensor : list ℕ → Type
noncomputable instance inhabited_tensor (shape : list ℕ) : inhabited (tensor shape) := sorry
constant f {shape : list ℕ} : tensor shape → tensor shape → tensor shape

noncomputable def bar {shape : list ℕ} (μσ : dvec tensor [shape, shape]) : tensor shape :=
  let μ := dvec.get shape μσ 0, σ := dvec.get shape μσ 1 in f μ σ

meta def jrw (th_name : name) : tactic unit :=
do th ← tactic.mk_const th_name,
   tactic.rewrite_core reducible tt tt occurrences.all ff th
```
The following proof succeeds:
```Lean
lemma foo {shape : list ℕ} (μ σ : tensor shape) :
      bar ⟦μ, σ⟧ = bar ⟦μ, σ⟧ :=
suffices H_suffices : true, from
begin
dunfold bar, dsimp,
jrw `dvec.get.equations.eqn_3,
jrw `dvec.get.equations.eqn_2,
jrw `dvec.get.equations.eqn_2,
reflexivity
end,

trivial
```
whereas the following one fails after the proof seems to go through with a `type mismatch` error:
```Lean
lemma foo {shape : list ℕ} (μ σ : tensor shape) :
      bar ⟦μ, σ⟧ = bar ⟦μ, σ⟧ :=
suffices H_suffices : true, from
begin
dunfold bar, dsimp,
dunfold dvec.get,
reflexivity
end,

trivial
```
Note: even with `pp.all true`, the goals look identical before the reflexivity invocation.

You can assign this to me.

**Comment by leodemoura** [comment]
The error occurs when the elaborator tries to check if the given proof for `foo` has the expected type.
It fails to establish that using the `type_context` class with `transparency_mode == Semireducible`.

The main issue is that the type of the proof produced in the second case does not match the expected type when `transparency_mode == Semireducible`.

This behavior may seen counter-intuitive, it occurs because tactics such as `dunfold` and `dsimp` do not produce any proof since they are just replacing terms with definitionally equal ones. So, in the second case, we are applying a series of transformations, and then apply `(@refl t)`. This term `t` is definitionally equal to `bar ⟦μ, σ⟧`, but we cannot establish that using `transparency_mode == Semireducible`.

Note that if we add 
```
    type_context::transparency_scope scope_trans(m_ctx, transparency_mode::All);
```
before 
https://github.com/leanprover/lean/blob/master/src/frontends/lean/elaborator.cpp#L2774
then the second `foo` lemma will be accepted.

BTW, the `enforce_type` in the line above is unnecessary in this case because we will check it again with the kernel.

The first `foo` lemma works because the `jrw` tactic produces an actual proof term. It is essentially creating a "checkpoint". 

I think this issue may happen in more complicated settings. I think the right fix is to modify `dunfold` and `dsimp` and make sure they produce a proof term. The proof term is not needed, but we can view it as a hint/checkpoint.

**Comment by dselsam** [comment]
> I think this issue may happen in more complicated settings. I think the right fix is to modify dunfold and dsimp and make sure they produce a proof term. The proof term is not needed, but we can view it as a hint/checkpoint.

This seems like the right fix to me as well.
