### ISSUE TITLE
Examples can print trace output in the wrong order

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#1299]
I guess the evaluation of examples usually doesn't matter, so the order of evaluation is determined by parallel compilation. But the following:
```lean
open tactic expr

example : true = true := by do
trace (("a", "a")),
reflexivity

example : true = true := by do
trace "a",
reflexivity
```
prints the output
```
a
(a, a)
```
which shows that they're evaluating in reverse order. More insidiously, the second example fails here:
```lean
open tactic expr

example : true = true := by do
trace (("a", "a")),
add_decl (declaration.ax `new_ax [] prop),
reflexivity

example : true = true := by do -- error: unknown declaration 'new_ax'
trace "a",
l ← get_decl `new_ax,
reflexivity
```
but succeeds if you change the examples to definitions.

**Comment by leodemoura** [comment]
This is the expected behavior. If an user wants sequential execution, then she should use `-j 0` option. Note that, the Emacs and VS Code frontends will attach the trace information in the correct place. 

Any environment modification performed in an `example` is discarded. If an user wants to modify the environment using meta programming, then she should use `run_command`. The command `example` is for writing examples.

**Comment by robertylewis** [comment]
I see, sorry. I thought I had checked that new_ax was remaining in the environment, but I see it isn't -- I must have only looked after changing the example to a def. I see that theorems behave similarly to examples in this respect. 

The following produces a segfault:

```lean
open tactic expr

theorem d1 : true = true := by do
trace (("a", "a")),
prt ← to_expr `(true = true),
add_decl (declaration.ax `new_ax [] prt),
l ← to_expr `(new_ax),
apply l

check d1
print d1
```
