### ISSUE TITLE
Unhandled errors during import parsing

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1301]
`module_mgr::get_direct_imports` uses the parser with `use_exceptions = true`, but thrown `parser_exception`s are never handled, resulting in permanent errors shown at the top of the file.

To reproduce:
```lean
import /--
```

**Comment by Kha** [comment]
Note that `use_exceptions = false` doesn't change anything because `get_imports` does not use `protected_call`, and even then continuing with an empty list of imports leads into an assertion violation. @gebner thoughts on how to recover from such an error?

**Comment by gebner** [comment]
In a sense, `module_mgr` makes two passes over the dependency graph.  First, we look at each module, parse its dependencies using `get_direct_imports`, and set up tasks that do the parsing so that each task has a list of the task_results of its dependencies.  This is done synchronously.  In the second "pass", the tasks are actually executed--but now we only have access to the dependencies that we got via `get_direct_imports`.

So basically its enough if `get_direct_imports` returns the same imports as we would get when parsing the file.  When parsing, we ignore the exception and import nothing, so it's ok if we just ignore the error in `get_direct_imports` and return an empty vector.  (Maybe we should change this behavior to at least import `init`, though.)

I agree that the `use_exceptions` is a red herring.  The persistency bug is a separate issue, and happens because in `build_module` all the relevant scopes in inside the try block where the exception is thrown, and we then report the exception outside of the scopes.

@Kha I tried the following change which should fix (half of) the problem, but could not reproduce the assertion violation.  Where do you get it?
```diff
diff --git a/src/library/module_mgr.cpp b/src/library/module_mgr.cpp
index 5cc203fff..6ff259031 100644
--- a/src/library/module_mgr.cpp
+++ b/src/library/module_mgr.cpp
@@ -404,12 +404,16 @@ module_mgr::get_snapshots_or_unchanged_module(module_id const &id, std::string c
 }
 
 std::vector<module_name> module_mgr::get_direct_imports(module_id const & id, std::string const & contents) {
-    scope_message_context scope("dependencies");
-    std::istringstream in(contents);
-    bool use_exceptions = true;
-    parser p(get_initial_env(), m_ios, nullptr, in, id, use_exceptions);
-    std::vector<std::pair<module_name, module_id>> deps;
-    return p.get_imports();
+    try {
+        scope_message_context scope("dependencies");
+        std::istringstream in(contents);
+        bool use_exceptions = true;
+        parser p(get_initial_env(), m_ios, nullptr, in, id, use_exceptions);
+        std::vector<std::pair<module_name, module_id>> deps;
+        return p.get_imports();
+    } catch (...) {
+        return {};
+    }
 }
 
 std::tuple<std::string, module_src, time_t> fs_module_vfs::load_module(module_id const & id, bool can_use_olean) {
```
