### ISSUE TITLE
dsimp introduces recursors

### ISSUE THREAD

**Issue by gebner** [leanprover/lean3#1327]
I've seen this a few times now, here is a small example:
```lean
example (n) : nat.pred n = n := by dsimp
```
This generates the following goal:
```lean
n : ℕ
⊢ nat.rec 0 (λ (a ih_1 : ℕ), a) n = n
```

Just to be clear, I don't think we should unfold `pred` to a recursor here.

**Comment by leodemoura** [comment]
I'm having trouble reproducing this problem. Do you have other decls and/or attributes in your files?

**Comment by gebner** [comment]
It doesn't happen on `master`, only on the `bitvec_refactor` branch.

**Comment by leodemoura** [comment]
I managed to reproduce, and I'm investigating the problem.

**Comment by leodemoura** [comment]
Found the problem, `dsimp` was unfolding all non-irreducible constants when matching simp lemmas.
The `bitvec_refactor` branch added the simp lemma:
```
nat.pred (nat.succ n) = n
```
Then, in the example above, `dsimp` will try to solve the following unification constraint:
```
nat.pred (nat.succ ?m) =?= nat.pred n
```
It surprisingly solves it with `?m := nat.rec 0 (λ (a ih_1 : ℕ), a) n`, which is essentially `?m := nat.pred n`.
This solution is correct since the terms  `nat.pred (nat.succ (nat.pred n)) =?= nat.pred n` are definitionally equal. I "fixed" the problem by making sure `dsimp` will only unfold reducible constants during matching. 
The new behavior is consistent with the one used in `simp`.
