### ISSUE TITLE
RFC: lightweight default parameters

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1340]
We currently do not have support for default parameter values in Lean. So, we use the following idiom.
1- Define a "core" function that takes "configuration parameters"
```lean
/- (apply_core t approx all insts e), apply the expression e to the main goal,
   the unification is performed using the given transparency mode.
   If approx is tt, then fallback to first-order unification, and approximate context during unification.
   If all is tt, then all unassigned meta-variables are added as new goals.
   If insts is tt, then use type class resolution to instantiate unassigned meta-variables. -/
meta constant apply_core    : transparency → bool → bool → bool → expr → tactic unit
```

2- Define the common case that fixes these parameters 
```lean
meta def apply : expr → tactic unit :=
apply_core semireducible tt ff tt
```

This style is quite annoying to use when the default is not what we want. 
We now have default structure values, then we can make the approach above less ugly.

```lean
structure delta_config :=
(max_steps       := default_max_steps)
(visit_instances := tt)

meta def delta (cs : list name) (e : expr) (cfg : delta_config) : tactic expr := ...
```

Then the user can write
```lean
delta cs e {}  -- default configuration
delta cs e {max_steps := 1000}   
delta cs e {visit_instances := ff}
...
```

However, it is still a little bit annoying to keep writing `{}` when we want the default configuration.

Here are some possibilities:

1- Add a new attribute `@[default_params]`. It would instruct the elaborator to replace `delta cs e` with `delta cs e {}`. To be precise, if `f` has the attribute `@[default_params]`, then for any term `(f ...)` or `f`, if it has type `S -> A` where `S` is a structure, we automatically add the `{}`. 
This is a little bit hackish, but we don't have to change the parser nor add a new kind of binder.
It is also a small change in the elaborator.

2- Use type classes. It is described here: https://github.com/leanprover/lean/issues/1121#issuecomment-274671634

This one has two problems. It has an extra setup step: we have to define a class, and then an instance with the default values. Second, it is annoying to use when we want to change the default for a single application. We would have to use `@f ...`. This is particularly annoying if `f` has many implicit arguments, and we would also need to use many `_`s.

The main advantage of this approach is that we don't have to change anything in the elaborator and/or parser.

BTW, in interactive mode (i.e., inside `begin ... end`), we have many tricks for dealing with default parameter values, but they only work when we are interactive mode. @kha is making the process even more flexible. Now, I'm wondering, is it possible to use some of the new gadgets that @kha is designing in regular mode. If yes, then we would be able to use it to handle this issue.

I'm not considering new syntax such as 
```lean
def f (n : nat := 10) (b : bool := tt) : nat :=
...
```
This would require substantial changes in the parser and elaborator.

**Comment by leodemoura** [comment]
BTW, I'm raising this issue now, because I'm adding more and more tactics using the nasty `*_core` idiom.
I'm concerned it will be a lot of work to eliminate this idiom later using a better solution for default parameters. It would also be nice to have a default solution that we use consistently in the tactics provided by the standard library.

**Comment by avigad** [comment]
An advantage of possibility 2 over possibility 1 is that it allows users to change the default locally, by declaring a local instance. I don't know how important that is, but I thought I would mention it.

It seems a small gadget is enough to handle one default parameter, e.g.
``` lean
def opt_param (α : Type) (default : α) : Type := α

def foo (x : ℕ) (t : opt_param ℕ 0) : ℕ := x + t
```
tells the parser to interpret `foo x t` as is, but interpret `foo x` as `foo x 0`. But maybe there are nicer gadgets.

**Comment by leodemoura** [comment]
@avigad Yes, option 2 is nice if we want to change the default in a section, or in the whole file.
I think it is nasty to use when we want to change the default in a single application. I say it is nasty because we would have to write `@f` and use `_` for the other implicit arguments.

**Comment by avigad** [comment]
Good point. You are right, in most cases, that is more important.

**Comment by leodemoura** [comment]
@avigad I think using `opt_param` is better than a new attribute like I described in option 1. BTW, like in option 1,  `opt_param` should not be used in the "middle". 
I think it would give us a lot of flexibility. For example, we would be able to write:

```lean
meta def tactic.cc (cfg : opt_param cc_config {}) : tactic unit :=
...
```
`cc_config` has several fields (https://github.com/leanprover/lean/blob/master/library/init/meta/smt/congruence_closure.lean#L9-L20) Then, when using `cc`, we can write
```lean
cc
cc {ac := ff}
cc {em := ff, ac := ff}
```
We are using the default field parameters for setting the default and setting configuration options in each application.

**Comment by gebner** [comment]
> Now, I'm wondering, is it possible to use some of the new gadgets that @kha is designing in regular mode. If yes, then we would be able to use it to handle this issue.

This would be my preference.  Being able to parse some parameters in a special way is more flexible in other areas as well, for programming at least.  We could even make the gadgets user-configurable in the future by triggering parser extensions with parameter types.  How do the parameter gadgets interact with overloading?

Just two applications off the top of my head:

1) We get nicer syntax for the thunk idiom, and replace it by implicit CBN arguments:
```lean
def trace {α : Type u} (s : string) (f : bikeshedding.thunk α) : α := f ()

-- (after VM replacement)
example := trace "foo" (trace "bar" 123)
```
(Although I have no idea how this might interact with the dollar syntax.)

2) Cool debugging functions:
```lean
def debug {α : Type _} [has_to_tactic_format α] :
    bikeshedding.expr_with_source α -> tactic unit :=
λ ⟨value, source⟩, do
  value_fmt ← pp value,
  trace $ to_fmt source ++ " = " ++ value_fmt
```
Idea from the [Text[_] type in the sourcecode package for Scala](https://github.com/lihaoyi/sourcecode#debug-prints).

**Comment by Kha** [comment]
The prototype implementation looks very reasonable. For autoquotations, I would have gone with `option` instead of an explicit default value, but that makes it harder to pass to another function with default parameters. I'm a bit concerned about language complexity and "magicalness", but this still seems to be the best solution at hand.
Refactoring the autoquotation grammar into gadgets isn't very high on my to-do list right now, shall we just go with the prototype for the time being?

**Comment by leodemoura** [comment]
> How do the parameter gadgets interact with overloading?

I don't see problems. We elaborate overloaded function applications using two passes. In the first pass, we don't elaborate any arguments, we only use the number of explicit arguments to create the correct number of placeholders, and compute some information about the application type. For example, suppose we have `f {A : Type} (a b : nat) (b : opt_param bool tt) : nat`, and the application `f 0 0`. Then, in the first pass, we would produce `f ?A ?a ?b tt`. If this candidate is the only applicable one, we would elaborate the arguments in the second pass.

> We get nicer syntax for the thunk idiom, and replace it by implicit CBN arguments:

This is neat. This one would have to be implemented in the second pass when we elaborate the arguments. 

> Cool debugging functions:

This is also nice. It also need to be implemented in the second pass.

**Comment by leodemoura** [comment]
> shall we just go with the prototype for the time being?

Good for me.

**Comment by nyuichi** [comment]
Hi. Can we have infix notation for opt_param like:

```lean
infix `?=`:10 := opt_param    -- using `?=` because I'm not sure if I can use `:=` for this purpose

def f (x : nat ?= 42) : nat :=
x
```

Just a thought. Thanks.

**Comment by leodemoura** [comment]
@nyuichi This is nice.

Regarding `:=`, your concern is justified, it would produce a lot of ambiguity. 
However, we may workaround it if we implement the notation using native code.
Then, we can make sure it is only considered when parsing the declaration header.

**Comment by avigad** [comment]
I just tried a really cool experiment in Lean that is related to this discussion, and I'd like to share it with you.

To see how well we can work with deeply-embedded logics in Lean, I decided to try embedding modal propositional logic in the new, customizable logic framework. So I defined the syntax of modal logic and some sample functions:
``` lean
open modal.form

private def my_form :=
  impl (conj (box (var "p1")) (box (impl (var "p1") (var "p2")))) (box (var "p2"))

example : modal.size my_form = 10 := rfl
example : modal.num_atoms my_form = 4 := rfl
```
The problem is that it is annoying to have to write expressions in that way. Even with notation and syntactic sugar, we would still have to choose new symbols for logical connectives, etc. I thought, wouldn't it be nice if we could write something like this instead?
``` lean
check { [modal] "◾ (p1 ∧ ◾ (p1 → p2)) → ◾ ◾ (p1 ∧ p2)" }
```
I couldn't quite make that work, but I came close:
``` lean
check (by [modal] "◾ (p1 ∧ ◾ (p1 → p2)) → ◾ ◾ (p1 ∧ p2)")
```
In fact, all these work:
``` lean
check (by [modal] "p ∧ q → p")
check (by [modal] "◾ p1 ∧ q")
check (by [modal] "◾ (p1 ∧ ◾ (p1 → p2)) → ◾ ◾ (p1 ∧ p2)")

example : num_atoms (by [modal] "◾ (p1 ∧ ◾ (p1 → p2)) → ◾ ◾ (p1 ∧ p2)") = 5 := rfl

example : (by [modal] "p ∧ q → p") = impl (conj (var "p") (var "q")) (var "p") := rfl
```
The files are here: https://github.com/leanprover/library_dev/tree/master/tools/parser. 

Here is how it works. The prefix `[modal]` refers to a function that parses a string, construct a modal formula, and then returns a tactic that builds exactly that modal formula:
``` lean
prefix `[modal]`:100 := modal.parse.build_form_from_string
```
For that, I had to write a parser in Lean. But that was surprisingly easy to do. There is a really nice article by Hutton and Meijer that shows how to implement a monadic parser framework in Haskell: http://www.cs.nott.ac.uk/~pszgmh/pearl.pdf. It was straightforward to transcribe the approach into Lean. The only mild annoyance is that to avoid `meta` I had to replace arbitrary recursions by recursions up to a big number.

With that framework, it was easy to write down a grammar for modal logic: https://github.com/leanprover/library_dev/blob/master/tools/parser/modal.lean#L78-L115. For simplicity, I made all the binary connectives associate to the left and gave them all the same binding strength. But I don't think it would be much harder to write a more sophisticated Pratt-style parser.

This convinces me that it will not be hard to implement custom syntax in Lean. For example, the `opt_param` trick (btw, maybe `opt_arg` is a better name) can be used to install a tactic that says "use this parser to parse this argument." So we can use all kinds of crazy syntax for the arguments to a function. Other syntactic gadgets can be used to install custom parsers in other places, for example to parse commands in a custom tactic mode.

What this says to me is that we don't need a very complicated arrangement for customizing argument syntax. We should have one or two simple gadgets for installing custom Lean parsers, we should develop a parser library in Lean, and then move all the complexity there.

By the way, talk of custom arguments reminds me of Coq's "argument scopes," which are generally useful. If one day we have an API to Lean's internal parsing routines, an argument handler can do some light preprocessing, declare some special notation, and then call the usual internal parser.

**Comment by jroesch** [comment]
@avigad This is in line with my proposed design for parser extensions, previously I suggested two forms of parser extension `keyword`, and `command` extensions. That is we modify the parser to call user provided parser extensions in two places. 

One is a fall through case in command parsing for `command` extensions, this would allow us to add new top-level forms like the `ir_def`, `extern` and more.

The second case is in the expression position allowing us to do things like the above modal operator without resorting to strings. `modal { p ∧ q → p }`, we can argue about the semantics here, do we provide the full input stream, a token stream, the token stream between `{ ... }`, or something else.

This conversation seems to cleanly gives rise to third kind of extension which allow us to customize definition and application semantics like above.

**Comment by leodemoura** [comment]
@jroesch I don't think it is inline with the design we have discussed.
In that design, we would provide a `parser` monad that would expose actions such as `parse_expr`, `parse_binder`, `check_token`, `next`, etc. That is, it would expose the C++ parser object to Lean users. Note that the user would not have access to the input stream.  This approach has not been implemented yet because we need to refactor the C++ parser object before we expose it in the Lean API.

The approach used by @avigad is good for deep embedding. Example: parsing modal logic expressions; parsing `ir_def`; etc. However, it is not good for extending Lean itself. For extending Lean, we need actions such as `parse_expr`, `parse_binder`, etc. Another problem is that @avigad's parser monad does not have access to the Lean parser local context.

**Comment by avigad** [comment]
Yes, my thought was that for real syntax extensions we would have a "meta" parser monad with access to Lean internals. It should extend the tactic monad, shouldn't it? In most cases it will be invoked when there is a goal to be filled, and the tactic API will generally be useful.

**Comment by leodemoura** [comment]
> It should extend the tactic monad, shouldn't it?

No, it should not. The parser extension is for the parser object. It is a very different beast.
It is used in a completely different stage of the compilation process.

The stages are:
1- Parser: it produces a pre-term
2- Elaborator: converts the pre-term into a term. For synthesizing some holes, it uses the tactic framework. It creates a `tactic_state` object and invokes the bytecode interpreter.
3- Tactic: it uses the tactic monad. The tactic `to_expr t` invokes the elaborator.
Steps 2 and 3 are interlaced because of the tactic `to_expr`, but there is no interaction with the parser.

The parser monad must produce a pre-term. We need to add APIs for creating pre-terms in a convenient way.

**Comment by gebner** [comment]
>> It should extend the tactic monad, shouldn't it?
>
> No, it should not.

I think you are both right.  On the one hand, the parser monad should be a state monad around a parser_state object, without any reference to a tactic_state--after all, tactic_states only exist during elaboration.  From this point of view, the parser monad is completely independent from the tactic monad.

On the other hand, there is a lot of generic functionality right now in the meta library that is tied to the tactic monad.  It is tempting to simply transfer these tactics to the parser monad.  I'm talking about functions like the following:
```lean
meta constant mk_fresh_name : tactic name
meta constant get_fun_info_core   : transparency → expr → tactic fun_info
meta constant attribute.get_instances : name → tactic (list name)
meta class has_to_tactic_format (α : Type u)
```
These functions also make sense in the parser monad.  (Then there's also the vm monad as well.)  In particular `mk_fresh_name` is nasty, because it is the most reasonable way to create new local constants.  This makes it difficult to share code between the parser and tactic monads.
For the others we could simply take a functional approach, where we pass arguments explicitly instead of using the tactic_state.  That is, we would have `get_fun_info_core : environment -> transparency -> expr -> option fun_info`.  We already use this approach in many places.

**Comment by leodemoura** [comment]
@gebner We will have some duplication, since both of them use the `environment`. However, it is quite small. For example, from the functions you have listed, only `mk_fresh_name` is really used in the parser. I never had to use `fun_info` in the parser. Both `get_instances` and `has_to_tactic_format` require a well-formed local context, which we don't have at parsing time. 

Regarding code duplication, we can define a type class with the shared interface.

**Comment by Kha** [comment]
So if we want to move `opt_param` and eventual friends to the parser monad, we will have to move it out of the elaborator stage first. Which we need to do either way for things like `using_ident` that are not valid expressions. The only way of doing that which I can see is to disregard/forbid overloading, just like the tactics parser does right now. E.g.:

* if the parser sees an unambiguous identifier, it fetches its signature and invokes the parameter parsers, if any
* as a safeguard, if the elaborator selects an overloaded definition, it checks that its signature does not contain parameter parsers (we could also do that in the parser against the whole overloaded set)

**Comment by leodemoura** [comment]
> So if we want to move opt_param and eventual friends to the parser monad, we will have to move it out of the elaborator stage first.

As you said, we would have to forbid overloading. 
I think this is bad, since `opt_param` will be extensively used. For example, I will refactor many tactics to use it, and avoid the nasty `*_core` idiom.
The current approach seems to be working really well. I don't see a good motivation for changing it for something that is more restrictive.

I think the `bikeshedding.thunk` is another example where we want to support overloading. For example, `trace` is already overloaded. 

How many extensions do we need when writing regular Lean code?
For sure, it is nice to have many of them when writing interactive tactics inside of `begin ... end` blocks.
It is also nice to be able to write new ones. For example, in the thread https://groups.google.com/forum/#!topic/lean-user/G71qvZVZXFk, I wanted to add a new extension for 
the `rcases` argument
```lean
example (a : foo) : nat :=
begin
  /- creates two goals with hypothesis names: h.1, x, y, h.4 -/
  rcases a : [(0,1,`x), (1,0,`y)]
end
```

**Comment by leodemoura** [comment]
@Kha 
The following works with the current `opt_param` implementation:

```lean
def f (a b : nat) (c : nat := 4) :=
a + b + c

local infix `++` := f

vm_eval 1 ++ 2
```

**Comment by avigad** [comment]
For me, a nice application would be to be able to implement `obtains` syntax in Lean. Does the overloading problem make that impossible?

**Comment by leodemoura** [comment]
The overloading only affects parser extensions for parsing parameters. `obtains` would be a keyword directed extension. It would work as follows: when the next token is `obtains` the parser will pass control to the parser extension.

That being said, to be able to implement `obtains` in Lean, we would need to provide APIs for creating pre-terms in the format expected by the elaborator. `obtains` is syntax sugar for `match`. Thus, the parser extension needs to be able to create a pre-term that represents a `match` expression.

**Comment by jroesch** [comment]
@leodemoura's To clarify, I was thinking in the other direction; that @avigad's example can be built using the general parser extension mechanism we have been discussing. The only constraint is that the embedded language must share the same token set as Lean. You could define a custom parser extension which constructs the deeply embedded term directly from the token stream. This is nice because it allows you to reuse all the standard error reporting and position information when parse errors occur.

For example in the keyword style `modal { p ∧ q → p }` would present the tokens `p`, `∧`, `q`, `→`,  `p`.

The only thing required are primitives for matching single tokens.

**Comment by Kha** [comment]
> How many extensions do we need when writing regular Lean code?
> For sure, it is nice to have many of them when writing interactive tactics inside of begin ... end blocks.

Okay. I am completely fine with supporting custom parameter parsers only in tactic blocks and keeping the regular term language (mostly :) ) sane.

**Comment by leodemoura** [comment]
@kha What are the insane parts? Any suggestions on how to fix them?

**Comment by Kha** [comment]
Oh sorry, I was just alluding to the special parameter types that are
already implemented (opt_param and thunk). But they are certainly useful.

**Comment by leodemoura** [comment]
I'm closing this RFC since it has been implemented.
