### ISSUE TITLE
Emacs selection highlighting stops working after `C-c C-g` is used

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1352]
I have this problem on Emacs 24.3 and 24.5.1.
@rlewis1988 also managed to reproduce the problem on his machine (Emacs 24.4).
Emacs 24.5.1 is the one installed with Ubuntu 16.04.

BTW, we can still select and copy/cut text. However, we can't see what we are selecting.

**Comment by robertylewis** [comment]
>BTW, we can still select and copy/cut text. However, we can't see what we are selecting.

When I try to use shift-arrows to select text, /something/ gets selected, but not what I expect. For example, I start with the cursor at the end of this text:
```lean
begin

end
```
and shift-up twice, so that the cursor is at the `i`. There's no highlighting to show that anything is selected. I copy and paste, and the result is just `in`.

**Comment by leodemoura** [comment]
@rlewis1988 The commit above fixed the problem for me.
I will close the issue. We can reopen it if you are still having problems.

**Comment by robertylewis** [comment]
Appears to be fixed in 24.4.1 too!
