### ISSUE TITLE
auto-completion menu overflowing screen

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#137]
On my notebook, the auto-completion sometimes doesn't fit on the screen. 
Possible solution: truncate the declaration type.

**Comment by soonhokong** [comment]
1. It turns out that there is already a routine truncating long annotations in `company.el`
   
   https://github.com/company-mode/company-mode/blob/master/company.el#L2116-L2118
2. I believe that the problem is caused by the use of unicode characters in Lean and company-mode and emacs do not compute the width of strings accurately when unicode characters are used.
3. I implemented a workaround in 047659199210514f3d88cfc9c8943f2fdc89a81d for company-mode to use a smaller window-width (95% of it, instead of 100%). This solves the problem when company-mode displays candidates on the left-hand side of a window. However, we still have the problem when it displays candidates on the right-hand side of a window.

**Comment by leodemoura** [comment]
Using a better unicode font set also minimizes the problem. The problem almost disappeared after I added the following command to my .emacs

(when (member "DejaVu Sans Mono" (font-family-list))
  (set-face-attribute 'default nil :font "DejaVu Sans Mono-12"))

**Comment by soonhokong** [comment]
@leodemoura, it helped me, too. I put it on the README.md file: https://github.com/leanprover/lean/blob/master/src/emacs/README.md

**Comment by leodemoura** [comment]
@soonhokong The main issue is that the "drop down box" used in company mode is just an "illusion". That is, there is no drop down box. They simulate it by changing the background color.
So, their illusion fails whenever there are characters with a different width.
I think their trick/illusion is quite clever since it supports even Emacs in terminal mode.

That being said, I don't see good solutions for the problem. Here are some random thoughts
- We could include a nice monospaced font in the Lean distribution. 
- We could use a different package for auto-completion. If the package creates a real "drop down box", then the problem would not happen. The drawback is that the auto-completion would not work in Emacs terminal.

**Comment by soonhokong** [comment]
There is a related discussion in https://github.com/company-mode/company-mode/issues/207.

**Comment by soonhokong** [comment]
I agree that there is nothing much we can do for this one. Let me close this..
