### ISSUE TITLE
When lean is called with --server, -T and -M then it does not report error messages.

### ISSUE THREAD

**Issue by johoelzl** [leanprover/lean3#1371]
Contents of `test.log`:
```{"seq_num":0,"command":"sync","file_name":"test.lean","content":"bug\n"}```

When I call lean with `-T` and `-M` option, it does fails to report an error:
```
$ lean --server -T 100000 -M 1024 < test.log 
{"message":"file invalidated","response":"ok","seq_num":0}
{"cur_task":{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1},"is_running":true,"response":"current_tasks","tasks":[{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1}]}
{"cur_task":{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1},"is_running":true,"response":"current_tasks","tasks":[{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1}]}
{"cur_task":{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1},"is_running":true,"response":"current_tasks","tasks":[{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1}]}
```

Without this error it correctly reports this error:
```
$ lean --server < test.log 
{"message":"file invalidated","response":"ok","seq_num":0}
{"cur_task":{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1},"is_running":true,"response":"current_tasks","tasks":[{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1}]}
{"cur_task":{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1},"is_running":true,"response":"current_tasks","tasks":[{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1}]}
{"cur_task":{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1},"is_running":true,"response":"current_tasks","tasks":[{"desc":"parsing test.lean","end_pos_col":0,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1}]}
{"msgs":[{"caption":"","file_name":"test.lean","pos_col":0,"pos_line":1,"severity":"error","text":"command expected"}],"response":"all_messages"}
```
This was tested on Fedora with `gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)`.

It works on Ubuntu 16.10 with `gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005`.

**Comment by gebner** [comment]
Note that the multi-threaded server mode is non-deterministic: the error messages are reported asynchronously, about 100ms after they are produced.  There is no guarantee on the order of the response messages.
In addition, the server terminates when stdin is closed.  We should probably cancel all tasks at that point, because why keep running if the user closed the editor (still needs to be ~done~ merged).  Error messages that are not yet produced or just queued for reporting will not be sent to the client.

If you paste the `test.log` file by hand, you should see the error message after about 100ms.  You can also add a sleep command to the server input (Leo added the command for this purpose):
```
{"seq_num":0,"command":"sync","file_name":"test.lean","content":"bug\n"}
{"seq_num":1,"command":"sleep"}
```
Now `lean --server=test.log` should return the error message as a response.  (Sleep is one second, this may not be enough if the standard library needs to be recompiled.)

(However none of that explains the problems you experience in Emacs.)

**Comment by johoelzl** [comment]
It looks like e551b4ff0952005c470de67fc3836cc82a93caa fixes the problem! :-)
