### ISSUE TITLE
lean 3.0.0 binary fails to run in server mode (in VS Code) on Windows

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover/lean3#1389]
Symptom is syntax highlighting but no further compiler-based functionality. Said to be due to lack of -T option in distributed 3.0.0 binary. Problem is also said to be fixed in daily build. I will test that but can't do it right this moment. Fix would be to update distributed binary from 3.0.0 to a more recent version. More details follow, from conversation on Google Group. 

----

On Monday, February 20, 2017 at 2:32:51 PM UTC-5, v.v.p...@gmail.com wrote:
Yeah, if you build lean from github, it should work fine. The timeout option was introduced in this commit: github.com, which was after the 3.0.0 release. I encountered the same thing but didn't bother opening an issue, just built the latest version of lean from github instead.

понедельник, 20 февраля 2017 г., 22:23:07 UTC+3 пользователь Kevin Sullivan написал:
Hmm, yes, I'm using the 3.0.0 release. I'm not seeing any error messages about failures to start the server. But the server failing to start would explain the symptoms, I suppose. Is there an open issue for this matter? I don't see one here: https://github.com/leanprover/vscode-lean/issues. As for building from scratch, are you saying that the most recent code on GitHub fixes the issue? --Kevin 

On Monday, February 20, 2017 at 2:06:29 PM UTC-5, v.v.p...@gmail.com wrote:
(1) Syntax and other errors are not highlighted in the code

I suppose you're using the 3.0.0 release of lean from here: https://github.com/leanprover/lean/releases/? After this commit to vscode-lean: github.com the VS Code plugin is unable to start lean of version 3.0.0 in server mode since lean of that version doesn't seem to support the '-T' command line option which the plugin is currently using to start the server. One workaround would be to build lean from git.

понедельник, 20 февраля 2017 г., 19:04:39 UTC+3 пользователь Kevin Sullivan написал:
CONTEXT: I'm new to both VS Code and Lean. I've got the environment working. Files with .lean extensions show up as Lean files in VS Code. Control-Shift-R runs the compiler and output is produced. I've ported a few simple projects to Lean.

QUESTIONS:

(1) Syntax and other errors are not highlighted in the code. Indeed, no functions other than very simple syntax highlighting seem to be working. What am I missing?

(2) How do I set or, more importantly, extend, the LEAN_PATH variable on a per project/top-level-directory basis?

Thank you,
Kevin Sullivan
University of Virginia

**Comment by jroesch** [comment]
Hello Kevin,

Sorry about that, the error is just an oversight by me.

I posted a follow-up to the Google Group conversation, many active users are using the version of Lean in `master`, so I added these options due to another user request last week. 

I just added initial support for multiple Lean versions to the VSCode extension. 

It should now work on both versions `3.0.0` (release) and `3.1.0` (master). 

If you update the VScode extension from the marketplace it should boot with no errors.

If you have anymore issues with the VScode mode you can file them here: https://github.com/leanprover/vscode-lean. 

I am the primary maintainer of that editor mode, and its easier if editor issues are there :)

**Comment by kevinsullivan** [comment]
Thank you for the quick fix. And it's true, I wasn't sure whether the problem was here (lean) or there (vscode-lean). Now I know. Best, --Kevin
