### ISSUE TITLE
Equation compiler reports a problem in the clear tactic

### ISSUE THREAD

**Issue by johoelzl** [leanprover/lean3#1414]
The following snippet produces a `clear tactic failed, hypothesis 'a' depends on 'a'` error:
```
def Union {α : Prop} {β : Type} (s : α → set β) (x : β) : Prop :=
∃ i, x ∈ s i

example (y : ℕ) (t : set ℕ) : Union (λH : (∃x, x ∈ t), t) y → true
| ⟨⟨z, z_ex⟩, y_in⟩ := ⟨⟩
```

When I unfold `Union` it works. Somehow also the nesting of both existentials is important for the error.

**Comment by leodemoura** [comment]
@johoelzl 
The context at time of failure looks like this
```
y : ℕ,
t : set ℕ,
a : ∃ (x : ℕ), x ∈ t,
a : y ∈ (λ (H : ∃ (x : ℕ), x ∈ t), t) a
```
There is a "fake" dependency between the second `a` and the first `a`. The dependency disappears if we beta reduce the second one.  It is not clear to me what is the right way to fix this.
The dependency disappears if we beta reduce and try again. However, beta reduction is just one possible instance of a more general problem: artificial dependencies that disappear after applying reduction.
There are different forms of reduction. In practice, it is infeasible to compute the normal form since it can be extremely huge. 
Another issue: should we try to only apply reductions that may potentially remove the dependency? For example, we may have several subterms that can be beta-reduced, but only one of them contains `a`.

Consider the following variant:
```lean
def wid {p : Prop} (h : p) {α} (a : α) : α :=
a

example (y : ℕ) (t : set ℕ) : Union (λH : (∃x, x ∈ t), wid H t) y → true
| ⟨⟨z, z_ex⟩, y_in⟩ := ⟨⟩
```
The fake `wid` is used just to introduce a "fake" dependency that cannot be removed using beta reduction.

As I said above, it is not clear to me what is the right way to fix this.
Here are possible fixes. 
1- We use the new `dcases_on` (for inductive predicates) in the `cases` tactic.
This is a dependent eliminator, and it will eliminate any occurrency of the major premise with a constructor application. That is, after applying it, the `a` in the second `a` will become an `Exists.intro` application.
2- Ignore `clear` tactic failures in the `induction` tactic. Remark: the `cases` tactic uses the `induction` tactic.
Even if we implement 1, this also seems the right thing to do, since users may use `induction` directly with a non-dependent eliminator, and it will fail if they try it in this kind of scenario.

What do you think?

**Comment by johoelzl** [comment]
Ah, I didn't realize that `cases_on` was different btw inductive `Prop`s and `Type`s. Is this a problem of large elimination? Are there cases where dependent elimination is not possible (besides large elimination)? 

Both fixes seams to be the right solution.
I guess the `clear` tactic should have a flag to do nothing if there is a dependency?

**Comment by leodemoura** [comment]
> Ah, I didn't realize that cases_on was different btw inductive Props and Types. Is this a problem of large elimination? Are there cases where dependent elimination is not possible (besides large elimination)?

Here is the full story:

Before Lean 3.0, we supported different flavors of type theory. Example: we could choose whether we had `Prop` or node; whether it is proof irrelevant or not; CoC only (i.e., no inductive datatypes); etc. One of these flavors was the HoTT mode.
Moreover, the inductive type module (when enable) would use produce non-dependent eliminators for inductive predicates. So, we could experiment with the following flavor of type theory: Prop, no proof irrelevance, and no dependent elimination for inductive predicates. 
Moreover, we would be able to derive the dependent eliminator when proof irrelevance is enabled.
Another motivation for having the non-dependent eliminator for inductive predicates is that in 99% of time this is the one we want, and it is simpler.

Now, we support only one flavor. So, we considered changing the kernel and generating a dependent eliminator for all inductive datatypes (regular one and predicates). This is what @jroesch was referring too in the slack channel when he wrote about `drec`.

Unfortunately, this is not a small change. The library would break in many different places. The C++ code too since it assumes the non dependent eliminators are the primitive. Moreover, this change would not benefit regular users since they seldom use recursors directly. It would also create problems for advanced users since their files would break in multiple places. So, I don't see any motivation for implementing this solution, and investing a lot of energy on it. I think @jroesch's argument in favor of uniformity is very weak in this case.

That being said, this is how the kernel works now when we declare an inductive datatype `C`.
1- It generates the constructors and `C.rec` recursor. If `C` is a predicate, then this recursor is a non-dependent eliminator. 

2- Outside of the kernel, we automatically generate the following auxiliary recursors:
- `C.rec_on` (like `rec` but major premise before minor premises) 
- `C.induction_on` (like `rec_on` but only eliminates into `Prop`)
- `C.cases_on` (like `rec_on` but it is not recursive)
- `C.brec_on` (course of values recursion, and it cannot be defined for inductive predicates)
- `C.binduction_on` (like `brec_on`, but only eliminates into `Prop`)
- `C.drec` (for inductive predicates only, it is the dependent eliminator)
- `C.drec_on` (like `drec` but major premise before minor premises)
- `C.dcases_on` (like `drec_on`, but it is not recursive)
They are all definitions. We can print them using commands such as `print C.brec_on`.

The `drec` family has been implemented a few days ago. Before that, we were defining them by hand.

**Comment by johoelzl** [comment]
@leodemoura thanks for the overview! I really like that Lean only generates `T.rec` in the kernel and the rest is defined.

Thinking about this, do we really want the solution 1? It might be actually nicer just to have 2) and not 1)! By proof irrelevance it only matters that we have a proof (and as I understand from @gebner 's recent comment on slack it is even syntactic irrelevant) So the behavior to not clear a `p : Prop` from the context and use it instead of a concrete proof in the resulting goal is a nice abstraction.

What do you think? Are there cases where the syntactic presentation is important? Like we now that `x` is a certain witness for a existential proof?

**Comment by leodemoura** [comment]
> What do you think? Are there cases where the syntactic presentation is important? Like we now that x is a certain witness for a existential proof?

As pointed out by @gebner, the accessibility predicate is a good example.
Here is a proof that uses it.
https://github.com/leanprover/lean/blob/master/library/init/wf.lean#L49
Without `drec`, we can't finish the proof using `rfl`. The goal goes from
```lean
 fix_F F x acx = ...
```
to
```lean
 fix_F F x (acc.intro x a)= ...
```
The application on the right hand side is now convertible to a term of the form `F x ...`.
Without `drec`, we would have to change the goal using `show ..., from ...` or using the `change` tactic, and replace `acx` with a constructor application that has the same type (`acc.intro x a` in this case).

For equality and heterogeneous equality, we have "K", and we don't need to make this change manually. But "K" is only applicable to inductive datatypes that have a single 0-ary constructor (e.g., `eq.refl`). So, the process of replacing the term with a definitionally equal constructor application would have to be performed manually in all other cases. I'm not sure how often we will encounter this kind of issue.
A few weeks ago, @jroesch hit this problem when he was working with an inductive predicate, and this is why I implemented the `drec` constructions this week.
