### ISSUE TITLE
Inherited fields lose their attributes

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1443]
In

    structure X :=
      (a : unit)
    attribute [ematch] X.a
    structure Y extends X
    print Y.a

one sees that Y.a does not have the attribute `[ematch]`. I had expected that inherited fields would automatically inherit their parents' attributes.

(In my category theory development I have some long chains of inheritances, and for automation it is important to mark some fields with `[simp]` and `[ematch]`. Currently I have to copy and paste these attributes all down the hierarchies.)

**Comment by leodemoura** [comment]
I'm not sure what to do with this one. I never intended to copy attributes from the parent fields.
Does the automatic copying always make sense? Is this the behavior users always want for any kind of attribute? Attributes are dynamic in Lean. What do we do in the following case?
```lean
structure X := (a : unit)
structure Y extends X
attribute [ematch] X.a
```
That is, the attribute for `X.a` was set after `Y` was defined.
@kha @gebner What do you think?
We can implement a tactic such as `copy_field_attrs (src tgt : name) (fnames : list name) : tactic unit`, and tell users to use it explicitly.

**Comment by kim-em** [comment]
In your example, I wouldn't have expected the later attribute to have any effect on `Y`; just that at the moment we use the `extends` keyword we make `Y` behave as much like `X` as possible.

(No particular concern if you decide against this behaviour; in my use cases I seem to always want to copy attributes, but it's not particularly onerous to do by hand.)

**Comment by gebner** [comment]
I think that copying the attributes is only a very limited solution, similar problems will also arise with other lemmas that are not structure fields.  Here we have a simp/ematch-lemma about categories, and want to apply it to e.g. lax monoidal categories:
```lean
@[ematch, simp]
lemma left_identity (c : Category) {X Y : c^.Obj} (f : c^.Hom X Y) :
  c^.compose (c^.identity X) f = f := _
```
The first problem is that `^.compose` is actually a different function for categories and lax monoidal categories, namely `Category.compose` and `LaxMonoidalCategory.compose`, resp.  The simplifier can't use the lemmas defined for categories because they have a different top-level function symbol.

One solution that was already mentioned would be to define a tactic that transports lemmas about categories to lemmas about lax monoidal categories.  Maybe Johannes' transfer tactic can already do that?

Another approach is to refactor the category theory development in a similar way as the algebraic structures are implemented in the Lean library, i.e. using a partially unbundled approach with type classes.  IIRC, we chose the partially unbundled approach precisely so that operations such as `compose` are the same function on every structure, and can be easily matched by the simplifier.

@semorrison Try writing `lemma` instead of `definition` when possible, this should make the editor more responsive since lemmas are elaborated asynchronously (on a separate thread, and in parallel).  You can also try to replace `abstract { blast }` by `async { blast }`, but that might fail if there are still meta-variables in the subgoal.

**Comment by kim-em** [comment]
@gebner, thanks for the suggestion regarding `lemma`. Unfortunately `async` failed essentially everywhere, although I don't quite understand what the metavariables it is worried about are.

**Comment by gebner** [comment]
> Unfortunately async failed essentially everywhere, although I don't quite understand what the metavariables it is worried about are.

You can see them with `set_option pp.all true`, they are universe metavariables.  I guess `async` should include them as separate universe parameters in the auxiliary declaration.
```
44:82: goal contains metavariables
state:
⊢ ∀ (C : tqft.categories.Category.{?l_1 ?l_2}) (X : C^.Obj),
    @eq.{?l_2+1} (C^.Hom X X) (C^.identity X) (C^.compose X X X (C^.identity X) (C^.identity X))
```

One more thing: please create a `.project` file in the root directory of `lean-category-theory`, i.e. `touch lean-category-theory/.project`.  Then we only start one Lean server for the whole project, and changes that you make e.g. in `tactics.lean` are immediately visible in the other files.

**Comment by johoelzl** [comment]
I don't know what a _lax monoidal category_ is. But currently `transfer` lacks support for type constructors (e.g. you can not transfer something like `forall x : list t, p x` where `t` is the type you want to transfer into another one. I know how to do it, but it requires some work.

If your theorems are of the form `forall x y z : Category, p x` and there are no type variables, your theorem could be transfered fine.

**Comment by kim-em** [comment]
Should I raise an issue asking to improve `async` so it can cope with these universe metavariables?

(Thanks for the reminder, @gebner, about the `.project` file.)
