### ISSUE TITLE
dsimp and dunfold should fail if they don't do anything

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1449]
See the discussion at <https://groups.google.com/d/msg/lean-user/PXiYQEZjLpE/SqYiwiJoEAAJ>. @Kha suggested that this behaviour is a bug. In particular, we should expect

    structure X := ( a : Type )
    definition x : X := { a := unit }
    definition y : X := { a := unit } 
    lemma t : x^.a = unit := begin
                               dsimp [ y ],
                               dsimp [ x ],
                               refl
                             end

to fail.

**Comment by leodemoura** [comment]
@semorrison I'm not sure. @kha and I discussed this issue today.

In interactive mode, I agree failure is a good option, but when writing new tactics it is a pain.
For example, yesterday, I spent a lot of time when one our tests stopped working: `cpdt3.lean`. It uses `mini_crush`.  After a few hours, I tracked the problem to `simp` failing  here:
https://github.com/leanprover/lean/commit/c086c58b4a0bd56a6b7172ead28a3a218e3a1706
because it didn't change anything.
When we are writing new tactics, it is quite inconvenient to write `try simp`, or use `(... simplify ...) <|> ...`. In principle, we can implement a "safe"-version that doesn't fail (i.e., they do the `try` internally for us).  However, this is not very efficient since a choice point is created. As we start using more efficient data structures, choice points are bad because they will prevent destructive updates from happening. 

Another issue raised by @kha is whether we should backtrack or not after progress has been made.
This behavior often obscures helpful error messages. He suggested we support a tri-state (success/backtrack/fail) in the tactic framework.
