### ISSUE TITLE
`Sort u` is specialised to u = 0, allowing apparent proofs of false theorems.

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1487]
In <https://gist.github.com/semorrison/f9703d01d2f9a3016a49dedacf39ee34>, the proof on line 32 should not be possible, however Lean claims that it is true.

If you look carefully, with `set_option pp.universes true`, at the resulting signature, you see that we have defined

    IdentityNaturalTransformation.{u_1 u_2} :
      Π (F : Functor.{u_1 u_2 0 0} ?M_1 ?M_2), NaturalTransformation.{u_1 u_2 0 0} F F

This is not the expected signature --- in particular the two zero universe values should still be arbitrary. Lean has decided that by specialising those universe parameters to zero, it can provide a proof of naturality, because we are then looking for an equality between two proofs.

Although Lean is strictly correct, this seems a very misleading situation, where something false has apparently been proved, and the only way to see what's happened is to inspect universe annotations on the resulting lemma.

(Note that changing `Sort` to `Type` in lines 4 and 5, Lean correctly says that it is not possible to prove the required result in line 32. Then uncommenting out lines 8-12, we get the correct proof, with no universe specialisation cheating. Further, note that if we stay with `Sort`, and uncomment out lines 8-12, we still get the trivial proof with universes specialised to zero, rather than the desired one.)

**Comment by kim-em** [comment]
(I initially posted this at [lean-user](https://groups.google.com/d/msg/lean-user/rRUWD0T-5Jg/GG6D2NU3CAAJ).)

**Comment by intoverflow** [comment]
The indicated behavior is also useful, though. Consider the case of proving that a category has all limits. The statement of the claim includes universe vars (coming from the domain of the diagrams whose limits are claimed to exist). For categories which merely have all limits for certain universe levels (such as the category of Lean terms and functions), the behavior described above correctly restricts the statement of the claim. Or, at the very least, it'd be an annoyance if Lean rejected the claim because it didn't literally hold for all universe levels.

**Comment by leodemoura** [comment]
First a clarification, if the user specified the universe parameter `u`, then `u` **never** magically becomes `u := 0` in their definitions. What is happening in your example is that `Sort ?u` (where ?u is a metavariable, aka placeholder, aka hole, aka unification variable) is being assigned to `?u := 0`. 

I agree the assignment `?u := 0` is not desirable, but I want to emphasize this can only happen in very particular situations.
1- User is leaving universe parameters implicit. This is your case, you don't specify the universe parameters for `Category` and `Functor` at `IdentityNaturalTransformation`.
2- User is using automation for constructing definitions instead of lemmas. In Lean, the type of the lemma/theorem cannot be influenced by its proof. We elaborate the type of the lemma before we elaborate the proof. That is, when we elaborate the proof, we don't have universe metavariables anymore. This is your case, you are using `definition` and automation.
3- User is using automation that is tries to synthesize `subsingleton` type class instances. 
We have the following instance in the standard library
```
instance subsingleton_prop (p : Prop) : subsingleton p :=
...
```
https://github.com/leanprover/lean/blob/master/library/init/logic.lean#L763
It says that every proposition has at most one element.

I'm pushing a commit that address the issue by disabling the assignment of universe metavariables when trying to synthesize elements of the type class instance `subsingleton a`.

**Comment by kim-em** [comment]
Thanks for the careful clarification. The distinction between lemmas and definitions here makes sense, but I hadn't expected it.
