### ISSUE TITLE
`rename` does not change references

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1513]
```lean
example (n : ℕ) (h : n = 0) : n = 0 :=
by rename n m
```
```
tactic failed, there are unsolved goals
state:
m : ℕ,
h : n = 0
⊢ n = 0
```

**Comment by leodemoura** [comment]
This bug was introduced by this commit: https://github.com/leanprover/lean/commit/fd08a9badf2bde0cb24b5971d78753ee631790ea
I added this commit because it was a pain to trace expressions when debugging Lean:
the user facing names were stored in the local context, and we only had access to them if we had a reference to the local context.
This commit is quite convenient for debugging, but introduced this bug.
It is not clear how to fix this. We can 
1- Retract the commit that introduced the problem
2- Modify `rename_user_name` https://github.com/leanprover/lean/blob/master/src/library/local_context.cpp#L282-L293, and propagate the new name to all dependencies. The new version is much more expensive. We don't use `rename` very often. Thus, the overhead may not be a big issue.

**Comment by Kha** [comment]
> We don't use rename very often. Thus, the overhead may not be a big issue.

Yes, I agree.
