### ISSUE TITLE
[RFC] Minimal Standard Library

### ISSUE THREAD

**Issue by jroesch** [leanprover/lean3#1523]
I propose that we remove everything but the basics from the standard library. 

Many other languages have taken this approach for a variety of reasons. Most importantly it allows libraries to evolve uncoupled from language release cycles, reduces the maintenance burden on the core team, and keeps us free from standard library bloat that has happened in older languages without easy package distribution.

I am suggesting this change now because @gebner has done an awesome job prototyping a package management tool that we should start to dog food ASAP. 

I feel that these problems are exacerbated in a proof language as there is a desire to have as many useful facts as possible at your fingertips. It seems to lead to incoherence in the standard libraries and inconsistent quality control as evidenced by Coq's library which has many half finished libraries.

I propose that we convert `library_dev` to a contrib style development where we curate awesome developments in the community or incubate standard library extensions. We might also want to ship a batteries/haskell platform/stdx style package which includes a good standard set of packages.

Concrete of examples of what could be removed from the standard library today:
- smt2 bindings
- super
- mini-crush

Since the library is already pretty minimal, my purpose is to argue new additions should go in packages and not in the standard library.

A pointer to Rust's original proposal to do the same: https://github.com/rust-lang/rfcs/blob/master/text/1242-rust-lang-crates.md.

**Comment by leodemoura** [comment]
I strongly support this RFC.

**Comment by avigad** [comment]
I support it too, but we should talk about how we intend to "curate awesome developments in the community or incubate standard library extensions." Right now `library_dev` is an awkward mix of things: a staging ground for the standard library, a place for experimentation, a staging ground for more specialized theories, etc. 

Here are some different kinds of libraries:
- The standard library. This ships with Lean. It should be small, carefully curated, and we want to keep incompatible changes minimal across releases.
- Individual specialized libraries. These are easy. Any user (or developer) can create a library, try to make it useful, and take responsibility for maintaining it in their own space.
- Project-managed specialized libraries. For example, I think the project should support a good analysis library, which does not have to be part of the standard library but should be carefully maintained and kept up to date. Similarly for other branches of mathematics, program verification, etc.  
- Experimental libraries. We may (or may not) want to support spaces for shared experimentation, with bugs, sorry's, parts of the libraries that don't compile, and no promise or expectation of stability at all.

@jroesch How do Rust and other programming languages manage these different aspects of library development? Here is one way we can go about it: 
- Keep `library_dev` as the wild west, for shared experimentation, with no expectation of stability. Anyone can contribute anything, and if some folders don't compile, so be it.
- Create a staging ground for the standard library, and be picky as to what goes there. Contributions need to be reviewed and discussed by the development team.
- Create a single repository or multiple repositories to contain the specialized libraries that we want to support as a project. Each specialized library should have managers/curators that take responsibility for maintaining them and ensuring the quality of the contents.
- Let individual users develop and maintain their own libraries, and maintain a central list.
Why do you think?

**Comment by jroesch** [comment]
Rust has a couple different ways of handling this problem. I think that the highest level of stability is reserved only for the standard library. Most libraries have their own stability policies.

I believe that when they accept repositories to the "nursery" they must adhere to some of the same stability guarantees. 

The "nursery" acts both as official endorsement and also a staging ground for inclusion into the standard library. At the same time people will submit pull requests or feature additions directly to the standard library if they "fit" with the current functionality. For example exposing more of the file system API.

Finally there are things like https://github.com/brson/stdx, which curate the open source ecosystem, and allow users to pull in *many* useful crates (the packaging unit) at once.

It seems we will probably have a mix.

My feeling is that we will probably maintain many libraries ourselves, for example the math libraries useful to you and your students, my recent z3 bindings, super, mini-crush, and so on.

I think we should probably put together a registry of some sort as well (https://crates.io/, https://hackage.haskell.org, and so on).

I'm happy to chat more on Slack, just trying to get the ball rolling on these things. I think we are near the point where we need to do these things to continue to scale as a project.

**Comment by leodemoura** [comment]
I like this PR because I want a very small library in this repository.
Note that I'm not saying the library in this repository is **the** standard library. 
Other systems (e.g., Agda) have separate repositories for the standard library.
I will call the .lean files in this repository as the "core standard library". I think it should be small for the following reasons:
1- It distributes the effort of maintaining the Lean libraries. In Lean 2, I was wasting a huge amount of time fixing/adjusting the standard library. This is particularly important when we want to refactor something.
2- We don't waste time with dubious and poor quality PRs. We also have to waste time making sure the PR follows the coding conventions. 
3- We avoid modules in the core library that are useful only for a very small set of users.

**Comment by digama0** [comment]
One reason I don't like the idea of separating every little development into a separate Git repo is that it wasn't really designed for that, and submodules will give a lot of headache. (I know that Git repos are not exactly what we are talking about here, but it is a natural next thing to expect if the library is decentralized.) So I would like to avoid hundreds of tiny projects in their own repos that we have to maintain.

I propose a three-tiered approach:

* `lean` repository: Core library only. Everything is `prelude`. Everything here should either be used by another theorem in the core library, a C++ routine, or should have a good argument for why lean will not work properly without it.
* `stdlib` repository: The standard library. This is a large and organized development of standard mathematics, roughly analogous to the lean 2 stdlib, and containing most of the current `library` and `library_dev` repos. This should be cohesive and curated by the team. That is, everything in here should work with everything else, to give it "canonicity".
* `library_dev` repository: One-off projects and specialized developments; highly modular. This can be used as a staging ground for `stdlib` developments. This is something like Metamath's mathboxes or Isabelle's AFP.

All three repos will be maintained by the team, and we should attempt to keep them in a properly compilable state. However, the maintenance in the `library_dev` repo will be minimal, just stubbing out anything that can't easily be fixed and notifying the original author.

There will also be third-party repos and forks - these of course get no maintenance and the interaction of these with the big three will be entirely up to their authors. We would encourage them to submit their developments to `library_dev` so that they will be kept up to date.
