### ISSUE TITLE
Inductives over parameter types

### ISSUE THREAD

**Issue by jldodds** [leanprover/lean3#1525]
The following definition does not typecheck

```
section t

parameter t : Type

inductive eqt : t -> t -> Prop
| refl : forall x : t, eqt x x

end t
```

this seems to happen if the return type depends on a parameter (it's fine if a parameter to the inductive depends on a parameter)

**Comment by alashworth** [comment]
Hi, since you haven't received a response yet, I'm commenting.

As far as I am aware, a parameter of an inductive type is not allowed to be used as a bound variable in the type of its constructor.  I say this because it was this way in Coq, and Lean is very similar. The solution is to either declare t as a constant, or change the parameter declaration to a variable.

If this is not the case, I await re-education by someone more knowledgeable than me :+1: .

**Comment by jldodds** [comment]
Indeed, and looking at it again, I had it mixed up. This makes sense

**Comment by jldodds** [comment]
I'm reopening this issue because I think parameters in lean are fundamentally different from those in Coq.

My current understanding is that a lean parameter is the same as a variable, but it is automatically applied within a section. If this is the case, I see no reason that the above definition shouldn't work, as it works just fine with a variable.

The mapping seems to be that Coq variables are functionally equivalent to both lean variables and parameters (parameters are automatically applied within a section, though), and that Coq parameters are equivalent to lean constants.

My definition above works for Coq variables and parameters, as well as Lean variables, but not parameters.

**Comment by dselsam** [comment]
This is a bug, I'll look into it.
