### ISSUE TITLE
Simplification lemmas are not generated for definitions over types defined with "parameter"

### ISSUE THREAD

**Issue by jldodds** [leanprover/lean3#1577]
The following fails to simplify in the proof of sm, but it succeeds if T is a defined type (even if it's defined as sorry):

```lean
section

-- The proof of sm fails with the parameter and succeeds with the def
parameter T : Type
--def T : Type := nat

def eqT : T -> T ->  Prop
| t1 t2 := t1 = t2 

lemma sm : forall t1 t2,
eqT t1 t2 ->
t1 = t2 :=
begin
intros,
simp [eqT] at a,
assumption
end

end
```

**Comment by dselsam** [comment]
`simp` only tries to add the equation lemmas for a definition when a constant is provided. Because you are using a parameter, `simp` is seeing the elaborated application `eqT T`, which is not a constant, and which is not itself a valid simplification lemma. 

You have two options.
1. Use `variable` instead of `parameter`. The only change you need to make is that `eqT t1 t2` becomes `eqT T t1 t2`.
2. Pass `_root_.eqT` to the simplifier instead of `eqT`. This prevents the elaborator from applying `eqT` to the parameter T.

**Comment by jldodds** [comment]
Thank you for the solution. I would suggest that 2 should happen transparently

**Comment by Kha** [comment]
Fixed by https://github.com/leanprover/lean/commit/27c1d2f4fbcee4e4ebbd854e45889bdeb92d446e
