### ISSUE TITLE
Simp performance on large terms

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean3#1589]
I've built up a small test to validate the performance of different operations on terms that contain a lot of shared subterms (i.e., they are small when traversed as a dag, but large when traversed as a tree).

I've found that simp appears to do a dag-based traversal, but scales worse than linear or near-linear (maybe quadratic?).

Here's the script:

```
-- This is a test case to validate the rewriter exploits the
-- dag structure of terms.
--
-- It allows one to build up terms that are binary trees with branches
-- and leaves.  The size of the term as a dag is proporportional
-- to the height of the tree, but contains an expoential number
-- of nodes when viewed as a tree.

def leaf : ℕ := 0

def branch (x y : ℕ) : ℕ := leaf

-- Simplification rule that only works on branch.
theorem branch_leaf_leaf : branch leaf leaf = leaf := begin simp [branch, leaf], end

-- Call a unary operation a given number of times.
meta def repeatn {α : Type} (f : α → tactic α) : α → ℕ  → tactic α
| x 0 := pure x
| x (nat.succ n) := f x >>= λy, repeatn y n

-- Build a branch that contains the same expression as leaves.
meta def branch_same (e : expr) : tactic expr := do
  pure `(branch %%e %%e)

open tactic

example : true := by do
  let n : ℕ := 1024,
  trace "iterations:",
  trace n,
  e ← repeatn branch_same `(leaf) n,
--  trace e,
  s ← simp_lemmas.mk.append
     [ (expr.const `branch_leaf_leaf [])
     ],
  (s', pr) ← simplify s e,
  trace "result:",
  trace s',
  tactic.triv
```

Here's a log of runtimes on a machine with 16GB ram:

```
lean% time lean dag.lean
iterations:
512
result:
leaf
lean dag.lean  5.25s user 0.09s system 100% cpu 5.334 total

lean% time lean dag.lean
iterations:
1024
result:
leaf
lean dag.lean  47.39s user 0.28s system 99% cpu 47.947 total

lean% time lean dag.lean
iterations:
1536
result:
leaf
lean dag.lean  152.31s user 0.24s system 99% cpu 2:32.71 total
```

I'm not sure what the expected performance is of simp, but for some of my envisioned use cases, it would be great if the runtime was linear or near-linear with respect to the term size (for a fixed set of rules). It's ok if some rules can push simp into exponential behavior.

**Comment by jroesch** [comment]
@joehendrix Leo and I spent some time talking about this today, it appears that the simplifier performs a linear number of operations, but it requires further investigation to understand where the performance hit is. We will try to spend some time this week chasing it down, thanks for the thoughtful issue!

**Comment by leodemoura** [comment]
I have profiled this benchmark. I used `n = 512`.
94% of the runtime is spent comparing expressions
```lean
bool is_equal(expr const & a, expr const & b);
```
It seems we get a lot of hash code collisions in this benchmark. That is, `is_equal` is invoked with expressions that have the same hash code but are structurally different.
The Hashtable insertion procedures are invoked approx. 15K times, but `is_equal` is invoked more than 600K times due to hash collisions. The performance of `is_equal` is also affected by the hash collisions.
The following line is reached approx. 180 million times.
https://github.com/leanprover/lean/blob/master/src/kernel/expr_eq_fn.cpp#L71
I'm currently investigating why we have so many collisions.

**Comment by leodemoura** [comment]
I recall that I experienced a similar (hash collision) problem in the past, and I addressed it by incorporating the term weight into the hash code computation. Unfortunately, the weight is ineffective for this benchmark since many sub terms have weight UMAX_INT because of the sharing. So, I decided to store the depth of composite terms and use it in the hash code computation. The new numbers are much better.

Here are the runtimes (using option `-j 0` no multi threading):
- empty file : 0.500 secs (loading `init` library)
- `n = 100` : 0.570 secs     (before 0.612 secs)
- `n = 500` : 0.600 secs     (before 4.3 secs)
- `n = 1000` : 0.604 secs   (before 31.728 secs)
- `n = 1500` : 0.612 secs
- `n = 2000` : 0.640 secs
- `n = 4000` : 0.664 secs
- `n = 8000` : 0.684 secs
- `n = 16000` : 0.816 secs
- `n = 32000` : 1.016 secs 

Remark: I had to increase stack space for `n >= 4000`

@gebner @kha It is not clear to me why we had so many hash collisions. Any ideas?
BTW, I tried different `hash(unsigned, unsigned)` combine functions, and they did not fix the problem.
I'm concerned we may have some bad hash function somewhere in the code, and using the `depth` is just masking the real problem.

**Comment by joehendrix** [comment]
Thanks for fixing this.
