### ISSUE TITLE
Quoting Prop values

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean3#1590]
The new quoting facility seems to report errors when quoting propositions.  

Consider the example below:

```
def foo : ℕ := 0

theorem bar : 0 = 0 := by trivial

set_option trace.app_builder true

example : true := by do
  let e : expr := `(foo) in do
  let f : expr := `(bar) in do
  tactic.triv
```

This results in the following error message:

```
[app_builder] failed to create an 'reflected'-application, failed to solve unification constraint for #1 argument (?x_0 =?= 0 = 0)                                                                                                   
../quote.lean:9:18: error: app_builder_exception, more information can be obtained using command `set_option trace.app_builder true`
```

Could it be that the metavariable `?x_0` has type `Type *` rather than `Sort *`?

**Comment by Kha** [comment]
Ah, that would certainly explain the error - I still haven't adjusted myself to the `Sort` change.

I'm beginning to think that \`(e) should return to always being of type `expr` instead of `reflected e` - you really only need the latter when writing `reflected` instances, and you can still use the `reflect` function for that.
Thoughts?

**Comment by jroesch** [comment]
@kha so we could just write `reflect (foo b c)`  when constructing the instances?

**Comment by Kha** [comment]
Yes, right now \`(e) and `reflect e` are exactly the same (except for antiquotations, but then the former switches back to `expr` anyway).

**Comment by joehendrix** [comment]
I haven't had a direct need for `reflected x` as opposed to `expr` in meta programming.  It seems like if using antiquotations make it return `expr`, it should always return `expr`.

**Comment by Kha** [comment]
I've only fixed the universe problem for now. When trying to restrict \`() back to `expr`, I realized that this wouldn't be trivial to implement without also losing the ability to use `reflected`-backed locals in the quotation (which we do make use of since the initial PR). I would have to duplicate some code from `type_context` in the elaborator, for (to me, currently) dubious benefits.

Quotations having a "dynamic" return type would be even more important if we ever implemented a `typed_expr` type as outlined in https://github.com/leanprover/lean/pull/1576. I haven't found a convincing use for that type yet personally, but I think @javra was interested in it.
