### ISSUE TITLE
Why does Σ not permit proofs in the second component?

### ISSUE THREAD

**Issue by JasonGross** [leanprover/lean3#1635]
If I try to copy/paste https://github.com/leanprover/lean/blob/7db2b8d01403c61f6311fe959ca0adc0881c3b58/library/init/data/sigma/basic.lean#L13-L14 to a new file, I get errors:
```lean
universe variables u v
lemma ex_of_sig {α : Type u} {p : α → Prop} : (Σ x, p x) → ∃ x, p x
| ⟨x, hx⟩ := ⟨x, hx⟩
```
gives
```
-*- mode: compilation; default-directory: "~/Documents/repos/lean-playgorund/" -*-
Compilation started at Fri Jun  2 00:36:46

/home/jgross/Documents/repos/lean/bin/lean  /home/jgross/Documents/repos/lean-playgorund/test2.lean
/home/jgross/Documents/repos/lean-playgorund/test2.lean:2:47: error: type mismatch at application
  Σ (x : α), p x
term
  λ (x : α), p x
has type
  α → Prop
but is expected to have type
  α → Type ?
/home/jgross/Documents/repos/lean-playgorund/test2.lean:2:47: error: type mismatch at application
  Σ (x : α), p x
term
  λ (x : α), p x
has type
  α → Prop
but is expected to have type
  α → Type ?
/home/jgross/Documents/repos/lean-playgorund/test2.lean:3:2: error: invalid constructor ⟨...⟩, expected type is not an inductive type
  ⁇
/home/jgross/Documents/repos/lean-playgorund/test2.lean:2:6: error: equation compiler failed (use 'set_option trace.eqn_compiler.elim_match true' for additional details)

Compilation exited abnormally with code 1 at Fri Jun  2 00:36:47
```

**Comment by JasonGross** [comment]
Oh, I see that in master, there's `psigma` and `sigma`.  Why isn't `psigma` the default?

**Comment by leodemoura** [comment]
Remarks:
1- `Prop` is notation for `Sort 0`
2- `Type u` is notation for `Sort (u+1)`.
3- The inductive datatype module in the kernel only accepts an inductive datatype declaration if it is a proposition or it is not a proposition for any universe parameter assignment.
4- `sigma.{u v} : Π {α : Type u}, (α → Type v) → Type (max u v)`
5- `psigma.{u v}: Π {α : Sort u}, (α → Sort v) → Sort (max 1 u v)`
The `1` makes sure that `psigma A B` is not a proposition even if `A` and `B` are propositions, and satisfy (3).

During elaboration,`sigma` generates universes constraints that are easier to solve than the ones generated by `psigma`. For example, with `psigma`, we often get constraints such as `max ?u 1 =?= 1`, where `?u` is a universe meta variable. This constraint has two possible solutions `?u := 0` or `?u := 1`. In Lean 2, we used a backtracking solver in the elaborator. We abandoned this approach because the error messages were hard to understand. 

Here is the notation for `psigma`.
```lean
universe variables u v

lemma ex_of_sig {α : Type u} {p : α → Prop} : (Σ' x, p x) → ∃ x, p x
| ⟨x, hx⟩ := ⟨x, hx⟩
```

**Comment by JasonGross** [comment]
> During elaboration,sigma generates universes constraints that are easier to solve than the ones generated by psigma. For example, with psigma, we often get constraints such as max ?u 1 =?= 1, where ?u is a universe meta variable.

Ah, that makes sense; thanks!

**Comment by digama0** [comment]
Also, the type you want to be using here is 'subtype', notation {x // p x},
which is intended for a Type first argument and a Prop second argument.
