### ISSUE TITLE
Implicitly inaccessible terms

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1730]
Based on [this Stack Overflow question](https://stackoverflow.com/questions/44930049/how-to-propogate-an-assumption-when-pattern-matching-in-lean/44930854), I learned that Idris [can implicitly mark pattern terms as inaccessible](https://github.com/idris-lang/Idris-dev/commit/0d8a153cb09d3c6d282dba2343a989f2d425526d). While marking function applications as inaccessible may be confusing in combination with our `[pattern]` attribute, doing so for duplicate pattern variables could avoid many users' initial confusion about inaccessible terms. On the other hand, if a user assumes that we support true non-linear patterns (i.e. based on (decidable) propositional instead of definitional equality), the resulting error message may be slightly more obscure.
```lean
example : ℕ → ℕ → ℕ
| n n := 1
  --^ invalid use of inaccessible term, it is not fixed by other arguments
| _ _ := 2
```

What do you think?

**Comment by avigad** [comment]
@andreasabel has pointed out to me that Agda's elaborator is more flexible in this regard. They used to require users to mark which positions are inaccessible, but now they infer / guess that information automatically. They do not compile down to primitive recursors, but at least aspire to the ideal that it should be possible in principle. He and others have pointed me to Jesper Cockx's very nice dissertation, which describes particular algorithms: https://lirias.kuleuven.be/bitstream/123456789/583556/1/thesis-final-digital.pdf. @Kha, when you are here in Cambridge, it might be helpful to talk to some of the Agda people about these issues.

I personally like the idea of explicitly indicating which positions are pattern variables and which are inaccessibles. To me, it clarifies what is going on. But the equation compiler is sometimes finicky as to where to put the annotations. Last week, a student here asked me about how to write an append function for dependent vectors, and I had to struggle to explain why the first definition below works but not the second one.
```lean
universe u
variable {α : Type u}

inductive vec (α : Type u) : ℕ → Type u
| nil {}                           : vec 0
| cons {n : ℕ} (a : α) (v : vec n) : vec (n + 1)

open vec

def append_aux : Π {n m : ℕ}, vec α n → vec α m → vec α (m + n)
| ._ m nil                w := w
| ._ m (@cons .(α) n b v) w := cons b (append_aux v w)

-- doesn't work
def append_aux' : Π {n m : ℕ}, vec α n → vec α m → vec α (m + n)
| .(0) m nil        w := w
| n    m (cons b v) w := cons b (append_aux' v w)

def append {n m : ℕ} (v : vec α n) (w : vec α m) : vec α (n + m) :=
eq.rec_on (add_comm m n) (append_aux v w)
```
(BTW, as far as I can tell, there is no way to get `n + m` in the conclusion rather than `m + n` without using a cast. Another solution I pointed out was defining `vec` with `snoc` instead of `cons`, which lines up better with the fact that addition is defined by recursion on the right.)

(Sorry, I got the n's and m's confused the first time.)

**Comment by Kha** [comment]
> I personally like the idea of explicitly indicating which positions are pattern variables and which are inaccessibles.

I agree with you for compound inaccessibles. But when you have `x`s in your pattern, you can arbitrarily choose one not to be marked inaccessible (I think?), so there is not much semantic information in the choice.

> @Kha, when you are here in Cambridge, it might be helpful to talk to some of the Agda people about these issues.

Sounds good, I'm looking forward to it.

**Comment by andreasabel** [comment]
The current expert for Agda in this case is @jespercockx.

**Comment by leodemoura** [comment]
> Based on this Stack Overflow question, I learned that Idris can implicitly mark pattern terms as inaccessible. While marking function applications as inaccessible may be confusing in combination with our [pattern] attribute, doing so for duplicate pattern variables could avoid many users' initial confusion about inaccessible terms. On the other hand, if a user assumes that we support true non-linear patterns (i.e. based on (decidable) propositional instead of definitional equality), the resulting error message may be slightly more obscure.

@kha We used this approach in Lean 0.2. It generated confusion.

Note that the placement of inaccessible terms will affect how the function is compiled into recursors. 

```lean
open nat

inductive vec (α : Type) : nat → Type
| nil  {} : vec 0
| cons    : ∀ {n}, α → vec n → vec (succ n)

def map1 {α β} (f : α → β) : ∀ {n}, vec α n → vec β n 
| 0     vec.nil                   := vec.nil
| (n+1) (@vec.cons .(α) .(n) h t) := vec.cons (f h) (map1 t)

def map2 {α β} (f : α → β) : ∀ {n}, vec α n → vec β n 
| .(0)   vec.nil                := vec.nil
| .(n+1) (@vec.cons .(α) n h t) := vec.cons (f h) (map2 t)

#print map1._main 
#print map2._main
```

**Comment by leodemoura** [comment]
> He and others have pointed me to Jesper Cockx's very nice dissertation, which describes particular algorithms: https://lirias.kuleuven.be/bitstream/123456789/583556/1/thesis-final-digital.pdf. 

@avigad  I read Jesper's paper not his thesis. The paper is relevant for the HoTT mode that we don't support anymore. The approach we use is based on Connor McBride's paper, and uses proof irrelevance (and consequently is not good for HoTT).

**Comment by leodemoura** [comment]
@avigad The correct way to write `append_aux'` is

```lean
-- doesn't work
def append_aux' : Π {n m : ℕ}, vec α n → vec α m → vec α (m + n)
| .(0)   m nil                w := w
| .(n+1) m (@cons .(α) n b v) w := cons b (append_aux' v w)
```

**Comment by Kha** [comment]
@leodemoura 
> Note that the placement of inaccessible terms will affect how the function is compiled into recursors.

I see. Now that we have match equations, is this mostly a performance (term size) concern?

**Comment by leodemoura** [comment]
> I see. Now that we have match equations, is this mostly a performance (term size) concern?

Performance is one issue, but this was not a problem in Lean 0.2 since we did not have a code generator in 0.2. I recall two problems:
- Wildcard behavior (this is less problematic in Lean 3.x but it is still a problem).
- Unifier (when we unfold definitions and there are meta-variables).

**Comment by Kha** [comment]
Okay, thanks for the explanation. Since this approach has been tried before, I'm closing this RFC.

**Comment by andreasabel** [comment]
The problem is that both definitions below are rejected by `lean`.
```lean
inductive Fin : nat → Type
| fzero : Π {n}, Fin (nat.succ n)
open Fin

def fmin : Π (n : nat) (x y : Fin n),  Fin n
| ._ fzero fzero := fzero

def fmin' : Π (n : nat) (x y : Fin n),  Fin n
| n fzero fzero := fzero
```
Thus, no matter whether I treat the `n` as dot pattern or not, `lean` has a problem.
The only way to fix this is to give all arguments to `fzero` explicitly.

Agda accepts both of these definitions and they lead to different case trees.

Idris does not require dot patterns at all, but this goes way beyond Agda.  
Agda only allows omitted arguments or `_` to stand both for dot patterns and variable patterns.

Lean accepts those definitions:
```lean
def fmin1 : Π (n : nat) (x y : Fin n),  Fin n
| ._ (@fzero ._) (@fzero _) := fzero

def fmin2 : Π (n : nat) (x y : Fin n),  Fin n
| ._ (@fzero _) (@fzero ._) := fzero
```
Printing as suggested above
```
#print fmin1.main;
#print fmin2.main;
```
yields
```
_ `;`:1 _:1 := andthen #1 #0
_ `;`:1 _:1 := andthen #1 #0
```
which looks the same to me.

How are `fmin1` and `fmin2` distinguished?  
Wouldn't it make sense to accept `fmin` and treat it either as `fmin1` or `fmin2`?

**Comment by leodemoura** [comment]
@andreasabel 
```lean
#print fmin1.main;
#print fmin2.main;
```
**EDIT**: Lean is actually printing information for `;`. There is a missing `_` at `fmin1.main` and `fmin2.main`. We should report an error. I will take a look later.

To get the actual definition, we should use
```lean
#print fmin1._main
#print fmin2._main
```
They are indeed identical. However, the following one is not
```lean
def fmin3 : Π (n : nat) (x y : Fin n),  Fin n
| (n+1) (@fzero ._) (@fzero ._) := @fzero n

#print fmin3._main
```

> Wouldn't it make sense to accept fmin and treat it either as fmin1 or fmin2?

Yes, for simple definitions such as `fmin1` and `fmin2`, I don't see major issues.
We tried this approach in Lean 0.2, it created confusion in complex dependent pattern matching problems. We had the following problems:
- Wildcards in patterns. This is still a problem in Lean 3, but at least we have strict validations rules to minimize the problem. 
- Inconsistent use of inaccessible annotations. It is still hard to diagnose some of the problems in complex dependent pattern matching problems, but with the current strict rules it is a little bit saner.
- Unification. The unifier may unfold definitions and expose the recursors during unification. Users were surprised that using inaccessible annotations would affect the unifier.

**Comment by andreasabel** [comment]
> They are indeed identical. However, the following one is not
```lean
  def fmin3 : Π (n : nat) (x y : Fin n),  Fin n
  | (n+1) (@fzero ._) (@fzero ._) := @fzero n
```
Yes, of course, this matches first on `n` while the other definitions only match on `x` and `y`.  Agda has the same distinction as `lean` here.

**Comment by gebner** [comment]
> We should report an error.

@leodemoura  Fixed in d610709a5358de741f5094ccdfed6241434252e2.

**Comment by jespercockx** [comment]
> Agda accepts both of these definitions and they lead to different case trees.
> 
> Idris does not require dot patterns at all, but this goes way beyond Agda.
> Agda only allows omitted arguments or _ to stand both for dot patterns and variable patterns.

That's actually no longer true for the current version of Agda: since @ulfnorell added the new parameter refinement, you can now write a variable in place of an inaccessible pattern in Agda. If you use this variable in the right-hand side, then it evaluates to the value of the inaccessible pattern inferred by Agda. So you can now write in Agda:
```
append : {A : Set} (m n : Nat) -> Vec A m -> Vec A n -> Vec A (m + n)
append m n nil ys = ys
append m n (cons m' x xs) ys = cons x (append m' n xs ys)
```
On the right-hand side of the second clause, `m` has value `suc m'`. I think this is quite similar to what is done in Idris (but I'm not 100% sure).

To be honest, I think this approach gives the best of both worlds: you don't ever have to use an inaccessible pattern, unless you want to prevent the typechecker from splitting on a particular argument. But I can also see the value of requiring inaccessible patterns to be always written in the same consistent style.

**Comment by andreasabel** [comment]
Indeed, now ordinary variables can also stand for dot patterns.
