### ISSUE TITLE
Lean emacs mode hijacks compile command

### ISSUE THREAD

**Issue by andreasabel** [leanprover/lean3#1737]
If I have an emacs session with a lean buffer, then the `compile` command is compiling my lean file, regardless from where it is invoked.

For instance, in my LaTeX buffer I want to call my local `Makefile` with `M-x compile`.  Instead, `M-x compile` will run lean on my last lean file.

If I want it back I have to `M-x set-variable RET compile-command RET "make -k"`.

I think the lean emacs mode should set the compile command only locally, such that it is invoked when issuing `M-x compile` from a lean buffer.

**Comment by Kha** [comment]
We implement `lean-execute` via `compile`, which apparently stores the last command non-locally. To be honest, I didn't expect that anyone was still using Lean batch compilation from inside Emacs. If `lean-execute` is part of your regular workflow, I can work around the problem by restoring `compile-command` after the function call.

**Comment by leodemoura** [comment]
@kha I have a similar problem. For me, `M-x compile` remembers all previous commands I have executed. So, it is not a big deal, I can use `up-arrow` to get the older versions. However, there is one minor annoyance. My .emacs file sets an initial compilation command (for building Lean). If I compile a Lean file before I compile Lean, then the command is lost. This is a minor problem for me, since most of the time I compile Lean before I compile a .lean file using Lean.

**Comment by Kha** [comment]
Okay, I pushed a commit that resets `compile-command` after compilation.

**Comment by Kha** [comment]
(aaa5908)

**Comment by leodemoura** [comment]
@Kha Should we close this issue?

**Comment by Kha** [comment]
Since nobody is complaining any more, I'm assuming the commit indeed solved the problem :) .
