### ISSUE TITLE
is src/kernel/expr.h the right reference for the lean AST?

### ISSUE THREAD

**Issue by cartazio** [leanprover/lean3#1762]
partly because im poking at code extraction facilities in a few provers, is that the rep that would perhaps be used if one were to do a code extraction facility for lean?

https://github.com/leanprover/lean/blob/master/src/kernel/expr.h

thanks 
-Carter

**Comment by gebner** [comment]
We already do (some) code extraction in Lean for evaluation in the VM, see [the compiler](https://github.com/leanprover/lean/tree/master/src/library/compiler) and [VM code](https://github.com/leanprover/lean/blob/master/src/library/vm/vm.h).  This VM implements a straightforward stack machine; types, propositions, and proofs are erased during compilation.  You can inspect the internal bytecode representation by using `set_option trace.compiler.optimize_bytecode true` above the definition that you want to see.

If you want to experiment with your own code extraction techniques, you could start from expressions in the kernel type theory.  You can access them via the `environment` object from inside Lean, see [our recent paper on metaprogramming](http://leanprover.github.io/papers/tactic.pdf).  The [inductive definition for the kernel expression type is here](https://github.com/leanprover/lean/blob/667e1e138162ef6d65a2041abfe760a7aa79c2c5/library/init/meta/expr.lean#L38-L48).

@jroesch is working on a [native compiler for Lean using this metaprogramming facilities](https://github.com/jroesch/lean/tree/direct-calls/library/tools/native).

I'll close this issue since it is not a bug report, but feel free to ask if have any questions.  You can also [use our gitter channel](https://gitter.im/leanprover_public/Lobby).

**Comment by emberian** [comment]
(and the answer is yes, but see also the lean definition of exprs too for an easier high level view: https://github.com/leanprover/lean/blob/master/library/init/meta/expr.lean#L38)
