### ISSUE TITLE
Type inference unstable under let substitution/unfolding

### ISSUE THREAD

**Issue by bmsherman** [leanprover/lean3#1783]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Consider the following code:
```lean
def map (K V : Type) : Type := K → option V

namespace map
section
parameters {K V : Type} [decidable_eq K]

def empty : map K V := fun _, none

def insert (k : K) (v : V) (m : map K V) : map K V :=
  λ k' : K, if H : k = k'
       then some (eq.rec_on H v)
       else m k'

structure member (m : map K V) :=
  (value : V)

parameter {B : V → Type}

def lookup_empty : ∀ x : (empty : map K V).member, B (x.value) := sorry

def lookup_insert {m : map K V}
  (k : K) (v : V) (b : B v) (f : ∀ x : m.member, B x.value)
  (x : (insert k v m).member) : B x.value
:= sorry
end
end map

def my_map : map nat bool :=
     map.insert 3 tt $
     map.insert 6 ff $
     map.empty

def my_lookup : ∀ z : my_map.member, nat :=
  let B := ((λ x : bool, nat) : bool → Type) in
  @map.lookup_insert _ _ _ B _ (3 : nat) tt (4 : nat) $
    map.lookup_insert (6 : nat) ff (7 : nat) $
    map.lookup_empty

def my_lookup' : ∀ z : my_map.member, nat :=
  @map.lookup_insert _ _ _ ((λ x : bool, nat) : bool → Type) _ (3 : nat) tt (4 : nat) $
    map.lookup_insert (6 : nat) ff (7 : nat) $
    map.lookup_empty
```

The definitions of `my_lookup` and `my_lookup'` differ only in that `my_lookup'` removes the `let` statement from `my_lookup `, substituting in its values.

**Actual behavior:** 
While the definition of `my_lookup ` typechecks successfully, `my_lookup'` fails with the error:
```
bug.lean:41:45: error
type mismatch at application
  map.lookup_insert 6 ff 7 map.lookup_empty
term
  map.lookup_empty
has type
  Π (x : map.member map.empty), ?m_4 (x.value)
but is expected to have type
  map.member ?m_1 → ℕ
```

**Expected behavior:** I'd expect no difference in type checking/inference behavior when consider terms which differ only by let-substitution. For instance, I'd expect type checking/inference behavior for `my_lookup ` and `my_lookup'` to be the same.

### Versions

Lean HEAD from July 21, 2017, Lean (version 3.2.1, commit 667e1e1, Release)

**Comment by digama0** [comment]
This is not going to change, I think. There are a few parts of this example which are bad for elaboration. First, the `B` parameter must be inferred using higher-order unification, which caused lots of problems in lean 2. To resolve this there are two strategies used. In the default strategy, functions are not unfolded and function metavariables cause unification failure, which is what happened here. The version with the `let` worked because it produces an application instead of a reduced beta redex (since it is only unfolded as necessary). 

Alternatively, you could define `lookup_empty` and `lookup_insert` as `@[elab_as_eliminator]`. With this elaboration strategy, higher order metavariables are unified by replacing all instances of the argument in the type. With this annotation, both proofs break, because this mode cannot handle metavariables in the arguments (in this case, in the implicit argument to `lookup_empty`).

The real answer is that these definitions are written in a very bad style if you want lean's elaborator to help you at all. You need to make sure that it doesn't need to solve higher-order constraints to solve your problem. Think about it: you write `map.lookup_empty : nat` and it has to solve the problem of determining `K,V,B,x` such that `?x : (map ?K ?V).member` and `?B ?x.value =?= nat`. This is a wildly underdetermined system of equations. Note that your having given `B` in the enclosing function doesn't help since there is no argument that links these `B` parameters to be the same in nested calls.

Finally, there is no guarantee that type inference is unchanged under zeta reduction. Indeed, it is better to think of the elaborator as inferring things in the order they are given in the text, so that moving something to a let can help to make it elaborate earlier than it otherwise would, which is useful for giving hints in complicated elaboration problems like this one.

Others can reopen this issue if I am in error, but I think it is a safe bet that this issue falls in "won't fix" territory.

**Comment by bmsherman** [comment]
Thanks for your explanation of how elaboration works and why this surprising behavior occurs! I understand now why one should not expect that elaboration is stable under zeta reduction.
