### ISSUE TITLE
Modify after free

### ISSUE THREAD

**Issue by jldodds** [leanprover/lean3#1787]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Although I can't easily reproduce, I figure this is best to mention. I'm happy to take further steps to debug as necessary if recommended in response.

When running lean on our (private) development, we occasionally see lean crash with the following message or something similar.

```
lean(2637,0x70000bd24000) malloc: *** error for object 0x7fa1f8255610: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

### Steps to Reproduce
Work on our development for an unpredictable amount of time

### Versions

Lean (version 3.2.1, commit 667e1e138162, Release)

**Comment by bmsherman** [comment]
I'll add some additional detail:

- We are using the Lean plugin in VSCode
- The error usually occurs just after typing a character, and the code is in a state where it does not parse or typecheck (which is usually the case after a character is typed)
- I have gotten it to a point where the crash consistently occurred: I'd type a character, it would crash, I'd delete the character that I just typed, restart Lean, and it would crash when I typed the same character again. However, I tried deleting the entire code in the file, and re-pasting it, and the error stopped occurring. Perhaps deleting the entire code in the file cleared some broken cache.

**Comment by bmsherman** [comment]
OK, I managed to find a concrete example today where I consistently am able to get Lean to error, and spent a lot of time to get it to this minimal example.

```lean
import data.bitvec

def word16 := bitvec 16

inductive poll_dlabel : Type
| timeout {} : poll_dlabel
| receive {} : ∀ (rn : word16), poll_dlabel

#check option_bind

def next_agent_state_poll_dlabel : poll_dlabel → bool
| poll_dlabel.timeout := tt

#check option_map
```

I can "tell" there is something wrong with this file, even before it crashes, because I get a green underline under the `#check option_bind` line (and the corresponding Lean output), but no corresponding underline or output for the last line, `#check option_map`. Even though the `next_agent_state_poll_dlabel` is not a complete pattern match, there is no red underline or error message from Lean indicating this error.

If I change the definition of `word16` to be `bool` rather than `bitvec 16`, then I am told that there is a non-exhaustive pattern match, and there is Lean output/green for the `#check option_map` at the end.

It can take some work to cajole Lean into crashing. I am using VSCode. My strategy has been to edit parts of the file haphazardly until it crashes. Some of these modifications that seem to do well include:

- changing the definition of `word16` back and forth between `bool` and `bitvec 16`
- removing the `word16` argument to the `receive` constructor and putting it back
- changing `tt` to `ff` in the definition of `next_agent_state_poll_dlabel`

But other changes seem to work as well, and none of these work consistently, so I don't know if there's anything special about these modifications. After making edits back and forth, for some variable amount of edits or number of time, but often around a handful, or maybe up to 20 sometimes, I get Lean to crash. The error message is often something like this:
```
lean(29805,0x70000e78e000) malloc: *** error for object 0x7ff981aa2410: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```
(but the memory addresses vary).

I am running a Lean version from July 19. Here's the Lean version output:
```
Lean (version 3.2.1, commit 667e1e138162, Release)
```
I am running Mac OS 10.12.6.

**Comment by bmsherman** [comment]
Inlining the definition of `bitvec` and changing the parameter to 0, simplifies it a bit, and the error persists:
```lean
inductive foo : Type
| timeout : foo
| receive : { l : list bool // l.length = 0 } → foo

#check option_bind

def my_def : foo → bool
| foo.timeout := tt

#check option_map
```

**Comment by Kha** [comment]
Do you mean that your last code snippet consistently crashes for you? It does not do so for me on the latest master build.

**Comment by bmsherman** [comment]
You need to do work to make it crash, but you should be able to confirm the *absence* of an error for you if Lean gives you an error at `my_def` for a non-exhaustive pattern match and also displays the output of the `#check` directive that comes after that, `#check option_map`. For me with that last code snippet, I do not get either of these things, and with enough editing of the file, I can eventually get it to crash. But I encourage checking for the presence of expected error messages/output to see if you have the same issue that I am running into. Thanks.

**Comment by Kha** [comment]
No, the output is as expected for me and I can't seem to force a crash through editing either. Could you update Lean and check if the problem persists?

**Comment by jldodds** [comment]
Updating Lean has given me the expected output in the example file. @bmsherman or I will comment in a few days if the crash also appears to be gone in our development.

**Comment by leodemoura** [comment]
I'm closing this issue. We can reopen if the problem appears again after the update.

**Comment by jldodds** [comment]
Thanks, it appears to be gone
