### ISSUE TITLE
"cases" and "induction" tactics behave incoherently and produce unwieldy terms

### ISSUE THREAD

**Issue by mrhaandi** [leanprover/lean3#1794]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

"cases" and "induction" tactics behave incoherently and produce unwieldy terms

### Steps to Reproduce

Consider the following lean code:

```lean
inductive test : nat -> list nat -> Prop
| zero: test 0 list.nil
--n remains even
| nil: forall {n: nat}, test n list.nil -> test (n+2) list.nil
--n flips between even and odd
| cons: forall {n i: nat} {is: list nat}, test n is -> test (n+3) (list.cons i is)

--cases tactic fails
lemma example1 : forall (n m: nat), test (n+n) [m] -> false :=
begin
intros n m h,
cases h; try {intros, contradiction}, --cases tactic failed, unsupported equality between type and constructor indices
end

--induction tactic produces infeasible result
lemma example2 : forall (n m: nat), test (n+n) [m] -> false :=
begin
intros n m h,
induction h; try {intros, contradiction},  --infeasible
end

--cases tactic produces unwieldy terms
lemma example3 : forall (n m: nat), test (n+n) [m] -> false :=
begin
intros n m,
generalize def_n' : n + n = n',
generalize def_is : [m] = is,
intro h,
revert def_n' def_is,
cases h; try {intros, contradiction}, --creates unwieldy terms
admit, --not clear on how to continue
end

--induction tactic behaves fine
lemma example4 : forall (n m: nat), test (n+n) [m] -> false :=
begin
intros n m,
generalize def_n' : n + n = n',
generalize def_is : [m] = is,
intro h,
revert def_n' def_is,
induction h; try {intros, contradiction}, --creates easy to use terms
admit, --continue by showing that n_1 is both even and odd
end
```

**Expected behavior:** 
lemma example3 at "cases h": same terms as in lemma example4 at "induction h" (just without the induction hypotheses).

lemma example2 at "induction h" may produce an error message similar to lemma example1 at "cases h", or alternatively introduce additional equations on indices.

**Actual behavior:**
(see comments in code at particular lines)
"cases h" unlike "induction h" introduces large incomprehensible terms.
"induction h" does not fail like "cases h", but creates an infeasible state (|- false).

### Versions

Lean (version 3.2.1, commit 631513627911, Release)
OS: Windows 10, 64bit

**Comment by digama0** [comment]
`example2` is behaving as intended. `example3` is a problem. The basic issue is that `cases` applies `whnf` to the terms in the generated equalities on the indices to see if there are constructor applications it can take advantage of, but in the case of a variable and a constructor application it keeps the whnf form rather than the input form in the result, causing the blowup seen here (which is the attempt to solve the unification `n + 3 =?= nat.succ ?M` as `?M := <whnf form of nat.add> n 2`).

I would like to see `example1` not fail but just return the state with the equality hypothesis - there is a chance the user can do something useful with it, and `cases` is a basic enough tactic that I think people expect it to never fail as long as the input is an inductive datatype (although it might not be useful).

By the way, your proof sketch for how to finish `example4` won't work, since you get the assumption `n + n = n_1 + 3`, which is not itself contradictory. You need another lemma, which can be proven by induction on `n`:

    lemma example5 : forall (n m : nat), test (n+n) [m] -> false :=
    begin
    intros n m,
    generalize def_n' : n + n = n',
    generalize def_is : [m] = is,
    intro h,
    induction h; injections,
    subst h,
    have : ∀ n k, n + n = k + 3 → test k [] → false := sorry,
    apply this; assumption
    end

**Comment by mrhaandi** [comment]
> By the way, your proof sketch for how to finish example4 won't work, since you get the assumption n + n = n_1 + 3, which is not itself contradictory.
The proof sketch was meant to abbreviate (using the variable names from last tactic state):
1) observe that is_1 = [], 
2) using "test n_1 is_1" show (by induction) that n_1 is even
3) using "n + n = n_1 + 3" show (by induction) that n_1 is odd 
4) contradiction (this appears to be the intention of your suggested lemma)

For examples 1 und 2, I hoped that if `n + 3 =?= nat.succ ?M` is not unifiable, then `whnf ` is reverted and additional equalities are introduced as premises (this is what I currently do manually in custom recursors). However, I'm not sure whether this generalizes well enough.

**Comment by digama0** [comment]
In fact, in this case there is no need for whnf at all. There is a generated equality `n' = n_1 + 3`, which is eliminated by `subst`. This works even if the right side is an arbitrary function like `f n_1`, but unfortunately in this case `n_1 + 3` is also a constructor (which matters for some other configurations) and it has to whnf the term to discover this; after that the term is a mess (`nat.succ (<whnf of nat.add> n 2)`) and that is what is actually used in `subst` so that the mess goes everywhere.

The additional equalities are already there as premises; all that is needed is to remove the part where `cases` throws an exception at "unsupported equality", and maybe give the generated equality a better name (it is currently an ugly unique name).
