### ISSUE TITLE
Custom recursor introduces misleading tactic state

### ISSUE THREAD

**Issue by mrhaandi** [leanprover/lean3#1798]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
Custom recursors are sensitive to position of `{p: Prop}` and may introduce a misleading tactic state.

### Steps to Reproduce
Consider the following lean code that contains two  (essentially same, `{p: Prop}` is at a different position) custom recursors:

```lean
inductive test : nat -> list nat -> Prop
| zero: test 0 list.nil
--n remains even
| nil: forall {n: nat}, test n list.nil -> test (n+2) list.nil
--n flips between even and odd
| cons: forall {n i: nat} {is: list nat}, test n is -> test (n+3) (list.cons i is)

attribute [recursor 4]
lemma recursor1 : ∀ {n': nat} {ns': list nat} {p: Prop},
    test n' ns' →
    (n' = 0 → ns' = list.nil → p) → 
    (∀ (n: nat), n' = n+2 → ns' = list.nil → test n list.nil → p) → 
    (∀ (n i: nat) (is: list nat), n' = n+3 → ns' = list.cons i is → test n is → p) → 
    p :=
    begin
    introv T IH1 IH2 IH3,
    induction T,
    case test.zero { apply IH1 rfl rfl },
    case test.nil n'' { apply IH2 n'' rfl rfl a },
    case test.cons n'' i'' is'' { apply IH3 n'' i'' is'' rfl rfl a }
    end

attribute [recursor 4]
lemma recursor2 : ∀ {p: Prop} {n': nat} {ns': list nat},
    test n' ns' →
    (n' = 0 → ns' = list.nil → p) → 
    (∀ (n: nat), n' = n+2 → ns' = list.nil → test n list.nil → p) → 
    (∀ (n i: nat) (is: list nat), n' = n+3 → ns' = list.cons i is → test n is → p) → 
    p :=
    begin
    introv T IH1 IH2 IH3,
    induction T,
    case test.zero { apply IH1 rfl rfl },
    case test.nil n'' { apply IH2 n'' rfl rfl a },
    case test.cons n'' i'' is'' { apply IH3 n'' i'' is'' rfl rfl a }
    end

lemma example1: ∀ (n m: nat), test (n+n) [m] → false :=
begin
intros n m h,
induction h using recursor1; try { contradiction }, 
--show that n_1 is necessarily both even and odd
admit
end

lemma example2: ∀ (n m: nat), test (n+n) [m] → false :=
begin
intros n m h,
induction h using recursor2; try { contradiction }, 
exact n + n,
exact [m],
contradiction,
contradiction,
--continue as in example1
admit
end

lemma example3 : false :=
begin
have h := test.zero,
induction h using recursor2,
--the following line should produce an error
exact 1,
exact [],
{ contradiction }, 
{ injection a, contradiction },
injection a with c, --remaining goal n : nat, c : 0 = n + 2 |- false
end
```

**Expected behavior:**
`recursor1` should behave the same as `recursor2`, therefore `lemma example1` should not differ from `lemma example2`. Additionally, `lemma example3` should recognize that custom recursor parameter `exact 1` is chosen inconsistently.

**Actual behavior:**
`recursor1` in `lemma example1` behaves as expected, but `recursor2` in `lemma example2` introduces unnecessary goals.

Moreover, the only reported error at the end of `lemma example3` is
```
[Lean]
tactic failed, there are unsolved goals
state:
n i : ℕ,
is : list ℕ,
a : 1 = n + 3,
a_1 : list.nil = i :: is,
a_2 : test n is,
c : 0 = n + 2
⊢ false
```
This is highly misleading, since "c" is a contradiction, therefore `false` is derivable. The **actual** error is reported after closing the last goal.

### Versions
Lean (version 3.2.1, commit 631513627911, Release)
OS: Windows 10, 64bit

**Comment by leodemoura** [comment]
The behavior above is the expected one. It is consistent with the one the `[recursor idx]` is processed.
A recursor may have parameters, a motive, a major premise, indices for the major premise, minor premises, and "extra hypotheses" (everything else). It infers this data using the following approach.
- The motive is detected using the resulting type. In the example above, the motive is `p : Prop`.
- Anything that occurs before the motive is assumed to be a parameter. All recursors automatically generated by Lean have this property. So, `recursor1` has 2 parameters and `recursor2` has 0.
- The number of indices is computed using the motive and whether the recursor supports dependent elimination or not. In this case, since the motive is just `p : Prop`, the number of indices is assumed to be 0.
- The major premise position is given by the user `test n' ns'`. The indices for the major premise are assumed to occur before the major premise. This is not relevant here since the number of indices is assumed to be 0 for both recursors.
- The minor premises are computed using the motive. In the examples above, the following parameters are treated as minor premises.
```lean
    (n' = 0 → ns' = list.nil → p) → 
    (∀ (n: nat), n' = n+2 → ns' = list.nil → test n list.nil → p) → 
    (∀ (n i: nat) (is: list nat), n' = n+3 → ns' = list.cons i is → test n is → p) 
```
- Everything else is considered to be "extra hypotheses" (that need to be discharged/provided by the user). They are similar to minor premises, but they do not produce the motive. This feature was explicitly requested by users. So, `{n': nat} {ns': list nat}` are assumed to be "extra hypotheses" for `recursor2`.  This is why we get the weird extra goals.

We can retrieve information on how Lean has interpreted a recursor by using the command:
```lean
#print [recursor] recursor1
#print [recursor] recursor2
```

The information above will be included in the reference manual in the future.

I'm also closing the issue since the behavior is the intended one. I understand it can be viewed as counter-intuitive, but I'm not interested in discussing how to change it.
