### ISSUE TITLE
Cases tactic doesn't use supplied names

### ISSUE THREAD

**Issue by bmsherman** [leanprover/lean3#1816]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Consider the following example:
```lean
namespace list
inductive Forall {A} (P : A → Prop) : list A -> Prop
| nil : Forall []
| cons : ∀ {x xs}, P x -> Forall xs -> Forall (x :: xs)
end list

lemma foo {A : Type} (x : A)
  : [x].Forall (λ e, false) → false
:= begin
intros H,
cases H with H1 H2,
-- introduces variables a, a_1
rename a H1, rename a_1 H2,
assumption
end
```

**Actual behavior:**
After destructing the `list.Forall` hypothesis with the tactic invocation `cases H with H1 H2`, hypotheses named `a` and `a_1` are introduced. Hence, in the example above, I rename `a` to what I would have expected, `H1`, and similarly `a_1` to `H2`.

**Expected behavior:**
I would expect that hypotheses named `H1` and `H2` would be introduced, rather than `a` and `a_1`.

### Versions

I am using a Lean Git version from September 5 on Mac OS 10.12.6.
Lean (version 3.2.1, commit f1ec117a2445, Release)

**Comment by leodemoura** [comment]
> I would expect that hypotheses named H1 and H2 would be introduced, rather than a and a_1.

Lean used the names for the implicit arguments `x` and `xs`. The `cons` case has 4 arguments.
Remark: the goals for `x` and `xs` were solved by solving typing constraints.
The following example will name the explicit arguments as `H1` and `H2`.
```lean
namespace list
inductive Forall {A} (P : A → Prop) : list A -> Prop
| nil : Forall []
| cons : ∀ {x xs}, P x -> Forall xs -> Forall (x :: xs)
end list

lemma foo {A : Type} (x : A)
  : [x].Forall (λ e, false) → false
:= begin
intros H,
cases H with _ _ H1 H2,
assumption
end
```

**Comment by leodemoura** [comment]
I'm closing this issue. I considered changing `cases` and only use the provided names for goals that have not been solved using typing constraints. However, I discarded this option since it would make `cases ... with ...` even harder to use for inductive types with many constructors. Right now, we have a simple explanation for the list of `with` ids. It is of the form `id_1_1 .. id_1_n1 id_2_1 ... id_2_n2 ... id_m_1 id_m_nm`. where `id_i_j` is the name for the `j`-argument of the `i`-constructor. The user doesn't have to think whether an argument can be inferred using typing inference or not. We are aware the `with` clause is inconvenient to use if there are too many constructors. In this case, we suggest users use the auxiliary `case` tactic. For example, we can write the example above as:
```lean
namespace list
inductive Forall {A} (P : A → Prop) : list A -> Prop
| nil : Forall []
| cons : ∀ {x xs}, P x -> Forall xs -> Forall (x :: xs)
end list

lemma foo {A : Type} (x : A)
  : [x].Forall (λ e, false) → false
:= begin
intros H,
cases H,
case list.Forall.cons H1 H2 { assumption }
end
```

**Comment by bmsherman** [comment]
Thanks for your helpful explanation! I had wrongly assumed that what I saw must have been a bug. And thank you for explaining several ways to accomplish what I wanted.
