### ISSUE TITLE
generalize tacitly fails

### ISSUE THREAD

**Issue by mrhaandi** [leanprover/lean3#1832]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
Invoking the `generalize` tactic does nothing although a suitable subterm is present.

### Steps to Reproduce
Consider the following lean code:
```lean
def l : list int := [0]
def index := {i : nat // i < l.length}

lemma example1a (i : index) : i.val < list.length l :=
    begin
        generalize def_n : list.length l = n,
        --doesn't generalize
        admit
    end

lemma example1b (i : index) : i.val < list.length l :=
    begin
        generalize def_m : i.val = m,
        generalize def_n : list.length l = n,
        --does generalize
        admit
    end

lemma example2a (i : index) : i.val < list.length l :=
    begin
        have : list.length l = 1 := rfl,
        rw [this],
        --doesn't rewrite
        admit
    end

lemma example2b (i : index) : i.val < list.length l :=
    begin
        have : list.length l = 1 := rfl,
        simp [this],
        --does simplify
        admit
    end
```

**Expected behavior:**
`example1a` : after generalize, the target should be `⊢ i.val < n`.

**Actual behavior:**
`example1a` : generalize does nothing (maybe a failed rw as in `example2b`).
The issue seems to be due to `i.val` containing a reference to `l`.

### Versions
Lean (version 3.3.1, commit d83b9ef3efbf, Release)
OS: Windows 7, 64bit

**Comment by digama0** [comment]
This is intended behavior. If we look at the state of the first example before the `generalize` with `set_option pp.implicit true`, we see

    ⊢ @subtype.val ℕ (λ (i : ℕ), i < @list.length ℤ l) i < @list.length ℤ l

and `generalize` and `rw` are both trying to replace both occurrences of `list.length l` with `n`, and only the second can be done without causing a type error. It is very difficult to determine which subsets occurrences can be replaced without causing a type error, so `generalize` just tries to replace all instances, and if this fails it just adds the equality to the context and leaves the goal unchanged.

`simp` works by a completely different method, and the first `list.length l` is not even accessible here because it is a dependent propositional argument.
