### ISSUE TITLE
Rewrite failure

### ISSUE THREAD

**Issue by PatrickMassot** [leanprover/lean3#1877]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Rewrite fails to run on an example from logic and proofs [sets in lean](https://github.com/leanprover/logic_and_proof/blob/master/sets_in_lean.rst).

### Caveat

This is literally my first day trying to learn how to use lean (after only a few days trying Coq, and no computer science training). I already had a lot of difficulties getting any example running (especially figuring out the LEAN_PATH variable trick). So I may be completely wrong in thinking what I explain below should work.

### Steps to Reproduce

1. Download lean-3.3.0-linux binaries from github (on a computer where no previous version of lean was ever installed)
2. install vs-code 1.18, and its lean extension (again, first version ever used), set lean.executablePath
3. git clone mathlib, at commit 2c84af163d
4. LEAN_PATH="lean-3.3.0-linux/lib/lean/library/:mathlib/" code
5. copy and paste from _logic and proof_:
```lean
import data.set
open set

variable  U : Type
variables A B C : set U

-- BEGIN
example : (A ∩ -B) ∪ B = A ∪ B :=
calc
  (A ∩ -B) ∪ B = (A ∪ B) ∩ (-B ∪ B) : by rw union_distrib_right
           ... = (A ∪ B) ∩ univ     : by rw compl_union_self
           ... = A ∪ B              : by rw inter_univ
-- END
```

**Expected behavior:** 

Lean is happy.

**Actual behavior:** 

The second rewrite fails, lean answers: 
```
rewrite tactic failed, did not find instance of the pattern in the target expression
  -?m_2 ∪ ?m_2
state:
U : Type,
A B : set U
⊢ (A ∪ B) ∩ (-B ∪ B) = (A ∪ B) ∩ univ
```

Note that writing the more explicit ``by rw compl_union_self B`` only makes the failure more puzzling (replacing ?m_2 by B). Asking to see the definition of ``compl_union_self`` returns ``theorem compl_union_self (s : set α) : -s ∪ s = univ := by finish [set_eq_def]``, which sounds promising.

**Reproduces how often:**

100%

### Versions

Lean (version 3.3.0, commit fa9c868ed2bb, Release) on Debian Sid

**Comment by kbuzzard** [comment]
This is not a bug. You are running Lean 3.3.0 but cloned mathlib so are probably running mathlib master, which is compatible with Lean master (i.e. Lean nightly). The code works fine for me with lean nightly https://leanprover.github.io/lean-nightly/build/lean-nightly-linux.tar.gz so you could try upgrading to that. If you still have trouble then you could ask at https://gitter.im/leanprover_public/Lobby where you might get helpful suggestions or explanations. The fact of the matter is that there was Lean 2, and some docs written for it, and then there was Lean 3, and now there are different versions of Lean 3, and sometimes people attempt to clean up the docs so that they work with <insert whichever version of Lean 3 is the favourite of the person doing the clearing up>. Sorry on behalf of the community that there are not more explicit instructions on how to get things up and running from scratch.

**Comment by robertylewis** [comment]
You're using a version of mathlib based on Lean 3.3.1. Check out the 3.3.0 branch of mathlib: https://github.com/leanprover/mathlib/tree/lean-3.3.0

If you use leanpkg (https://github.com/leanprover/lean/tree/master/leanpkg) you shouldn't need do do anything with LEAN_PATH.

> sometimes people attempt to clean up the docs so that they work with <insert whichever version of Lean 3 is the favourite of the person doing the clearing up>

The docs should all be based on the latest release version of Lean, currently 3.3.0. There's separate documentation for Lean 2.

**Comment by PatrickMassot** [comment]
Thank you very much for your answer. ``cd mathlib && git checkoutlean-3.3.0`` indeed solved my issue. I did come across leanpkg but I wasn't able to make any sense of the documentation I could find (not even understanding whether I needed it).
