### ISSUE TITLE
[RFC] Revise leanpkg build

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1880]
Currently, `leanpkg build` will call `lean --make` with the directory configured as `path` in the `leanpkg.toml` file. By default, this is `"."`, the project root itself, which brings some problems with it:
* `test/` is compiled as well. With our current test setup, that means that tests are also _run_ on `build`.
* All the dependencies in `_target/` are compiled as well (including _their_ `test/` directories!). With larger dependencies like mathlib, this may compile significantly more code than you actually use in your project. 

I would therefore suggest to enforce using `src/`, just like we're already hard-coding `test/`. We can start by setting it as a default for `leanpkg new/init` and printing a warning when leanpkg sees any different or missing path.

**Comment by spl** [comment]
I ran into a problem I reported in #1848 due to the default use of `.`.

**Comment by kbuzzard** [comment]
I have a Lean project containing some problems for students, and these lean files are (intentionally) full of sorrys. Although I don't synch scratch files on github, in practice when I compile my library there are also a bunch of scratch files around which typically don't even compile. It would be nice if the default behaviour of leanpkg build was to compile all the parts of my project which should compile, without having to deal with all these warnings and errors; this way I could check much more easily to see if recent changes in Lean broke my code.

**Comment by Kha** [comment]
> It would be nice if the default behaviour of leanpkg build was to compile all the parts of my project which should compile

I'm really not sure what you mean by that.

If you use a `src/` directory, you can put scratch files in another folder `scratch/` so that won't be compiled by `leanpkg build`, but can still import the project files. Does that help?

**Comment by kbuzzard** [comment]
In which case I'm not using the full functionality of leanpkg build, and my comment becomes "where are the docs that explain how to do what I want to do"? I want to make olean files in some cases (e.g. always mathlib, sometimes my lean files), and not in other cases. That's my sole use case of leanpkg build. 

If I move everything to src then either I change all my imports to src.<what they were> or I edit leanpkg.path [and my understanding from a recent conversation we had was that leanpkg.path is generated by leanpkg and should not be edited by the end user, which is why there is no explanation of the syntax]. Perhaps what you can take from my comments is simply that I am a Lean user who is failing to use leanpkg correctly and wants to learn how to use it better without bothering the devs. It sounds like I would also want to use this test directory functionality -- where can I read about that? All I see is "leanpkg test -- <lean-args>] : download dependencies, build *.olean files, and run test files". Is a test file equal to a file in a directory called test?

Should I submit a PR on leanpkg README.md, removing all mention of library_dev, adding some (possibly incorrect) ideas about how an end user like me might want to use leanpkg build (and other leanpkg commands -- like some unix man page), and then leave someone else to fix it up? Or should I just wait for someone who knows exactly what they're talking about to do this?

**Comment by spl** [comment]
@kbuzzard: I share some of your concerns, but I just wanted to share with you what I do, in case it might help.

My `leanpkg.toml` looks like this:

```toml
[package]
name = "alpha"
version = "0.0.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib.git", rev = "03074f197cb6f832eade66220f49ed999deec768"}
```

Every `.lean` file in `src` or a recursive subdirectory thereof is built by `leanpkg`. Any `.lean` file not in this hierarchy is not built by `leanpkg`.

To be able to have `leanpkg` run `lean` on files that I do not want to commit to my `git` repository, I added a line to my `.gitignore`:

```
# Ignore any sandbox file: these are for experiments.
sandbox*.lean
```
