### ISSUE TITLE
Adding type class instances in tactic mode doesn't work anymore

### ISSUE THREAD

**Issue by johoelzl** [leanprover/lean3#1920]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

In `mathlib` the following scheme is used to introduce type class instances in a tactic:
```lean
begin
  have := inst,
  exact t
end
```

Where `inst` provides a type class instance which is required in `t`. This doesn't work anymore, I guess it changed around https://github.com/leanprover/lean/commit/c132f555a9cfce9a76f0224064f8b737cbe5e579

The commit message indicates that it was a bug that it was not intended to work this way. Is this a general limitation how the type class mechanism and `type_context` works?

I wonder if it would be possible to implement a tactic `add_instance I`. Or a method  `with_instance (I : expr) (t : pexpr) : tactic expr` where `I` is elaborated and the resulting instance is added as type class instance when elaborating `t`?

My idea would be to extend `tactic.to_expr` with a list of additional instances. Does it make sense to try to prepare a pull request for this?

**Comment by johoelzl** [comment]
Another idea is to have a special `intro` which would allow to implement the following scheme:
```lean
apply_instance l t 
    ==
have : ∀[type_of I], target,
  {
    intro,
    exact t
  },
  exact @this I
]
```

but a test failed: 

```lean
class test : Type

def to_unit [test] : unit := ()

example : unit :=
begin
  have : ∀[test], unit,
  {
    intro,
    exact (to_unit : unit) -- failed to synthesise [test]
  },
  exact @this test.mk
end
```

**Comment by digama0** [comment]
See also: c132f555a. Bug was introduced in 6060b75.

**Comment by leodemoura** [comment]
Copying a comment here from https://github.com/leanprover/lean/commit/c132f555a9cfce9a76f0224064f8b737cbe5e579

------

@digama0 The idiom/hack was exploiting a bug in the type class instance cache management. The bug impacts performance, and type incorrect terms may be produced. The issue must be fixed.

For minimizing the impact on your code, I will add a new parameter (use_cache : bool := tt) to the mk_instance and apply_instance tactics. It will be tt by default, if the user sets it to ff, then the cache is not used nor updated, and all local instances are considered.

That being said, I have told you and @avigad that backward compatibility problems would happen, and I have strongly advised against building mathlib. I said more than once that it was not the right time. You replied saying that you didn't mind fixing the library over and over again.
Moreover, I told @avigad and you that small experiments and proofs of concept are much more useful for me at this point. That is, lean code that tests realistic scenarios, but can be discarded and doesn't need to be maintained. My point is that there are many more changes coming, and your code will break in much more spectacular ways. We should not expect that there will be a small fix/workaround every time. You should also not expect I will invest a huge amount of time working on a workaround that minimizes the effort of patching mathlib.

**Comment by leodemoura** [comment]
> My idea would be to extend tactic.to_expr with a list of additional instances. Does it make sense to try to prepare a pull request for this?

The cache management for type classes is still buggy. 
So, any PR related to this issue will be rejected.

**Comment by leodemoura** [comment]
> I wonder if it would be possible to implement a tactic add_instance I. Or a method with_instance (I : expr) (t : pexpr) : tactic expr where I is elaborated and the resulting instance is added as type class instance when elaborating t?

After the cache management is fixed, it should be possible to add a tactic that completely disables the cache (no read or write).

**Comment by digama0** [comment]
I certainly don't mind fixing mathlib as many times as is necessary (as the past few months should have demonstrated), but I was at a loss here because I didn't know how to fix the problem at all. It's even fine if there is no small fix / workaround, as long as the general problem of "how to solve problem X" has an answer. In this case, the problem is "how to elaborate a term with additional assumptions for typeclass inference beyond the ones at the start of the theorem". The `apply_instance` option also sounds like a workaround, but may be suitable for my purposes. Thank you.

I don't want you to develop things "for mathlib", but I hope that mathlib will help give you a sense of how "real code" interacts with the lean codebase as a large test bed. I think it is good that mathlib failed on this to flag it early as an important point - this is not a mathlib specific problem.

I have a concern with your proposed workaround, though: It doesn't sound as though it will work in typeclass problems that occur inside terms, for example in code like `by have comm_ring X := sorry; exact x + y`. How could I mark to not use the cache in code such as this?

**Comment by leodemoura** [comment]
> I was at a loss here because I didn't know how to fix the problem at all. 

We can always write the term explicitly. The issue here is convenience. You want a convenient one of patching the library.

> "how to elaborate a term with additional assumptions for typeclass inference beyond the ones at the start of the theorem".

Can't you write an auxiliary definition that takes the new instance as an argument?

> I think it is good that mathlib failed on this to flag it early as an important point - this is not a mathlib specific problem.

A design decision was made a long time ago: only local instances in the header of a declaration would be considered. There was a bug in the implementation that allowed code like the one in the issue above to be accepted. The bug is the problem, and it will be fixed. I understand you may not like the design decision.

> I have a concern with your proposed workaround, though: It doesn't sound as though it will work in typeclass problems that occur inside terms, for example in code like by have comm_ring X := sorry; exact x + y. How could I mark to not use the cache in code such as this?

I suggested another fix above when responding to @johoelzl.

**Comment by cipher1024** [comment]
Would it make sense to adopt a different proof style to circumvent the issue? It might be that, whenever you need an instance on the fly, extracting a lemma would improve the situation. Does that make sense with what you've seen in mathlib @digama0 ?

**Comment by digama0** [comment]
> We can always write the term explicitly. The issue here is convenience. You want a convenient one of patching the library.

I think it's a bit of a stretch to call type class inference a "convenience". It's pretty well essential in a great deal of lean-based design.

If you really really want to stick to this path, yes I'll have to add `@` everywhere and have huge proof terms where typeclass inference won't help me. But surely this is a sign that lean isn't doing something right?

> Can't you write an auxiliary definition that takes the new instance as an argument?

Maybe, but I would need to find a way to automate it as well, and for some reason `abstract` doesn't work in this case. Does the `abstract`ed tactic get elaborated in the context of the new definition, or the original one?

> A design decision was made a long time ago: only local instances in the header of a declaration would be considered. There was a bug in the implementation that allowed code like the one in the issue above to be accepted. The bug is the problem, and it will be fixed. I understand you may not like the design decision.

Is this decision at all up for discussion? I understand why you need the cache context to be mostly static, for performance reasons, but that doesn't point unambiguously to this protocol for resolving it. (In particular, it is compatible with the `have [tc A], from _, _` style of "labeled instance inclusion", by this notation or any other, i.e. Johannes's `add_instance`.) Are there places where the reasons for this decision are set out?

Disabling the cache altogether will work AFAICT, although there are obvious potential performance problems. It is not perfect but is certainly acceptable as a workaround.

---

Here are a few examples from mathlib that use this style:
```lean
inductive rcases_patt : Type
| one : name → rcases_patt
| many : list (list rcases_patt) → rcases_patt

meta instance rcases_patt.has_reflect : has_reflect rcases_patt
| (rcases_patt.one n) := `(_)
| (rcases_patt.many l) := `(λ l, rcases_patt.many l).subst $
  by have := rcases_patt.has_reflect; exact list.reflect l
```
Here the typeclass instance is the recursive function itself, so it has to be right of the colon. Yes it is possible to write this with an auxiliary, or with explicit args, but it's not nearly as clear.

```lean
@[simp] theorem not_forall_not [decidable (∃ x, p x)] :
  (¬ ∀ x, ¬ p x) ↔ ∃ x, p x :=
by have := decidable_of_iff (¬ ∃ x, p x) not_exists;
   exact not_iff_comm.1 not_exists
```
This can be argued as a "convenience" usage of typeclass inference to avoid giving a bunch of irrelevant information. But this would be quite ugly with auxiliaries:

```lean
lemma not_forall_not.aux [decidable (∃ x, p x)]
  [decidable (∀ (x : α), ¬p x)] : (¬ ∀ x, ¬ p x) ↔ ∃ x, p x :=
not_iff_comm.1 not_exists

@[simp] theorem not_forall_not [D : decidable (∃ x, p x)] :
  (¬ ∀ x, ¬ p x) ↔ ∃ x, p x :=
@not_forall_not.aux α p D (decidable_of_iff (¬ ∃ x, p x) not_exists)
```
It seems at least one `@`-usage is necessary here no matter how you cut it, since the typeclass parameter is instance implicit in the auxiliary and has to be given explicitly in the main theorem.

**Comment by leodemoura** [comment]
> I think it's a bit of a stretch to call type class inference a "convenience". It's pretty well essential in a great deal of lean-based design.

Type class resolution is an essential feature in Lean, but the ability of introducing new local instances in the middle of the declaration is not. corelib used it new local instances only once, and it was a bad use. Haskell also does not allow new local instances to be introduced.

> Is this decision at all up for discussion?

No, it is not. 

> Here are a few examples from mathlib that use this style:

All your examples are straightforward to patch.

**Comment by leodemoura** [comment]
The tactic `meta constant unfreeze_local_instances : tactic unit` can be used to fix broken proofs.
See doc-string for additional details.

**Comment by PatrickMassot** [comment]
@leodemoura Thank you very much!
