### ISSUE TITLE
disallow identical notation in the same namespace

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#310]
Another minor issue, but I think its sensible that if you overload notation, you can only do this in different namespaces. Otherwise there is no way to specify which one you want (right?) if there is ambiguity.

```
import data.nat
namespace foo
infixl `++++`:50 := nat.add
infixr `++++`:30 := or -- this should raise an error (or at least a warning)
end foo
```

Also: Coq disallows specifying two different precedences or associativity rules for the same notation, do we want that too?

**Comment by leodemoura** [comment]
> Otherwise there is no way to specify which one you want (right?) if there is ambiguity.

We can restrict that.

> Coq disallows specifying two different precedences or associativity rules for the same notation, do we want that too?

Should we allow different precedences in different namespaces?
BTW, the precedence is a little bit misleading, we use that because this is the concept most users are familiar with. In Lean, we use a Pratt's parser. The precedence is actually the left binding power of the token. (http://en.wikipedia.org/wiki/Pratt_parser)
