### ISSUE TITLE
implicit arguments in structure command

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#354]
In the file below, the type A is implicit in semigroup.mul_assoc, which is what we want. But it is explicit in the other two. Is this the intended behavior? Is there any way to make A implicit, while using the defined notion "associative"?

import logic

definition associative {A : Type} (op : A → A → A) := ∀a b c, op (op a b) c = op a (op b c)

structure semigroup [class](A : Type) :=
(mul: A → A → A) (mul_assoc : ∀a b c, mul (mul a b) c = mul a (mul b c))

check @semigroup.mul_assoc    -- A is an implicit argument

structure semigroup2 [class](A : Type) :=
(mul: A → A → A) (mul_assoc : associative mul)

check @semigroup2.mul_assoc   -- A is an explicit argument

structure semigroup3 [class](A : Type) :=
(mul: A → A → A) (mul_assoc : @associative A mul)

check @semigroup3.mul_assoc   -- A is an explicit argument

**Comment by leodemoura** [comment]
This is a unfortunate consequence of a recent change.
See the discussion at: https://github.com/leanprover/lean/issues/344

The first `mul_assoc` has type 

```
Pi (A : Type) [s : semigroup A] (a b c : A), mul (mul a b) c = mul a (mul b c))
```

Then, strict implicit inference is executed, since there are explicit arguments `a/b/c` after `A` that contains `A`, Lean marks `A` as implicit.

For the other versions, we have that `mul_assoc` has type

```
Pi (A : Type) [s : semigroup A], @associative A mul
```

Thus, `A` does not qualify as implicit by the strict inference rules. 
If we move to non-strict, then it would qualify since it appears in the result type.
However, @fpvandoorn provides good arguments to keep strict inference as the default (at https://github.com/leanprover/lean/issues/344). 
One option is to have the modifiers `{}` and `()` as we have in the inductive datatype command. The modifer `{}` enables `non-strict` inference. They are not supported in the structure command yet.
If we have them, we would write:

```
structure semigroup2 class :=
(mul: A → A → A) (mul_assoc {} : associative mul)
```

Yet another option is to change the strict inference rules. We could put the range in weak-head-normal-form before using it. That is, we would expand `associative mul` before applying the implicit inference rules.

**Comment by fpvandoorn** [comment]
This is indeed an unfortunate consequence of my suggestion. Maybe putting the type in whnf is a good idea, indeed.

That said, eventually we probably want to support the notation `{}` and `()` anyway. Whatever rule we come up with, some user will want it differently (but that's probably not a feature to implement now).

Aside: I'm quite sure we want `associative` to be `[reducible]` (and similarly for other already defined notions such as `reflexive` in `relation.lean`)

**Comment by avigad** [comment]
A third solution in this case is to write out associativity explicity
rather than using the abbreviation. I don't have a strong feeling about
this particular case, and I am finding it hard to anticipate what will be
more useful in general.

(The only reason I noticed it here is because of the other issue we have
been discussing, regarding merging structures -- at some point I had used
semigroup.mul_assoc to copy one component to another, and the change broke
that.)

We can certainly mark "associative" reducible, but I don't see why that
will help. It will only be used in cases like this, to state axioms in
structure and to state theorems, and there is no higher-order unification
going on. Unless the proposal is to expand something like associative mul
only if "associative" is reducible? That is overloading the meaning of
"reducible," but it makes some intuitive sense -- "reducible" =
"abbreviation".

Leo, could you remind me of the strict / nonstrict distinction? My guess is:
- non-strict : make implicit if it occurs in the type of a later argument
  _or_ the return result
- strict : make implicit if it occurs in the type of a later argument

Is that right?

**Comment by leodemoura** [comment]
> Is that right?

Yes, it is.
There is only one extra detail. Now, "later argument" means "later _explicit_ argument".
The motivations for the change are described at #344

**Comment by fpvandoorn** [comment]
> We can certainly mark "associative" reducible, but I don't see why that
> will help.

I didn't mean it as solution to the current problem; just as a separate remark.

**Comment by avigad** [comment]
Got it. But where will it make a difference? I.e. where do the definitions
interact with higher-order unification?

On Sat, Nov 29, 2014 at 12:57 PM, Floris van Doorn <notifications@github.com
