### ISSUE TITLE
simp tactic

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#358]
To keep things a little separated, I'll open a new issue from this (this is continued from #356).

It would be nice to have a more powerful tactic like Coq's `simp`. The main purpose for me (currently) would be to replace things like `⟨a,b⟩.1` by `a` in the goal, because that makes the goal much more readable. But a little beta-reduction and eta reduction could also be useful.

Note that this is not purely to see a nicer goal. Sometimes it makes a functional difference. I encountered one example of this so far: I wanted to revert the variable `v2`, but that failed because the context contained `p : ⟨ u1, u2 ⟩ .1 ≈ ⟨ v1, v2 ⟩ .1`

I want `dpr1` in `⟨a,b⟩.1` to be unfolded, but I don't want to unfold `dpr1` in `u.1`. So I want to unfold definitions only if that allows for some iota or beta (or eta?) reduction afterwards (I also want to unfold `compose` in `compose g f x`, but preferably not in `compose g f`). 

Is something like this feasible?

**Comment by leodemoura** [comment]
> It would be nice to have a more powerful tactic like Coq's simp. The main purpose for me would be to replace things like ⟨a,b⟩.1 by a in the goal, because that makes the goal much more readable.

Is the scope the whole goal (hypotheses + conclusion)?
Do you want to be able to control that?

> Note that this is not purely to see a nicer goal. Sometimes it makes a functional difference. 

I agree. This can make a big difference for the unification procedure.

> I want dpr1 in ⟨a,b⟩.1 to be unfolded, but I don't want to unfold dpr1 in u.1. So I want to unfold definitions only if that allows for some iota or beta reduction afterwards (I also want to unfold compose in compose g f x, but preferably not in compose g f). Is something like this feasible?

In principle, this is possible. I think the main issue is to find a nice "default" behavior.
That is, one that does what we want most of the time.

Remark: a transparent definition can be marked as: reducible, irreducible, or none.

What do you think of the following default?
- simp has two states: liberal and restricted
- in liberal mode, simp will unfold any transparent definition that is not marked as irreducible.
- in restricted mode, simp will not even consider definitions that are not marked as reducible.
- in restricted mode, when simp finds a reducible definition: switches to liberal mode, reduces expression and compares its size with the original one. If it is smaller it keeps the reduced expression, otherwise it discards it and reduces children expressions in restricted mode.

At least, for the examples you provided, it does the right thing.
- `a` is smaller than `⟨a,b⟩.1` -- we keep `a`
- `sigma.rec ... (fun a b, a) u` is bigger than `u.1`  -- we keep `u.1`
- `g (f x)` is smaller than `compose g f x` -- we keep `g (f x)`
- `fun x : A, g (f x)` is bigger than `compose g f` -- we keep `compose g f`

**Comment by fpvandoorn** [comment]
> Is the scope the whole goal (hypotheses + conclusion)?
> Do you want to be able to control that?

Preferably, yes, I want to control that. Coq gives a whole list of options where to use simpl-like tactics ([here](https://coq.inria.fr/refman/Reference-Manual011.html#Conversion-tactics)). I think the most important ones are (in decreasing order): everywhere; only in conclusion; only in a specific hypothesis (or lists of hypotheses).

So everywhere is a good default for me (though note that Coq's default is only the conclusion).

> What do you think of the following default?

Do I understand the following correctly?
If I call `simp` to the expression `⟨n+m, k⟩.1`, it will first be in restricted mode, and start by unfolding `dpr1`. Then it unfolds the resulting expression in liberal mode. In the next steps it will reduce the expression to `n+m`. Does it now compare the length of this expression with the length of the original one, or will it first continue to reduce `n+m` in liberal mode, thereby creating a expression which may be larger than the original one?

I'm not sure whether length of the expression is a good measure of the complexity. In Coq I often used `simpl` in the following case.

I define some function `f : nat -> nat` by recursion, and now I want to prove properties about `f`. Say I want to prove `forall n, P (f n)`. I do this by induction on `n`. In the induction step, I need to prove `P (f (succ n))` from `P (f n)`. To do this, I want to unfold the definition of `f (succ n)` in terms of `n` and `f(n)`. This definition might be much longer than `f (succ n)` itself.

**Comment by leodemoura** [comment]
I see your point. The scenario you describe makes sense.
The size is not a good metric.
I checked the link you sent. Let's use the same configuration options used in Coq.
Now, I'm wondering if we should also use these configuration options in our unifier.

**Comment by leodemoura** [comment]
@fpvandoorn I have been thinking about this issue.
The simplifier tactic (in Lean) will have many "bells and whistles". 
It will also do more than evaluation (Coq's `simp`). 
For example, it will also use rewrite/congruence rules provided by the user.
So, why do we need both tactics: (our) simplifier tactic, and evaluation tactic (aka Coq's `simp`)?
I think we should keep only our simplifier tactic since it will be more powerful.
It will address exactly the requests you have. We can install rewrite rules for all the cases you described.

**Comment by fpvandoorn** [comment]
I think there are merits to having a evaluation tactic in addition to the simplifier. Suppose I'm proving an equality in `nat`, and I call the simplifier. Will this use commutativity and associativity of addition on both sides of the equality to put them both in "normal form"? Maybe I don't want that... But maybe the evaluation tactic becomes similar to calling the simplifier which uses (almost) no theorems?

In either case, we can wait with the evaluation tactic until we have the simplifier, and judge whether we need something in addition at that time.
