### ISSUE TITLE
"invalid reference to undefined universe level parameter"

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#395]
Can somebody explain to me what's the cause for this error?

**Comment by leodemoura** [comment]
The kernel produces this error message when it is type checking a definition `D` that uses a universe level parameter `L`,  but `L` is not listed as a universe level parameter for `D`. 

This is probably a bug in the automation: elaborator, unifier, type-classes, definitional package, etc.
I say that because we usually do not provide the universe levels explicitly.

If you post the file that produces this error, I will take a look.

**Comment by javra** [comment]
The error occurs here: https://github.com/javra/msc-thesis/blob/master/code/dbl_cat/basic.hlean#L76

Even if the error occurs at line 76 the real cause is the structure definition in line 80.
