### ISSUE TITLE
Parameters of structures in contexts?

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#401]
https://github.com/javra/msc-thesis/blob/bbcf89474fe6ecc0eaeeb3e40f640a08be30cb0a/code/dbl_cat/basic.hlean#L85-L102

When delete the explicit arguments in line 85, lean says "cannot synthesize placeholder" even if the context contains a variable of that type up to universe levels and implicit arguments.

And when I include the explicit arguments in line 85, line 99 tells me that there is C_1 so a second copy of that class instance must be in the context but is never really shown?

**Comment by leodemoura** [comment]
@javra Did you find a solution by yourself?
I got your latest changes, and `two_cell_ob` doe not have the explicit arguments anymore.

**Comment by javra** [comment]
I "solved" it by deleting the "include C D"! Which causes that I cannot use class inference in the proofs and I have to state the classes explicitely (e.g. line 156).

**Comment by leodemoura** [comment]
I see, I will investigate. The command `structure` is probably ignoring the `include`.

**Comment by leodemoura** [comment]
I know what is going on.
The problem is that 

```
  structure worm_precat [class] : Type :=
```

is defined inside of a context. All meta-logical information (notation, coercions, classes, instances, etc) defined in a context is lost when the context is closed.
So, `worm_precat` is not tagged as a class outside of the context.
If we add the command 

```
class [persistent] worm_precat
```

after the end of the context, then everything works as expected.

That being said, the current behavior is not nice. Originally, we wanted a context to be a place where we can use a custom configuration/setting that does not affect the rest of the module. We would be able to do thing such as

```
context
     -- set options
     -- set reducible 
     -- set rewrite rules
     -- Then prove some tricky theorem
end
```

Unfortunately, this conflicts with a different use of `contexts`: we don't use it to set local configuration options, but to define a scope containing parameters, and auxiliary definitions (your case).
In this case, we don't want to loose information regarding new 'classes/instances/coercions' defined inside the context.

@avigad What do you think?

**Comment by javra** [comment]
Oh right. I think this might also be the reason for some other occurences of confusing bahaviour. I guess one solution would just be that globally used structure definitions should not be inside contexts. Pulling the def of e.g. worm_precat out of the context wouldn't hurt that much...

**Comment by avigad** [comment]
I am still fuzzy on the issues. Regarding this:

  Unfortunately, this conflicts with a different use of contexts: we don't
use it to set local configuration options, but to define a scope containing
parameters, and auxiliary definitions (your case).
  In this case, we don't want to loose information regarding new
'classes/instances/coercions' defined inside the context.

Is there a strong reason we cannot have "parameters" in sections? The
restriction would be that you cannot define notations in sections with
parameters. But the semantics would be clear: metalogical information in
sections persists, but not in contexts. And the error message for the
restriction would be clear: "cannot define notation in sections with
parameters".

**Comment by leodemoura** [comment]
> Is there a strong reason we cannot have "parameters" in sections?

You described one of the reasons: we cannot define notation in sections with parameters.
In general, this will be an issue for other meta-logical objects (e.g., rewrite rules).

That being said, I think we need something like the mechanism you suggested: allow parameters in sections and sign an error for bad cases (e.g., notation and rewrite rules in sections with parameters).
I will analyze the impact on the code base. This part is quite messy since we changed the semantics many times :-)

**Comment by avigad** [comment]
Excellent. I will revise the information in the tutorial.

On Fri, Jan 23, 2015 at 8:44 PM, Leonardo de Moura <notifications@github.com
