### ISSUE TITLE
tactics broken

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#402]
The "fake simplifier" no longer works in the emacs interface. To reproduce the problem, open data.int.basic, introduce an error, and fix it. Flycheck and C-c C-l report errors, starting with something like this:

/home/avigad/projects/lean/library/data/int/basic.lean:555:0: error: invalid 'apply' tactic, invalid argument
  simp
failed at:
  tactic.expr.builtin

Curiously, running "make" does not report any error, not even after "make clean-olean". If I run linja after a "make clean-olean", it finds errors all over the library, like

error: invalid 'apply' tactic, invalid argument
  apply_refl
failed at:
  tactic.expr.builtin

I if I then run "make", it fails with the same errors. But if I "make clean-olean" and run make again, make says it compiles successfully.

Does this have something to do with the trusted mode?

**Comment by leodemoura** [comment]
Yes, I changed the behavior of the trusted mode.
I had to change it to fix a "hole" in the kernel regarding macros.
Lean supports "macros" in the kernel. Each macro has a "trust-level".
Each macro provides a functions for returning the type of its instances, and another for "expanding" its instances. When we start the kernel, we set a "trust-level". 
Before yesterday's commit, the kernel would always accept declarations containing macros, and during type checking it would expand the macro (with trust-level >= the kernel trust-level), type check the result, but keep the macro (in unexpanded form). The motivation was mainly saving space: the expanded form may be much bigger. However, this approach is assuming macros are deterministic. There is also no easy way to enforce that the operations of substitution and macro expansion commute with each other. I realized these issues when I was implementing the support for "fast projections" using macros. 

Therefore, I modified the support for macros in the kernel. Now, the kernel will reject any declaration containing macros with trust-level greater than the kernel trust-level. So, we are forced to expand "untrusted" macros in declarations before sending them into the kernel. 

Unfortunately, this affects the way we store user defined tactics in .olean files.
Instead of having a special mechanism for defining tactics, we use the same infrastructure used to define constants in Lean. However, some tactics take "pre-terms" as arguments (e.g., `apply`). A pre-term is a term before elaboration. Thus, pre-terms do not even type check. To store them into regular definitions, we use a "macro" that wraps a "pre-term" as a term, but expands itself into a dummy `expr.builtin` term. The whole purpose of the macro is to store the "pre-term". The tactic `apply` "knows" how to interpret it, but for the kernel, it is just a "funny" way to say `expr.builtin` (https://github.com/leanprover/lean/blob/master/library/init/tactic.lean#L51).

Everything works when we build the library because we are compiling the library in "Trusted" mode, and the macros are not expanded. When we load an .olean file containing "untrusted" macros, we expand them before sending the declarations into the kernel. Consequently, all pre-terms stored in tactics are lost in the process.

One possible work-around is: use the option `-T` (trusted) when using user defined tactics. 
Note that, this will not prevent us from generating a .olean file using tactics, and then loading the .olean file without `-T`.
Of course, this is not convenient. So, we should probably make option `-T` the default. BTW, Jakob suggested that before. A user that cares about trust can always check everything using `lean -t 0 file.olean` (`-t 0` means trust-level `0`, i.e., do not trust any macro). That is, the user would be checking all declarations in `file.olean` and in files imported directly/indirectly by `file.olean` without relying on any macro. Moreover, even if a user cares about trust, I doubt he wants to check everything every time he executes Lean.

**Comment by leodemoura** [comment]
@avigad Ping

**Comment by avigad** [comment]
Sorry to be slow to respond -- I went out last night and was still thinking
about this.

What concerns me is that the error came up in files that use the tactics
(e.g. data.int.basic), not just the files that define the tactics. Does
that mean we can never check data.int.basic in untrusted mode? That seems
problematic.

Is this a correct understanding of the problem? The module
tools.fake_simplifier contains "definition simp := apply sorry". When
data.int.basic imports that module with trust level 0, the kernel checks
the definition of simp and expands the macro that hides the preterm "apply
sorry". So we will have the problem whenever we try to check any file that
imports a tactic definition, either directly or indirectly. Is that right?

Am I also correct in understanding that if I prove a theorem "foo" in
data.int.basic using "by simp", the proof term will _not_ contain any macro
that hides preterms? So the problem is not with type checking "real"
theorems and definitions, only tactic definitions.

Maybe one solution is to give the tactic macro a very secure trust level,
like "-1" (or "0", but make the default trust level higher than that).
There seems to be some room for abuse there, since a user could define
other macros with this trust level and use that to cheat.

Another solution would be to tag tactic definitions as special (e.g. define
them with the command "tactic definition ..."), and ask the kernel to check
them at a higher trust level or not at all.

The door to abuse there would be that a user could cheat by somehow marking
an ordinary theorem as a tactic definition, but that doesn't seem so bad.
There is a clear semantics: definitions and theorems are type checked
fully, tactic definitions are not type checked fully because they are not
really definitions or theorems.

Independent of this whole discussion, for performance, I agree that in
normal usage it is o.k. to check files with a high trust level. When a user
proves a big theorem, they can check it with 0 trust before they write the
paper.

On Wed, Jan 21, 2015 at 7:26 PM, Leonardo de Moura <notifications@github.com

**Comment by leodemoura** [comment]
> What concerns me is that the error came up in files that use the tactics
> (e.g. data.int.basic), not just the files that define the tactics. Does
> that mean we can never check data.int.basic in untrusted mode? That seems
> problematic.

We can check the data.int.basic.olean in untrusted mode.

**Comment by leodemoura** [comment]
> Is this a correct understanding of the problem? The module
> tools.fake_simplifier contains "definition simp := apply sorry". When
> data.int.basic imports that module with trust level 0, the kernel checks
> the definition of simp and expands the macro that hides the preterm "apply
> sorry". So we will have the problem whenever we try to check any file that
> imports a tactic definition, either directly or indirectly. Is that right?

Yes, modulo the following minor remark: 
- The definition is not expanded in the kernel, but by the module (outside of the kernel) that reads the definitions from an .olean file.

**Comment by leodemoura** [comment]
> Am I also correct in understanding that if I prove a theorem "foo" in
> data.int.basic using "by simp", the proof term will _not_ contain any macro
> that hides preterms? So the problem is not with type checking "real"
> theorems and definitions, only tactic definitions.

Yes.

**Comment by leodemoura** [comment]
> Maybe one solution is to give the tactic macro a very secure trust level,
> like "-1" (or "0", but make the default trust level higher than that).
> There seems to be some room for abuse there, since a user could define
> other macros with this trust level and use that to cheat.

We would have to move this macro to the kernel (trusted code base). 
We would also need to have a mechanism to prevent other macros from using trust level "-1".

**Comment by leodemoura** [comment]
> Another solution would be to tag tactic definitions as special (e.g. define
> them with the command "tactic definition ..."), and ask the kernel to check
> them at a higher trust level or not at all.

I thought about that too. This also requires a kernel extension. 
We would also have to implement a mechanism to prevent tactic definitions from being used inside regular definitions. Otherwise, the macros could "leak" inside the regular definitions.

**Comment by leodemoura** [comment]
> The door to abuse there would be that a user could cheat by somehow marking
> an ordinary theorem as a tactic definition, but that doesn't seem so bad.
> There is a clear semantics: definitions and theorems are type checked
> fully, tactic definitions are not type checked fully because they are not
> really definitions or theorems.

I think we can minimize the problem by forcing macro definitions to be restricted to objects of type `tactic`. However, the kernel would have to be aware of the existence of type `tactic`.
