### ISSUE TITLE
make install does not configure emacs

### ISSUE THREAD

**Issue by EgbertRijke** [leanprover/lean3#407]
emacs mode doesn't load after following the installation instructions. I'm on a ubuntu 14.10 machine.

**Comment by soonhokong** [comment]
I'm actually working on this. Did you install lean via apt-get on Ubuntu? If so, could you try the steps in http://www.cs.cmu.edu/~soonhok/talks/lean-mode.pdf (page 4, scenario#2)?

**Comment by EgbertRijke** [comment]
Jakob helped me compiling it from the source code using cmake and make install. He helped me setting up emacs too, but it didn't get configured automatically.

Last week I also installed lean via apt-get, but I ran into the same problem then.

**Comment by soonhokong** [comment]
I guess you're attending Prof. @avigad's lecture today. If so, I am happy to help you set things up before/after the class. Please find me in the class room if that's the case.

That being said, I want to take this as an opportunity to make things better. First of all, it's not really easy to fully automate the emacs setup process because it's required to modify user's emacs configuration.

For now, we have two issues which make things complicated:
1. lean-mode depends on other emacs packages such as comply, flycheck, etc
2. lean-mode requires the location of lean binaries such as `lean`, `linja`, and `leantags`.

I think the best solution is to upload lean-mode to the [melpa](http://melpa.org) so that users can install it via `package-install`. This is nice because we can specify its dependencies and `package-install` will install all the required packages for lean-mode.

For the second issue, I think we can first assume that those binaries (`lean`, `linja`, `leantags`) are in the system's path. As an option, we can also provide a customization variable to specify the location of them.

@leodemoura, what do you think? Of course, another option is to package all the required packages in lean-mode to make it self-contained. However, I'm not sure that this is an elegant solution (should be easier than melpa one for users though)

**Comment by leodemoura** [comment]
@soonhokong This is tricky. I don't really know what is the best approach.
The self-contained `lean-mode` may not be a clean solution, but it has some advantages.
- We control the dependencies. That is, `lean-mode` would not break because some package (e.g., `flycheck`) has been upgraded (and the upgrade is incompatible).
- For the user, it is easier to install.
- Isabelle and PVS use similar approaches. They even have a custom command that starts Emacs with their modes properly configured. This is particularly good for "novice" users.
- The user only needs one system `PPA` to perform upgrades. If we use `PPA` and `melpa`, then the user would have to execute `apt-get upgrade` and then upgrade lean-mode using `melpa`.

**Comment by soonhokong** [comment]
I agree that it's pretty tricky. Let me try to do the both of approaches -- self-contained version, and MELPA version. It would be great if we can let users to choose whatever they prefer to do.

**Comment by soonhokong** [comment]
@EgbertRijke told me today that he doesn't have the problem any more. So let me close this one.

@EgbertRijke, it would be great if you describe the problem and the solution that you applied (if it's easy to remember it).
