### ISSUE TITLE
unifier error

### ISSUE THREAD

**Issue by EgbertRijke** [leanprover/lean3#413]
In the following code, the last line produces a unifier error, which I don't understand

```
open sigma

namespace graphs

definition ctx : Type := 
  Σ(X:Type), X → X → Type

definition fam (G : ctx) : Type :=  
  Σ(Y : pr1(G) → Type), Π(i j:pr1(G)), pr2 G i j → Y i → Y j → Type

definition tm (G : ctx) (A : fam G) : Type := 
  Σ(x : Π(i : pr1 G), pr1 A i), Π(i j : pr1 G), Π(e : pr2 G i j), (pr2 A) i j e (x i) (x j)
```

**Comment by leodemoura** [comment]
I'm assuming you are using the HoTT version.

The funny error is produced whenever the search space (for the elaboration problem) is too big.
Here are possible solutions.

1) The simplest solution is to increase the Lean internal threshold. This is not a good solution since the file is going to be expensive to process.
On my machine, I can process `tm` by adding the following command before `tm`.

```
set_option unifier.max_steps 500000
```

2) Break `tm` in smaller pieces. The idea is to help the elaborator.
Example:

```
context
  parameter G : ctx
  parameter A : fam G
  definition X : Type         := pr1 G
  definition f : X → X → Type := pr2 G
  definition Y : X → Type     := pr1 A
  definition g : Π (i j : X), f i j → Y i → Y j → Type := pr2 A
  definition tm : Type :=
    Σ (x : Π (i : X), Y i),
      Π (i j : X) (e : f i j), g i j e (x i) (x j)
end
```

Lean can elaborate this version 50x faster than the previous one.

3- The following alternative uses `structure` instead of `sigma` types. It is compact and fast.

```
namespace graphs

structure ctx :=
(X : Type) (f : X → X → Type)
open ctx  -- creates the alias X for ctx.X and f for ctx.f

structure fam (G : ctx) :=
(Y : X G → Type) (g : Π (i j : X G), f G i j → Y i → Y j → Type)
open fam

structure tm (G : ctx) (A : fam G) :=
(x : Π (i : X G), Y A i) (h :  Π(i j : X G), Π(e : f G i j), g A i j e (x i) (x j))

end graphs
```

This one is much faster because the structures are "customized" for your problem. The projections `pr1` and `pr2` have implifict arguments, while `X`, `f`, `Y` and `g` do not.

**Comment by EgbertRijke** [comment]
Thanks! I've gone with option 3, the structures. I really like this option, because it gives me the possibility to choose uniform and descriptive naming even further:

```
namespace graphs

structure ctx :=
  (vertex : Type)
  (edge : vertex → vertex → Type)

structure fam (G : ctx) :=
  (vertex : ctx.vertex G → Type)
  (edge : Π{i j : ctx.vertex G}, ctx.edge G i j → vertex i → vertex j → Type)

structure tm {G : ctx} (A : fam G) :=
  (vertex : Π(i : ctx.vertex G), fam.vertex A i)
  (edge : Π(i j : ctx.vertex G), Π(e : ctx.edge G i j), fam.edge A e (vertex i) (vertex j))

end graphs
```
