### ISSUE TITLE
tab completion in namespaces

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#422]
If you open a new file and write

```
import data.nat
open nat
check mul.as
```

and hit tab, you are offered `mul.assoc` as a completion, which is good.

But suppose you are using a namespace instead:

```
import data.nat
namespace nat
check mul.as
```

The only option is to insert `nat.mul.assoc` and delete the `nat` prefix manually.

Could tab completion strip the prefix in namespaces just as with open?

**Comment by leodemoura** [comment]
@avigad Here is a related problem.
Consider the following scenario

```
import data.nat

check add.asso   -- press TAB after 'asso'
```

The auto-completion contains the `add.assoc` projection for many structures in the algebraic hierarchy.
Now, try `check add -- press TAB after 'add'`, then it is a "tsunami" of irrelevant information since there are many projections that contain the substring `add`. 
It is really hard to find anything. I essentially stopped using the auto-completion for any file that imports directly or indirectly the algebraic hierarchy.

One quick fix is to suppress "inherited projections". For example, the field `add_assoc` is defined at `add_semigroup`. So, the auto completion would suppress/hide `algebra.S.add_assoc` for any structure `S` that inherits the field `add_assoc` from `add_semigroup`. 
What do you think?

**Comment by avigad** [comment]
Good point. 

It is rare that anyone should have to access structure fields directly, because we have generic theorems and notations for that. For example, in algebra.group we define `algebra.add.assoc`. The user can always apply `add.assoc`, and should never have to write `s.add_assoc`. If they want to specify the structure directly, they can type `@algebra.add.assoc _ s`, and `s` will be coerced to an additive semigroup.

I guess what I am saying is that we can suppress _all_ structure projections, unless perhaps the user actually writes the structure in the prefix.

Does that make sense?

**Comment by leodemoura** [comment]
It makes sense. 
I was concerned about projections such as `sigma.pr1`, but I think you are right.

**Comment by leodemoura** [comment]
@avigad I can't reproduce the issue you have described. I got `mul.assoc` (not `nat.` prefix) in both cases. Could you please confirm the issue?

BTW, in the following

```
import data.nat
open nat algebra
check mul.as
```

The auto-completion will show `nat.mul.assoc` and `algebra.mul.assoc` since `mul.assoc` is overloaded. This is the indented behavior.

**Comment by avigad** [comment]
The plot thickens. You are right, with a truly empty file we get the intended behavior. In fact, I tested it in an existing file, and I used "exit" to filter out the rest. That seems to make the difference:

```
import data.nat
namespace nat
check mul.ass
exit
```

This produces exactly the behavior I described. It doesn't help if you close the namespace before exit:

```
import data.nat
namespace nat
check mul.ass
end nat
exit
```

It also happens if there is an error later in the file:

```
import data.nat
namespace nat
check mul.ass
definition foo (x : ℕ) : ℕ := y -- an error here
end nat
```

My guess is that that is what was causing the problem when I noticed the undesired behavior. 
If there is no error in `foo`, we get the desired behavior.

If it is hard to fix, I can live with it, now that I know what the problem is.

Here is another issue. I just ran into the case where I had to run "make clean-olean" after an update. Should we add a "Troubleshooting" section of the "Download" page, where we tell users how to do that? Sooner or later, they will run into the problem.

(If you would like, I will open a new issue for this, or just update the documentation myself.)

**Comment by leodemoura** [comment]
> Here is another issue. I just ran into the case where I had to run "make clean-olean" after an update. Should we add a "Troubleshooting" section of the "Download" page, where we tell users how to do that? Sooner or later, they will run into the problem.

This issue only affects developers and users that are building Lean and libraries by themselves. 
We can add a note in the build instructions. A "bullet proof" recipe is: after a 'git pull'  or 'git fetch', if there is a problem, then erase the build directory, and execute build instructions from scratch.

**Comment by leodemoura** [comment]
Oops... I missed the `make clean-olean` step...

**Comment by soonhokong** [comment]
@leodemoura, I think I've experienced a few cases where even `make clean-olean` doesn't fix a problem. For me, `cd /path/to/lean/library && git clean -fxd` always helps. FYI, here is an excerpt from `git help clean`:

```
       -f, --force
           If the Git configuration variable clean.requireForce is not set to false, git clean will refuse to run unless given -f, -n or -i.

       -x
           Don't use the standard ignore rules read from .gitignore (per directory) and $GIT_DIR/info/exclude, but do still use the ignore rules given with -e options. This allows removing all untracked files, including build products. This can be used (possibly in conjunction with git
           reset) to create a pristine working directory to test a clean build.

       -d
           Remove untracked directories in addition to untracked files. If an untracked directory is managed by a different Git repository, it is not removed by default. Use -f option twice if you really want to remove such a directory.
```

**Comment by avigad** [comment]
Do I understand correctly that "brew upgrade" and "apt-get upgrade" don't
rebuild the libraries?

If a user has a .lean project and upgrades Lean, couldn't his .olean files
break? That would require "linja clean" or something like that, wouldn't it?

I am just checking. There is a section of the tutorial where I say
something about projects. I can add a sentence about "linja clean" there,
if that would help.

**Comment by leodemoura** [comment]
> Do I understand correctly that "brew upgrade" and "apt-get upgrade" don't
> rebuild the libraries?

The new libraries come with them. For sure, when we are using `apt-get` on Linux.
Regarding `brew`, we should also get the new libraries.

> If a user has a .lean project and upgrades Lean, couldn't his .olean files
> break? That would require "linja clean" or something like that, wouldn't it?

Yes. `linja clean` should fix. 
Another solution is to add a dependency on the `lean` binary. That is, users projects are rebuilt whenever the `lean` binary is updated. This is not feasible for the builtin libraries since it would make the code development really slow.

@soonhokong Perhaps we can use a different approach in our cmake. In the new approach, by default, the rules in the automatically generated (ninja) makefiles would depend on the `lean` binary.  Thus, users would have a smooth update when upgrading lean. However, this default behavior is very inconvenient for Lean developers. Then, we add a flag to cmake `-D LEAN_BIN_DEP=OFF` that does not include the `lean` binary as a dependency. What do you think?

**Comment by soonhokong** [comment]
> Regarding brew, we should also get the new libraries.

I can confirm that this is the case. It first unlink the symbolic link to the previous library and create a new symbolic link to the current one.

> @soonhokong Perhaps we can use a different approach in our cmake. In the new approach, by default, the rules in the automatically generated (ninja) makefiles would depend on the lean binary. Thus, users would have a smooth update when upgrading lean. However, this default behavior is very inconvenient for Lean developers. Then, we add a flag to cmake -D LEAN_BIN_DEP=OFF that does not include the lean binary as a dependency. What do you think?

I think I understand what you want.

When I see the `src/CMakeLists.txt` file. I can see that the dependency is already there:

https://github.com/leanprover/lean/blob/master/src/CMakeLists.txt#L383

If I understand correctly, `Makefile` (or `build.ninja`) already detects any change in `/path/to/build_dir/shell/lean` and trigger `linja` calls for standard library and HOTT library. However, `linja` sees "nothing to do" because its generated build file does not depend on `bin/lean`.

What we need is a new `linja` option, something like  `--depend-on-lean-bin`, which enforces this dependency. To do this, we only need to change a couple of lines in `linja`. But I want to know whether we are on the same page on the topic.

**Comment by soonhokong** [comment]
In short,
- If a user runs cmake with `LEAN_BIN_DEP=ON`, it will call `linja` with `--depend-on-lean-bin`.
- With `LEAN_BIN_DEP=OFF` cmake option, it will call `linja` with `--no-depend-on-lean-bin` option.

Question is what should be the default options for both of `cmake` and `linja`.

**Comment by leodemoura** [comment]
For cmake, the default should be `LEAN_BIN_DEP=ON`.

For `linja`, I was not expecting a command line option. 
I was thinking about `cmake` generating the `linja` from `linja.in`.
`linja.in` would contain the following new line:

```
     LEAN_BIN_DEP=@LEAN_BIN_DEP_FLAG@
```

The value of `@LEAN_BIN_DEP_FLAG@` is set to `True` by `cmake` when `-D LEAN_BIN_DEP=OFF` is used.

`linja` would check the global variable `LEAN_BIN_DEP` when generating the rules.

The option is really just for us. Nobody should see it. 
If it is an option for `linja`, then we would also have to configure emacs.
I also edit .lean files all the time. If `--no-depend-on-lean-bin` is a flag for `linja`, I would also have to tell my emacs to send this flag.

**Comment by leodemoura** [comment]
I have a typo in the previous comment. It should be

The value of @LEAN_BIN_DEP_FLAG@ is set to False by cmake when -D LEAN_BIN_DEP=OFF is used.

**Comment by soonhokong** [comment]
@leodemoura, could you check the pull-request #425?
