### ISSUE TITLE
contexts and universe (variable) parameters

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#427]
in the following example, the last three checks shouldn't work and the output of the first two checks should be different.

```
import algebra.groupoid

open precategory truncation eq nat
open equiv groupoid morphism sigma sigma.ops prod
open path_algebra

namespace gamma
  context
  universe l
  parameters {D₀ : Type.{l}}
    [D₀set : is_hset D₀]
    [C : groupoid.{l l} D₀]
    (D₂ : Π ⦃a b c d : D₀⦄ (f : hom a b) (g : hom c d) (h : hom a c) (i : hom b d),
      Type.{l})
  include D₀set C

  protected definition gamma_CM2_gadget ⦃x : D₀⦄ (a lidu : hom x x)
    (v : D₂ a id id id) (u : D₂ lidu id id id) :=
  u

  set_option pp.universes true
  check gamma_CM2_gadget.{l}
  check gamma_CM2_gadget.{l l}
  check C.{l}
  check C.{l l}
  check C.{3}

  end
end gamma
```

**Comment by leodemoura** [comment]
The behavior you experienced is in the intended one. 
We can change it, but we have to think about the consequences.

In the given context, `gamma_CM2_gadget` means `gamma_CM2_gadget.{l} D₀  D₀set C D₂`.
This is the intended behavior for parameters in a context.

Now, we have the issue of providing explicit universe parameters to variables and parameters.
The current behavior is: if explicit universe parameters are provided, they are propagated to the types.
The semantics is: replace existing ones. 
We use this semantics because, in most cases, we do not provide the universe level parameters explicitly.

So, when processing `C.{l}`,  the parser transforms `C : groupoid.{l l} D₀` into `C : groupoid.{l} D₀`. Then, the elaborator will add a universe level metavariable to "fill" the missing universe parameter.

Another example: when processing `gamma_CM2_gadget.{3}` inside the context, the parser will replace `gamma_CM2_gadget.{l} D₀  D₀set C D₂` with `gamma_CM2_gadget.{3} D₀  D₀set C D₂`.
The new term is now type incorrect, and an error is produced.

Possible improvement:
- We can disallow the use of explicit universe levels for variables and parameters, and for constants inside contexts.

**Comment by javra** [comment]
We need some way to have explicit universe levels for parameters since there's many cases where one has to.

Me playing around with those levels resulted from another case of `failed to add declaration ... to environment, value has metavariables` where the metavariables actually only occur in the universe levels and I don't have the slightest idea where the they come from and why they are not all my set unvierse level `l`... Do you have any hints how I should tackle this kind of problem?

**Comment by leodemoura** [comment]
> We need some way to have explicit universe levels for parameters since there's many cases where one has to.

I meant when we are using them and not when we are declaring them.
That is, the following is ok

```
universe l
variable A : Type.{l}
```

But, the following `check` will be rejected since we are trying to provide explicit universe parameters to the variable declared above.

```
check A.{1}
```

**Comment by javra** [comment]
Yes I'd strongly prefer to reject such terms if @avigad or @fpvandoorn find this confusing as well.

**Comment by leodemoura** [comment]
> Yes I'd strongly prefer to reject such terms if @avigad or @fpvandoorn find this confusing as well.

Great. 
BTW, I just tried it, and no library file is affected by this change.

**Comment by avigad** [comment]
No objection here.

**Comment by fpvandoorn** [comment]
I also think we should reject such terms.
