### ISSUE TITLE
python looping?

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#428]
I just have a file where when I actually wanted to type in the last step of a proof, first lean keeps working for a while and then a python process uses up my full CPU time and doesn't stop. What does that mean?

**Comment by leodemoura** [comment]
We need the file(s) to be able to help and diagnose the problem.
It would also help to post step by step instructions to reproduce the problem.

**Comment by soonhokong** [comment]
@javra, could you tell us whether it happened in emacs or in command-line?

**Comment by javra** [comment]
It happened in emacs, at a point where I guess the result would have been an universe level metavariable. I solved it by giving the universe levels of a line 

```
apply (ap (λ x, _ ▹ x))
```

which also seems to have been the cause for my former metavariable mayhem. I'll try to recreate the state of the file and reproduce the error, but I don't think I will be able to keep it self contained.

**Comment by soonhokong** [comment]
>  I'll try to recreate the state of the file and reproduce the error, but I don't think I will be able to keep it self contained.

I'll try hard to reproduce the problem tonight. Any extra information will be very helpful (i.e. the file that you're working on...). Of course, the self-contained example with reproducible steps is ideal though I understand that it's hard to make in many cases.

**Comment by javra** [comment]
This is the file with the line that probably causes the loop marked.

https://github.com/javra/msc-thesis/blob/python-loop/code/equivalence/gamma.hlean#L119

It can be solved by replacing `apply (ap (λ x, _ ▹ x))` by `apply (ap (λ x, transport _ _ x))`. Maybe it's also not really nondetermination but just trying very hard to determine that second universe level parameter of transport.

**Comment by soonhokong** [comment]
Dear @javra,

I couldn't reproduce the problem, but I have some questions:
- When I tested https://github.com/javra/msc-thesis/blob/python-loop/code/equivalence/gamma.hlean file, I already had 28 errors in the file. Is it what you also have?
- When you see the python process uses 100% CPU, do you see `FlyC*` in your mode-line in Emacs? If so, it confirms that `flycheck` is still running and possibly uses all the CPU resources. Otherwise, it's not clear that the python process is a Lean-related process.
- Can you give me more information about `a python process`? There should be a full-path binary name attached to the process. FYI, `ps aux | head -n 10` gives you top 10 processes in the order of CPU usage. 

I was afraid that what you experienced was cause by the lack of `.hlean` support. Now, I can't really eliminate the possibility.  Let me finish the `.hlean` support and then let's test this again.

It would be great, if you can create shorter and reproducible steps for this problem.

**Comment by javra** [comment]
Hi @soonhokong,
- I don't have any errors in that file, did you check out the entire repo?
- Yes, I see `FlyC*`. I'm pretty sure it's lean related since I didn't have any other applications running.

Maybe we should not look at the problem until we have the proper `.hlean` support. In shorter settings the problem didn't exist. Maybe the process is flycheck creating some sort of output (the `unsolved metavariable error?) and taking a huge amount of time since it's trying to print the big term with all implicit arguments?

**Comment by leodemoura** [comment]
> Maybe the process is flycheck creating some sort of output (the `unsolved metavariable error?) and taking a huge amount of time since it's trying to print the big term with all implicit arguments?

This may be the problem. The pretty printer has some thresholds (max. number of lines, max. number of terms, etc). When the limit is reached, the pretty printer uses `...` for subterms.
However, the current default value for these thresholds is `unbounded`.
Perhaps, the default should be a  small value instead of unbounded. 
Then, users would have to set these options explicitly if they want to see big terms.

What do you think?

including @avigad @fpvandoorn

**Comment by soonhokong** [comment]
> @javra wrote: "I don't have any errors in that file, did you check out the entire repo?"

Yes, I did. Is it possibly because of the recent changes in Lean?

> @leodemoura wrote: "Perhaps, the default should be a small value instead of unbounded. Then, users would have to set these options explicitly if they want to see big terms."

I think it's a good solution.

**Comment by javra** [comment]
@soonhokong: Ah, i found the cause of the error, I hadn't pulled the change that apply uses class instance resultions yet.

**Comment by soonhokong** [comment]
@javra, do you still experience this problem?

**Comment by javra** [comment]
I'm just experiencing it [here](https://github.com/javra/msc-thesis/blob/master/code/equivalence/lambda.hlean). The second to last lemma seems to be the cause.

**Comment by javra** [comment]
Okay, by compiling it I saw that the output is something around a few ten thousand lines. It is a "value has metavariables" error, so implicit arguments are shown, but I still don't see why the output should be _that_ large...

**Comment by javra** [comment]
One solution could be to limit the lines of output at least to a few thousand lines in a way that each subterm that comes after the limit isn't even formatted...

**Comment by leodemoura** [comment]
I forgot to change the default. I will do it today. In the meantime, you can use

```
set_option pp.max_steps 1000  -- or smaller value
```

**Comment by javra** [comment]
Okay, that's a good feature!

**Comment by soonhokong** [comment]
:+1:
