### ISSUE TITLE
disable flycheck temporarily?

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#451]
Sometimes I want to disable flycheck temporarily when I work on definitions that are hard for the elaborator. But when I un-check the "Enable on-the-fly-sytax-checking" in the FlyCheck menu, the flycheck button disappears completely. Could you change that such that the button is still there but flycheck deactivated?

**Comment by leodemoura** [comment]
@soonhokong 
I believe the problem is `flycheck` (parsing the error messages).
If the machine has more than 1 core, then there is no reason to disable flycheck. We limit the amount of memory used by Lean. So, in principle, Lean should not affect the editor if it is running in the background.

Yesterday, I was performing some experiments, and noticed flycheck sometimes makes the system unresponsive. The problem can be reproduced by opening a file with many declarations (e.g., `library/data/int/basic.lean`). Then, introduce an error in a definition that is used by many other definitions (e.g., `repr_mul`). Now, many errors are generated, and it is hard even to edit the file. There is a delay after every keystroke. It seems `flycheck` blocks Emacs by trying to parse the error messages. This is really annoying. 

@javra Is this similar to the problem you are having?

I use the following workarounds:

1- Add an `exit` after the definition I'm editing, OR

2- Reduce the maximum number of errors reported by `flycheck`. The default is 100, if I reduce to 10, then the system is usable again.

Anyway, I think we need to fix this.

**Comment by soonhokong** [comment]
@leodemoura, you're right. We had a similar problem when we first tried to use `flycheck` to show type information. We showed that when it has more than 200 - 300 messages, it started getting slower.

**Comment by soonhokong** [comment]
I see... even limiting to 100 is not enough sometimes.

**Comment by leodemoura** [comment]
Here is a discussion in the flycheck issue tracker:
https://github.com/flycheck/flycheck/issues/179

I tried `(setq flycheck-highlighting-mode 'symbols)`, and it was still super slow.
I also tried `(setq flycheck-highlighting-mode 'lines)`, and did not observe a significant improvement. I  still had a noticeable lag after each key stroke.  
Now, I'm wondering if the problem is the regular expressions we use in `lean-flycheck.el`.
We use `minimal-match` there.

**Comment by javra** [comment]
I have two cores, but flycheck often (always?) creats two lean processes that sometimes work at the same time.(One for the flychecking and for indexing?) The problem I have is more that the emacs processes slow down the entire computer.

I always put an exit below the definition I'm working on but often that's not enought becaus I often run into looping things (and right now I'm having at least two definitions that need 500000 unifier steps but I'll work to avoid that).

**Comment by leodemoura** [comment]
Jakob, I took a look in your files. You should try the `cases` tactic. `cases F` is much faster than using `apply C.rec_on F`. It also does the `revert` step (if needed). It also handles indexed families. The `cases` tactic is not perfect for HoTT mode (it still needs polishing), but it is already useful.

I rewrote `dbl_functor_sigma_char` (one of the definitions that were taking 500000 steps) using `cases`.
The new version can be processed using the default threshold. I also used the new nested begin-end blocks.

```
  definition dbl_functor_sigma_char (D E : Dbl_precat) :
    (Σ (catF : functor (cat D) (cat E))
       (twoF : Π ⦃a b c d : cat D⦄
         ⦃f : hom a b⦄ ⦃g : hom c d⦄ ⦃h : hom a c⦄ ⦃i : hom b d⦄,
         two_cell D f g h i → two_cell E (catF f) (catF g) (catF h) (catF i)),
       (respect_id₁_type D E catF twoF) ×
       (respect_comp₁_type D E catF twoF) ×
       (respect_id₂_type D E catF twoF) ×
       (respect_comp₂_type D E catF twoF)) ≃ (dbl_functor D E) :=
  begin
    fapply equiv.mk,
      begin
        intro S, fapply dbl_functor.mk,
        apply (S.1), exact (@S.2.1), exact (pr1 @S.2.2),
        exact (pr1 (pr2 @S.2.2)), exact (pr1 (pr2 (pr2 @S.2.2))),
        exact (pr2 (pr2 (pr2 @S.2.2)))
      end,
      begin
        fapply is_equiv.adjointify,
          {intro F, cases F,
           apply (sigma.mk catF (sigma.mk twoF
                   (respect_id₁ , (respect_comp₁, (respect_id₂, respect_comp₂)))))},
          {intro F, cases F, apply idp},
          {intro S,
           cases S   with (catF, S'),
           cases S'  with (twoF, S''),
           cases S'' with (respect_id₁, S'''),
           cases S''' with (respect_comp₁, S''''),
           cases S'''',
           apply idp}
      end
  end
```

**Comment by javra** [comment]
Oh, thanks for the hint! I thought cases, destruct and `apply (...rec_on x)` would be the same in the case of products and sigmas.

**Comment by leodemoura** [comment]
For non-indexed families, here are the advantages.
1- `apply` does not "know" what a recursor is. That is, it treats it as any other function. In contrast,  `cases` "knows" how to synthesize the recursor implicit arguments more efficiently. It is customized for that.
2- `cases F` will automatically revert any hypothesis `H` that depends on `F`, apply the recursor, and then `intros` back all dependent hypothesis, and the constructor arguments.

**Comment by leodemoura** [comment]
Regarding the two processes in @javra's  comment, one process is used by flycheck. It starts a new process whenever the user modifies the file. This process uses the cache. Thus, if we put an `exit` command after the definition `D` we are working on, the time is roughly the time to process `D`. 
The second process is a background process started by Emacs. We call it the "Lean server". This process is responsible for auto-completion and providing type information. For expensive files, I think it is more useful to disable the second process (auto-completion and type information).
@soonhokong What do you think?

**Comment by soonhokong** [comment]
We can have two `lean-server` processes (one with `--hlean` and another with `--lean` argument), if a user is editing both of standard and HoTT files together.

> For expensive files, I think it is more useful to disable the second process (auto-completion and type information).

I think disabling `eldoc-mode` (automatically showing type information at point) should be enough. Once it's disabled, the `lean-sever` process is only activated by a user request -- either pressing <kbd>C-c C-t</kbd> for type information and <kbd>tab</kbd> for auto-completion.

I can create a key-binding for that, and also add it to the menu. @leodemoura, what do you think?

**Comment by leodemoura** [comment]
> I can create a key-binding for that, and also add it to the menu. @leodemoura, what do you think?

I think it is a good idea.

**Comment by soonhokong** [comment]
![screen shot 2015-03-05 at 2 43 47 pm](https://cloud.githubusercontent.com/assets/403281/6513046/28c79cc4-c346-11e4-9548-c17921918d06.png)
