### ISSUE TITLE
When ending namespace `foo`, keep `foo` open if it was opened before beginning of the namespace

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#493]
``` lean
open foo

namespace foo
   definition bla := 10
end foo

check bla  -- should work
```

**Comment by leodemoura** [comment]
This one is also messy. The main issues are:
- `open` is a command with many options: `renaming`, `hiding`, etc.
- The order we execute `open` commands matter. Example: we may override coercions, notations, etc.

The only way I found to implement this feature is the following:
1- Store all executed `open` commands on a stack. 
2- When we close a namespace/context/section, we must remove the `open` commands introduced in the current scope from the stack.
3- Then, if we closed a namespace called `foo`, and there is an `open` command for `foo` on the stack, then we must re-execute the whole sequence of `open` commands on the stack.

**Comment by fpvandoorn** [comment]
Yes, when you were at CMU you told me that this issue is messy.

Maybe a simpler (but imperfect) solution is that whenever you `end` a namespace `foo`, all `open [*options*] foo` commands will be re-executed right after you `end` the namespace (but all other `open`-commands will be ignored). Most of the type this will mean that `open foo` will be automatically executed right after `end foo`. This might lead to problems because now the namespaces are opened in a different order than before, which could cause issues (but in practice will only do seldomly, I think).

Another solution might be that when you `end` namespace `foo` lean executes all previous `open [*options*] foo` to the objects declared in this new namespace only.

I don't know whether either of these options is simpler to implement (or more efficient) than the one you proposed. If there is no simple solution, then this issue becomes really low-priority. It's not that bad  to sometimes write 

``` lean
end foo  open foo
```

**Comment by leodemoura** [comment]
The problem of the imperfect solution is that it will eventually backfire. I agree with you, this is not an issue most of the time. However, I'm pretty sure a user (like you) will find the problem. 
BTW, whenever I have implemented an imperfect solution, you usually is the first to find the corner case where it does not work :-) 
My point is: whenever I tried to "cut corners", someone eventually found out the corner case.

> Another solution might be that when you end namespace foo lean executes all previous open [_options_] foo to the objects declared in this new namespace only.

This is the ideal solution. However, we don't keep the information: "recently declared objects". Without this information, I don't see how to implement this solution. Note that, we have many modules that declare meta-objects: coercions, classes, notation, ...
All of them would have to provide the feature: "recently declared objects".

**Comment by fpvandoorn** [comment]
> BTW, whenever I have implemented an imperfect solution, you usually is the first to find the corner case where it does not work :-) 

Yeah, that has happened a couple of times. So I probably shouldn't be the one suggesting imperfect solutions :-)

> This is the ideal solution. However, we don't keep the information: "recently declared objects". 

Yes, I see why that information is needed. Is it hard to keep that information? For each namespace you open, create a couple of lists. To one you add the names of all the declarations in that namespace, one with identifiers for all declared notations (if notations have unique identifiers to represent them) and so on. After you close the namespace you run through these lists and then remove them. [Of course I have no idea how hard this will be to actually code.](https://xkcd.com/1425/)

**Comment by leodemoura** [comment]
> Is it hard to keep that information?

Conceptually it is simple. It is just busy work, we have to go over all modules that implement meta-objects and add this functionality. Note that the lists are not just lists of names, but lists of data that represent the meta-objects being declared.

**Comment by fpvandoorn** [comment]
Ok. If it's a lot of work, then I'm fine with postponing this until later. The benefit is small. For the moment we can just write `end foo  open foo`.
