### ISSUE TITLE
support for adding new commands in Emacs mode

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#499]
@soonhokong This is the feature we discussed in Jeremy's office last week.
It would be super useful for Jeremy, Floris and Jakob.
You took a picture of Jeremy's whiteboard.
Do you remember?

**Comment by soonhokong** [comment]
Yes, I got it.

**Comment by soonhokong** [comment]
Example: 
1. First include the following lines in your emacs setup.
   
   ``` elisp
   (add-hook 'lean-mode-hook '(lambda ()
   (lean-define-key-binding "\C-c\C-g"
                            '(lean-exec-at-pos "lean-goal" "*Lean Goal*" "--goal"))))
   ```
2. Press `C-c C-g` will execute Lean with `--goal` option in addition to `--line <LINE>` and `--col <COL>` arguments, and send the result to `*Lean Goal*` buffer.

@leodemoura, I couldn't test it because Lean doesn't support `--line` and `--col` options yet. If you find any bug, please let me know.

For an unmodified file-base buffer, it passes the file to Lean with `--cache` option. For a modified file-base buffer, we first ask a user to save it (like `compile` command). If he/she saves it, we handle like the unmodified file-base buffer case.

For an unsaved modified file-base buffer, and non-file-base buffer (temp file), we create a temporary file and pass it to Lean. For this case, we don't use `--cache` option.

**Comment by leodemoura** [comment]
Thanks!
I added dummy options for testing the interface with Emacs.
Lean will just display 

```
SHOW GOAL @ <line> : <col>
```

and terminate when the options `--line`, `--col` and `--goal` are provided.

I'm having the following problems:
1- The buffer `*Lean Goal*` does not become visible when I press `C-c C-g`. I try to to use `(display-buffer-same-window process-buffer-name)` in the end of `lean-exec-at-pos.

2- Then, the buffer `*Lean Goal*` sometimes does not show the output produced by Lean. I don't know why. Sometimes, it just shows: `Process lean-goal finished`

Process lean-goal finished

**Comment by soonhokong** [comment]
> I try to to use (display-buffer-same-window process-buffer-name) in the end of `lean-exec-at-pos.

`display-buffer-same-window` expects two arguments while it provides only one argument. I think it could explain some unexpected behavior. What about `display-buffer` instead of `display-buffer-same-window`? (ca81e9bee254727bfa7171140baf6b67cb1449c1) It works for me. Please test it and let me know.

**Comment by soonhokong** [comment]
@leodemoura, could you check this one?

**Comment by leodemoura** [comment]
I tested it. I'm still having the same problem.
Most of the time the buffer `*Lean Goal*` contains the produced output. Example:

``` lean
SHOW GOAL @ 76 : 0

Process lean-goal finished
```

but it other cases, the output produced by Lean is missing, and I get only

``` lean
Process lean-goal finished
```

I don't know what is going on.  Here are the steps to reproduce the problem:
1- Add the following configuration to emacs initialization

``` elisp
(add-hook 'lean-mode-hook '(lambda ()
(lean-define-key-binding "\C-c\C-g"
                         '(lean-exec-at-pos "lean-goal" "*Lean Goal*" "--goal"))))
```

2- Open a .lean file, and keep pressing `\C-c\C-g`. Every invocation must contain the message `SHOW GOAL ...`.

**Comment by soonhokong** [comment]
I see.. I'll test it.

**Comment by soonhokong** [comment]
@avigad, @fpvandoorn, @javra, could you help me test this feature?
- Have the following lines on your emacs setup:
  
  ``` lisp
  (add-hook 'lean-mode-hook '(lambda ()
  (lean-define-key-binding "\C-c\C-g"
                       '(lean-exec-at-pos "lean-goal" "*Lean Goal*" "--goal"))))
  ```
- Open `library/data/real/basic.lean` (or any file).
- Hit <kbd>C-c</kbd><kbd>C-g</kbd> inside of a `begin` - `end` region.

## Expected Behavior
- Have a separate buffer `*Lean Goal*` displayed.
- It should have something like the following (`46 : 37` means that you invoked the command at line 46, column 37):
  
  ```
  SHOW GOAL @ 46 : 37
  
  Process lean-goal finished
  ```

If you have something different (i.e. only showing `Process lean-goal finished`), please let me know your machine OS (i.e. Ubuntu-12.04), and emacs version (which you can get by running <kbd>M-x</kbd>`version`. Thank you!

BTW, please try it multiple times, because it seems that it's hard one to reproduce. @leodemoura and I are working on this.

**Comment by avigad** [comment]
It works for me, with one small issue: the window opens with

```

Process lean-goal finished
```

at the top of the buffer. If I put my cursor in the buffer and move it to the top, forcing the buffer to scroll down, I see

```
SHOW GOAL @ 183 : 20

Process lean-goal finished
```

In other words, the window opens with the second line of the buffer at the top, and the first line not displayed.

If I press C-c C-g again, with the buffer open, again the first line scrolls off the screen.

**Comment by soonhokong** [comment]
> In other words, the window opens with the second line of the buffer at the top, and the first line not displayed.

Thank you so much!!!!!

**Comment by leodemoura** [comment]
@avigad You saved the day! We didn't realize the information was there, but hidden.
Moreover, the problem does not happen in every OS.

**Comment by soonhokong** [comment]
For the record, I'll implement a temporary solution -- 'always scroll to the top'. When we see a problem in this hack, let's revisit this issue later.

**Comment by soonhokong** [comment]
@avigad, thanks again for helping us diagnose the problem. Could you test the <kbd>C-c</kbd><kbd>C-g</kbd> one more time after checking out the latest commit? It should show something meaningful now. Any comments are welcome as always.

**Comment by avigad** [comment]
I am happy that I could be helpful. Now I can read a tactic proof and see the goal at each step. It is really, really beautiful!

**Comment by arademaker** [comment]
It would be nice to have some emacs tips and this new feature documented in the tutorial.

**Comment by avigad** [comment]
The system has been evolving quickly, and there is a long list of features that we still need to describe. I am sorry that we have not been able to keep up, but we are still working on it. 

What do you have in mind for the emacs tips? The emacs mode is described in Section 5.4 of the tutorial. There is a quick reference here:

  https://github.com/leanprover/tutorial/blob/master/A1_Quick_Reference.org

It is available in the PDF version of the tutorial, and we will also put it online soon. Other than expanding Section 5.4 and the discussion of tactic mode in the tutorial, and adding to the quick reference, are there other things we can do that would be useful?

**Comment by soonhokong** [comment]
- We're adding and cleaning up things.  We'll update the documentation before 2 Aug.
- We just added another feature to <kbd>C-c</kbd><kbd>C-g</kbd>: if a cursor is on `_`, it shows a goal for the placeholder that you're at. Please test and let us know if you find a bug.
