### ISSUE TITLE
HoTT with impredicative universe

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#523]
@awodey asked if we can have a HoTT mode with an impredicative universe. 

I recall that the HoTT mode and the standard mode are two instantiations of the Lean kernel, and that we can already instantiate it in a third setting - without proof irrelevance in Type.{0}, but with impredicativity. If so, how do you do this?

**Comment by awodey** [comment]
to be more specific — an impredicative universe that is _not_ proof irrelevant (and perhaps containing some non-trivial types, like nat).

SA

**Comment by leodemoura** [comment]
I added the branch https://github.com/leanprover/lean/tree/imp_hott

Type.{0} is impredicative and proof relevant.
Here is a small example

``` lean
variable a : Type₀ 

inductive nat₀ : Type₀ :=
| zero : nat₀
| succ : nat₀ → nat₀

check ∀ A : Type, nat₀
-- Prints Type₀
```

Disclaimer: I had to disable the following automatically generated constructions for inductive datatypes: `no_confusion` and `brec_on`. 
I had to comment some theorems from the HoTT library.
Moreover, since `no_confusion` and `brec_on` are not available, we cannot use recursive equations.

This is why I put this experiment in a separate branch.

**Comment by awodey** [comment]
That was fast!
Thanks - that will be interesting!
Steve

**Comment by leodemoura** [comment]
I'm closing this issue since we have the branch https://github.com/leanprover/lean/tree/imp_hott.
Remark: to make this feature official, we would also have to support two versions of the HoTT library.

**Comment by awodey** [comment]
I’m not sure what would be involved in supporting two versions of the HoTT library, but I’m glad this is available for experimentation.
Perhaps it doesn’t really have to be “official”, whatever that involves?

Steve
