### ISSUE TITLE
allow local coercions in contexts

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#525]
From @rlewis1988 

Hi Leo/all,
I ran into the following problem yesterday. Jeremy, Floris and I aren't sure if there's a nice way around this.

I want to define a coercion locally, to a type determined by a parameter. For example:

context
  parameter A : Type
  parameters (a : A) (s : A → A)
  definition foo (n : ℕ) : A := nat.rec_on n a (λn' IH, s IH)
  local attribute foo  [coercion]
end

Lean complains that coercions cannot be defined in contexts. But there shouldn't be anything wrong with this, right? Is it possible to do?

(This came up while proving facts about rational sequences, on the route to constructing R. Many of these theorems are true for arbitrary ordered fields F, not just Q, so we can reuse proofs by making things parametric in F. But it's convenient to have a coercion num -> F for writing things like eps / 2.)

Thanks!
-Rob

**Comment by leodemoura** [comment]
Actually the previous commit did not fully fix the problem. It allows local coercions.
However, we also need to allow coercions to parameters

**Comment by leodemoura** [comment]
I'm working on #668, #666 and #679. Since I'm revising the coercion module, I tried to accommodate this issue. Well, this one is a mess. Recall that the section mechanism in Lean is quite different from Coq. 
I described it at #554. The summary is, the type of `foo` inside and outside of the section is `Pi (A : Type), A -> (s : A -> A) -> num -> A`. However, inside the section we maintain the alias `foo := @foo A a s`.
To close this issue, we have to handle aliases in the coercion management module, manage these parameters, and propagate them as we compute the transitive closure. 

The benefit of implementing this issue is quite small. BTW, @rlewis1988 used a simple workaround for the `eps / 2` problem. He defined 

``` lean
notation 2 := pnat.pos 2 dec_trivial
```

For these reasons, I'm closing this issue. The only reasonable way to support it would be to move to Coq's approach for handling sections, but this would create other problems (see issue #554).

**Comment by robertylewis** [comment]
In fact, the definition

``` lean
notation 2 := pnat.pos 2 dec_trivial
```

was not a workaround for this problem. This originally came up before we had rat as a concrete structure: the thought was that some of the work in constructing the reals could be reused, by making the construction parametric in the field being completed. This seemed to be a fair amount of trouble for little benefit, though, so once Jeremy finished rat I just used that explicitly. Since there's a (global) coercion num -> rat, this issue became irrelevant.

The `2` notation was simply for the positive natural number 2. I could have used a global coercion num -> pnat for this as well, but it seemed easier to avoid having so many coercions from num open when I only needed the pnats 2 and 3.

In any case, the original need for this feature is gone, and I doubt it will come up very often at all- I won't miss it.
