### ISSUE TITLE
type mismatch with rewrite tactic

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#550]
Taking my very first steps with lean, I stumbled upon a type-check failure that, as far as I can tell, seems to be not of my own but the rewriter's doing: While the tactic succeeds, type checking the last lemma does not:

``` lean
import algebra.function
import logic.axioms.funext

open function

structure bijection (A : Type) :=
(func finv : A → A)
(linv : finv ∘ func = id)
(rinv : func ∘ finv = id)

attribute bijection.func [coercion]

namespace bijection
  variable {A : Type}

  definition compose (f g : bijection A) : bijection A :=
  bijection.mk
    (f ∘ g)
    (finv g ∘ finv f)
    (by rewrite [compose.assoc, -{finv f ∘ _}compose.assoc, linv f, compose.left_id, linv g])
    (by rewrite [-compose.assoc, {_ ∘ finv g}compose.assoc, rinv g, compose.right_id, rinv f])

  infixr `∘b`:100 := compose

  lemma compose.assoc (f g h : bijection A) : (f ∘b g) ∘b h = f ∘b (g ∘b h) := rfl

  definition id : bijection A :=
  bijection.mk id id (compose.left_id id) (compose.left_id id)

  lemma id.left_id (f : bijection A) : id ∘b f = f :=
  bijection.rec_on f (λx x x x, rfl)

  lemma id.right_id (f : bijection A) : f ∘b id = f :=
  bijection.rec_on f (λx x x x, rfl)

  definition inv (f : bijection A) : bijection A :=
  bijection.mk
    (finv f)
    (func f)
    (rinv f)
    (linv f)

  lemma inv.linv (f : bijection A) : inv f ∘b f = id := -- ERROR
  bijection.rec_on f (λfunc finv linv rinv, by rewrite [↑inv, ↑compose, linv])
end bijection
```

```
type mismatch at application
  eq.symm linv
term
  linv
has type
  finv ∘ func = function.id
but is expected to have type
  x = function.id (lean-checker)
```

**Comment by leodemoura** [comment]
Thanks for reporting the problem, and trying Lean.

You are correct, the `rewrite` tactic is producing a type incorrect term.
It is not checking for dependencies. 
When we rewrite using `linv`:

``` lean
linv : finv ∘ func = id
```

The rewrite tactic is blindly replacing occurrences of `finv ∘ func` with `id` and ignoring dependencies.
This is problematic in your example because after we expand `inv` and `compose`, we have subterms such as

```
(@eq.symm (A → A) (finv ∘ func) (@function.id A) linv)
```

If we replace `finv ∘ func` with `id` in the term above, we get a type incorrect term.
That being said, we will add extra checks to the rewrite tactic, and it will fail in your example.
The lemma will still be refused, but at least the error message will be better.
One trick to prove the lemma is to generalize the rinv and linv subterms of compose.
Here is the revised file. I also defined to auxiliary lemmas for simplifying the definition `compose`.
The idea is to have a "name" for the subterms we want to generalize.

``` lean
structure bijection (A : Type) :=
(func finv : A → A)
(linv : finv ∘ func = id)
(rinv : func ∘ finv = id)

attribute bijection.func [coercion]

namespace bijection
  variable {A : Type}

  lemma compose_linv (f g : bijection A) : (finv g ∘ finv f) ∘ func f ∘ func g = id :=
  by rewrite [compose.assoc, -{finv f ∘ _}compose.assoc, linv f, compose.left_id, linv g]

  lemma compose_rinv (f g : bijection A) : (func f ∘ func g) ∘ finv g ∘ finv f = id :=
  by rewrite [-compose.assoc, {_ ∘ finv g}compose.assoc, rinv g, compose.right_id, rinv f]

  definition compose (f g : bijection A) : bijection A :=
  bijection.mk
    (f ∘ g)
    (finv g ∘ finv f)
    (compose_linv f g)
    (compose_rinv f g)

  infixr `∘b`:100 := compose

  lemma compose.assoc (f g h : bijection A) : (f ∘b g) ∘b h = f ∘b (g ∘b h) := rfl

  definition id : bijection A :=
  bijection.mk id id (compose.left_id id) (compose.left_id id)

  lemma id.left_id (f : bijection A) : id ∘b f = f :=
  bijection.rec_on f (λx x x x, rfl)

  lemma id.right_id (f : bijection A) : f ∘b id = f :=
  bijection.rec_on f (λx x x x, rfl)

  definition inv (f : bijection A) : bijection A :=
  bijection.mk
    (finv f)
    (func f)
    (rinv f)
    (linv f)

  lemma inv.linv (f : bijection A) : inv f ∘b f = id :=
  bijection.rec_on f (λfunc finv linv rinv,
    begin
      esimp [inv, compose],
      generalize (compose_linv (mk finv func rinv linv) (mk func finv linv rinv)),
      generalize (compose_rinv (mk finv func rinv linv) (mk func finv linv rinv)),
      esimp, rewrite linv, intros, esimp
    end)

  lemma inv.rinv (f : bijection A) : f ∘b inv f = id :=
  bijection.rec_on f (λfunc finv linv rinv,
    begin
      esimp [inv, compose],
      generalize (compose_linv (mk func finv linv rinv) (mk finv func rinv linv)),
      generalize (compose_rinv (mk func finv linv rinv) (mk finv func rinv linv)),
      esimp, rewrite rinv, intros, esimp
    end)

end bijection
```

**Comment by avigad** [comment]
Dear Sebastian,

Let me add just a few more words of explanation. Dealing with equalities and dependent types is the dark side of type theory. The issues can be subtle and confusing. The problem is that in the goal

``` lean
  mk (finv ∘ func) (finv ∘ func) ... ... = mk function.id function.id ... ...
```

the "..." expressions are actually proofs of propositions that depend on the arguments shown, which is to say, they are terms whose types involve those arguments. If you replace, say, "finv ∘ func" by "function.id" in the first argument on the left-hand side, the expression no longer type checks -- the later arguments to "mk" don't match the earlier ones.

Leo's solution was to generalize the expressions over the later arguments, so that you are proving
"forall rinv, forall linv, ...". Then the substitution replaces finv ∘ func /and/ changes the type of the universal quantifier, all at the same time.

To make the proof easier to understand, I broke out a helper lemma, bijection.eq, which says that to show two bijections are equal, it is enough to show that the function parts are equal. 

``` lean
  protected theorem eq {f g : bijection A}
    (func_eq : func f = func g) (finv_eq : finv f = finv g) : f = g :=
  begin
    revert finv_eq,
    revert func_eq,
    cases g with [gfunc, gfinv, glinv, grinv],
    cases f with [ffunc, ffinv, flinv, frinv],
    esimp,
    intros [func_eq, finv_eq],
    revert grinv, revert glinv, revert frinv, revert flinv,
    rewrite [func_eq, finv_eq],
    intros [H1, H2, H3, H4],
    apply rfl
  end
```

The proof follows the same strategy. "revert" puts the hypotheses back in the goal; "cases" breaks down g and f to the components. After introducing the hypotheses, the next "revert" does the key generalization; after that, when you apply the rewrite, it makes the substitution everywhere and things stay type correct, and the goal is essentially of the form x = x.

With this helper lemma, the proof is easy:

``` lean
  lemma inv.linv (f : bijection A) : inv f ∘b f = id :=
  eq !linv !linv
```

Eventually we will add a section to the tutorial explaining these issues better. We might also be able to automate the generation of these helper lemmas.

Two more (small) things. First, I would suggest generalizing your definition to bijections between two types, A and B. (So we have f : bijection A B, and your file is the special case f : bijection A A).

Also, note that in the current version of the repository, there is a theory of bijections between subsets of a type.

  https://github.com/leanprover/lean/tree/master/library/data/set

There isn't a version that bundles together the function and the inverse though, as you do -- that is a good idea. It is used in the homotopy type theory library:

  https://github.com/leanprover/lean/blob/master/hott/init/equiv.hlean
  https://github.com/leanprover/lean/blob/master/hott/types/equiv.hlean

Best wishes,

Jeremy

**Comment by fpvandoorn** [comment]
Here is another proof, which uses [a general theorem](https://github.com/leanprover/lean/blob/master/library/logic/cast.lean#L150-L153) to prove that two dependent function applications are equal:

``` lean
  open eq.ops
  lemma inv.linv (f : bijection A) : inv f ∘b f = id :=
  dcongr_arg4 bijection.mk !linv (!eq.rec_on_constant ⬝ !linv) rfl rfl
```

**Comment by fpvandoorn** [comment]
@avigad: Two small remarks on your proof:
- You can use `cases` without using `revert` first;
- The `reverts` command does multiple reverts at once.

Then the proof becomes like this.

``` lean
  protected theorem eq {f g : bijection A}
    (func_eq : func f = func g) (finv_eq : finv f = finv g) : f = g :=
  begin
    cases g with [gfunc, gfinv, glinv, grinv],
    cases f with [ffunc, ffinv, flinv, frinv],
    esimp at *,
    reverts [flinv, frinv, glinv, grinv],
    rewrite [func_eq, finv_eq],
    intros [H1, H2, H3, H4],
    apply rfl
  end
```
