### ISSUE TITLE
Weird behavior with implicitly quantified definitions 

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#552]
The following code:

```
import standard data.set

definition needs_explicit_args (m : nat) := ∀ {n:nat}, set.univ n → true
lemma takes_needs_explicit_args : ∀ {m : nat}, needs_explicit_args m → false := sorry
lemma cannot_state_type : ∀ {m : nat}, needs_explicit_args m → false :=
  take m (H : needs_explicit_args m), takes_needs_explicit_args H
```

gives a type mismatch error, claiming that 'H' has type 

```
set.univ ?M_2 -> true
```

instead of type

```
needs_explicit_args ?M_1
```

However, the same code snippet works if I don't state the type of 'H' in 'take':

```
import standard data.set

definition needs_explicit_args (m : nat) := ∀ {n:nat}, set.univ n → true
lemma takes_needs_explicit_args : ∀ {m : nat}, needs_explicit_args m → false := sorry
lemma cannot_state_type : ∀ {m : nat}, needs_explicit_args m → false :=
  take m H, takes_needs_explicit_args H
```

System details:
- Ubuntu 14.10
- Installed by following instructions at: https://leanprover.github.io/download/ubuntu14inst
- Upgraded moments ago

**Comment by fpvandoorn** [comment]
In your example, the type of `H` is `needs_explicit_args m` which is definitionally `∀ {n:nat}, set.univ n → true`. This means that the first argument of `H` is implicit, hence `H` is treated as `@H _`. This is the case because implicit arguments in Lean are _maximally inserted_, see also [section 2.7.2 of the Coq reference manual on this](https://coq.inria.fr/refman/Reference-Manual004.html#sec107) (@avigad: does our tutorial already mention this?). If you don't want this to happen, you can replace `H` by `@H`. So the following example works:

``` lean
import standard data.set

definition needs_explicit_args (m : nat) := ∀ {n:nat}, set.univ n → true
lemma takes_needs_explicit_args : ∀ {m : nat}, needs_explicit_args m → false := sorry
lemma cannot_state_type : ∀ {m : nat}, needs_explicit_args m → false :=
  take m (H : needs_explicit_args m), takes_needs_explicit_args @H
```

If you don't want to have arguments maximally inserted for the definition `needs_explicit_args`, you can change the definition to

``` lean
definition needs_explicit_args (m : nat) := ∀ ⦃n:nat⦄, set.univ n → true
```

(note: `⦃` and `⦄` are inserted by `\{{` and `\}}`, and can alternatively be written as `{{` and `}}`). 
This means that the implicit argument `n : nat` will only be inserted to `H : needs_explicit_args m` if `H` is applied to something. So in this case `H` will be treated as `@H`, but `H x` will be treated as `@H _ x`.

---

The fact that your second example does work is "accidental". The reason is that implicit arguments are inserted during "pre-processing", before the term is actually elaborated. In the second example, the pre-processor doesn't have enough information about the type of `H`, so it doesn't insert an implicit argument to `H`. In this case, this is what you want, so that is why it works.

**Comment by dselsam** [comment]
Thank you very much. The first part of your explanation makes perfect sense, and {{n:nat}} is exactly what I was looking for. I am not sure I understand the intuition for or the implications of the second part though (for what it is worth).

**Comment by leodemoura** [comment]
Let me try to clarify the second part. In Lean, we can annotate declarations with annotations such as `{ }`, `[ ]` and `⦃  ⦄`. These annotations are used by Lean to decide whether it needs to include an implicit `_` or not. In your first example, `H` has type `∀ {n:nat}, set.univ n → true`. Thus any occurrence of `H` is replaced with `H _`.  In the second example, at pre-processing time, the type of `H` is not known. 

``` lean
take m H, takes_needs_explicit_args H
```

The term above is equivalent to

``` lean
take (m : _) (H : _), takes_needs_explicit_args H
```

Consequently, there is no annotation associated with it, and `H` is _not_ replaced with `H _`.
This may feel weird because after Lean starts propagating typing constraints, it will eventually find out that `H` has type `∀ {n:nat}, set.univ n → true`. 
Another way to view is this: only explicit annotations are considered by Lean when adding implicit `_`'s. Inferred annotations are not taken into account.

**Comment by dselsam** [comment]
This makes perfect sense. Thank you very much for the clarification.
