### ISSUE TITLE
Tutorial insufficient for quantifiers

### ISSUE THREAD

**Issue by fspeech** [leanprover/lean3#560]
In one of the examples at the end of chapter 4 one is asked to prove:

```
(∀x, p x) ↔ ¬(∃x, ¬p x)
```

In the reverse direction we need to prove:

```
¬(∃x, ¬p x) → (∀x, p x)
```

However the techniques introduced leading up to it seems insufficient to prove this.  I don't doubt that one can prove it in Lean, just that there is no information in the tutorial (or my crude understanding of the library code) on how negations of quantifiers relate to each other.

**Comment by leodemoura** [comment]
Thanks for the feedback.
One of the goals of the exercise is to make the reader realize that the reverse direction requires classical reasoning. In the tutorial, we hint that some of the exercises require the law of the excluded middle, but we do not describe it in this chapter. 
One idea is to include it explicitly in the exercise.
Example

``` lean
axiom em (p : Prop) : p ∨ ¬ p
```

Then, a solution would be:

``` lean
theorem forall_not_of_not_exists {A : Type} {p : A → Prop} : (¬∃x, ¬ p x) → (∀x, p x) :=
assume nex, take x,
  or.elim (em (p x))
    (assume px : p x,    px)
    (assume npx : ¬ p x, absurd (exists.intro x npx) nex)
```

**Comment by avigad** [comment]
Another option is to use a proof by contradiction, as described in Section 3.5. The natural way to start the proof is to assume the hypothesis, let `x` be arbitrary, and try to show `p x`. You seem to be stuc, but because the text starts with `import classical`, you have a last resort: assume `¬ p x` and derive a contradiction. The following proof works.

``` lean
import classical

variables (A : Type) (p : A → Prop)

example : ¬ (∃x, ¬ p x) → ∀x, p x :=
assume H : ¬ ∃x, ¬ p x,
take x,
show p x, from
  by_contradiction
    (assume H1 : ¬ p x,
      have H2  : ∃x, ¬ p x, from exists.intro x H1,
      show false, from H H2) 
```

**Comment by fspeech** [comment]
Hi Dr DeMoura and Prof Avigad,
Thanks for the quick responses! I was aware of the need of em (as is pointed out in the tutorial). What I had trouble with was how to break apart `(∀x, p x)` as I naively tried `em (∀x, p x)` and was stuck. Now I see that I should do abstraction `take x` first. I guess I haven't quite mastered the connection between `λx, p x` and `(∀x, p x)` yet. Feel free to close the issue as this is not the fault of the tutorial.
I am really learning a lot from the tutorial. Thanks for a great tool and the great learning experience.

**Comment by fspeech** [comment]
If I may suggest, it would be great to have more guidance in the tutorial on how to combine negation with quantifiers. I find the interaction of negation with quantifiers rather challenging, for example the next example in the tutorial:

```
  lemma not_exists_all : ¬(∃x, p x) → (∀x, ¬p x) :=
    assume nex, take x,
        or.elim (em (p x))
            (assume px : p x, absurd (exists.intro x px) nex)
            (λnpx, npx)
  example : (∃x, p x) ↔ ¬(∀x, ¬p x) :=
    iff.intro
        (assume H : (∃x, p x),
            obtain x px, from H,
                not.intro
                    (assume Hnp : (∀x, ¬p x), absurd px (Hnp x)))
        (assume Hnnp : ¬(∀x, ¬p x),
            or.elim (em (∃x, p x))
                (λh, h)
                (assume Hnep : ¬(∃x, p x), 
                    absurd (!not_exists_all Hnep) Hnnp))
```

I had to use a lemma. I don't know if this is idiomatic or it can be simplified.

**Comment by avigad** [comment]
Thanks for the suggestion. Indeed, it would be helpful to add an example of how to use the quantifiers classically. I will do this within the next day or two. 

The proof you have that `¬(∀x, ¬p x)` implies `(∃x, p x)` is, indeed, fairly canonical. You could in-line the lemma in the proof, and, as above, you could use proof by contradiction instead of excluded middle, but it basically comes to the same thing. Well done!

In the future, could you post tutorial issues on the github site for the tutorial?

  https://github.com/leanprover/tutorial

That will make it easier to track them.

**Comment by fspeech** [comment]
Oops. I failed to notice that the tutorial has its own repo. Sorry about that. I will close this ticket now.
