### ISSUE TITLE
Bug in tutorial software (checked against Emacs/native Lean)

### ISSUE THREAD

**Issue by fspeech** [leanprover/lean3#561]
If I run

```
check (∀x, p x → r) ↔ (∃x, p x) → r
```

I get this type:

```
(∀x, p x → r) ↔ ∃ (x : A), p x → r
```

instead. Sorry I couldn't capture the exact output. (Is there an option to print to console instead of getting a floating info frame? I don't know how to copy from the result frame).
This looks wrong to me. So I thought I proved the following 

```
  example : (∀x, p x → r) ↔ (∃x, p x) → r :=
    iff.intro
        (assume (H : (∀x, p x → r)) (Hep : (∃x, p x)),
            obtain x Hpx, from Hep, H x Hpx)
        (assume (H : (∃x, p x) → r),
            take x, assume px : p x,
                H (exists.intro x px))
```

but the web version won't accept it, as the type checking would indicate.
I checked that the native Lean running through Emacs does not have this bug:

```
(∀ (x : A), p x → r) ↔ (∃ (x : A), p x) → r : Prop
```

**Comment by fspeech** [comment]
Similar problem for universal quantifier for the web version:

```
check (∃x, p x → r) ↔ (∀x, p x) → r
```

**Comment by fspeech** [comment]
Prof. Avigad,
Does this mean that the CMU 15-815 students did't do their week 3 homework assignments? Just kidding :-) I am also very impressed with week 11 assignment (# 9), for some reason I supposed it to be the whole HoTT book (with emphasis on some chapters). Is this an undergrad or graduate student class?

**Comment by avigad** [comment]
Thanks for catching this. Very recently, @fpvandoorn changed the binding strength of <-> so that it binds less tightly than -> (a common convention), and added these examples to the tutorial. There is a lag before the most recent version of Lean makes it to the tutorial system, however, which is what is causing the problem. It should be corrected next time the tutorial system is rebuilt. @leodemoura, when does this happen?

The seminar (which just ended yesterday) was a graduate level seminar, but undergraduates could take it as well (and a few did).

**Comment by leodemoura** [comment]
> @leodemoura, when does this happen?

Unfortunately, this is not automated yet. The web version and the Ubuntu PPA are updated manually from time to time. We should have it on Monday.

**Comment by leodemoura** [comment]
The web version has been updated.
