### ISSUE TITLE
iota reduction fails

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#563]
In [this file](https://github.com/fpvandoorn/lean/blob/issue562/hott/test.hlean) on [this branch](https://github.com/fpvandoorn/lean/tree/issue562) I have two examples where my goal is of the form `eq.rec (refl _) (refl _) = sorry` (+ some implicit arguments). The first one reduces to `refl _ = sorry`, as expected, however, the second one doesn't. Calling `esimp` doesn't reduce the `eq.rec`.

The first example is a copy of the goal of the second example, although I don't know whether the implicit arguments are inferred in the way they are in the second goal (probably not). However, in any case, the second goal should reduce to `refl _ = sorry`. Also, if I replace [`sorry`](https://github.com/fpvandoorn/lean/blob/issue562/hott/test.hlean#L200) in the second example by `idp`, the goal _does_ get solved by `esimp`.

Sorry for the huge terms in the file (but it's mostly bad since I copy-pasted _all_ implicit arguments).

**Comment by leodemoura** [comment]
This is one is really tricky. 
Remark 1: for parametric inductive datatypes, the kernel only applies iota IF the parameters of the eliminator/recursor are definitionally equal to the parameters of the constructor. 
This check is performed in the following place:
https://github.com/leanprover/lean/blob/master/src/kernel/inductive/inductive.cpp#L924-L932
That is, the term

``` lean
  @eq.rec A a C H b (@eq.refl A1 a1) 
```

will only be iota reduced if `A` is definitionally equal to `A1` and `a` to `a1`.

Remark 2: when we are executing `esimp`, we treat most constants as opaque.
That is, we use a custom normalizer, and it may affect the check above.

Remark 3: when `esimp` is executed in your example, the iota reduction fails because it cannot establish that the following two terms are definitionally equal:

``` lean
seg1 ▹ rec2 Pbase (seg1 ▹ Pbase) (refl (seg1 ▹ Pbase))
  (tr_eq_of_eq_inv_tr P (eq.rec Ploop⁻¹ (tr_con P seg1 seg2⁻¹ Pbase)))
  base1
```

and

``` lean
seg1 ▹ Pbase
```

Question: are these two terms definitionally equal?
My current conjecture is that `esimp` fails to establish that because it is using a custom normalizer that treats most constants as opaque. Does this sound reasonable?

I think the easy solution is to remove the extra check in the iota reduction:
https://github.com/leanprover/lean/blob/master/src/kernel/inductive/inductive.cpp#L924-L932

We will be able to reduce type incorrect terms, but I don't think this is a big deal. 
We should not trust any result produced by the normalizer if we do not type check the input term.

Another issue: in the past, when the elaborator was more brittle, by performing the extra definitional equality tests, we could elaborate more terms. Note that, the additional checks may produce unification constraints when the parameters contain metavariables. 
This is not the case anymore. Even if we disable the extra checks, we can still compile the whole library.

**Comment by fpvandoorn** [comment]
> Question: are these two terms definitionally equal?

Yes, these two terms are definitionally equal. `rec2 a b c d base1` reduces to `a`. However, this requires unfolding of `rec2` and `base1` (and a tower of other recursors and constructors, until it reaches `type_quotient.rec` and `class_of`). Some of these recursors are not reducible (but maybe they should be), so it sounds reasonable that `esimp` cannot establish this definitional equality.

> I think the easy solution is to remove the extra check in the iota reduction:

It sounds a bit dangerous. Do we always type check terms before we normalize them? In that case I guess it is fine.

**Comment by leodemoura** [comment]
> It sounds a bit dangerous. Do we always type check terms before we normalize them? 

At the final type check step (i.e., when we try to add a fully elaborated declaration to kernel), the answer is yes, we only try to normalize type correct terms.

However, I'm not sure whether this is true at elaboration time when we are executing tactics and the higher order unifier. I will investigate that. By removing the check, we do not introduce unsoundness, but we may observe counter-intuitive behavior (e.g., the elaborator or tactics failing for some bizarre reason). 

Anyway, your example demonstrates that the current approach is producing bizarre behavior. 

I'll remove the check, at least, we are fixing a known problem.
If we find problems in the elaborator/tactics in the future because of the missing check, we can fix by explicitly type checking before normalizing.

**Comment by fpvandoorn** [comment]
Ok. That sounds good!
