### ISSUE TITLE
rewrite with iff

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#579]
I'm porting some files from the standard library to the HoTT library, and I am confused about the following example in `algebra.ring`:

``` lean
  theorem mul_add_eq_mul_add_iff_sub_mul_add_eq : a * e + c = b * e + d ↔ (a - b) * e + c = d :=
  calc
    a * e + c = b * e + d ↔ a * e + c = d + b * e : by rewrite {b*e+_}add.comm
      ... ↔ a * e + c - b * e = d : iff.symm !sub_eq_iff_eq_add
      ... ↔ a * e - b * e + c = d : by rewrite sub_add_eq_add_sub
      ... ↔ (a - b) * e + c = d   : by rewrite mul_sub_right_distrib
```

How does this work in the standard library? Does `rewrite` know about `iff.refl`? It doesn't work in the HoTT library. Is this because of a difference in `rewrite` between the libraries, or just because we didn't set some rewrite/calc hint in HoTT? [Here](https://github.com/fpvandoorn/lean/blob/80e0ba01bf8c04438b60946a5f90dfb401e210ef/hott/algebra/ring.hlean#L217) is the branch where it fails.

**Comment by leodemoura** [comment]
Quick comment: the standard library has `subst` for `iff`.
https://github.com/leanprover/lean/blob/master/library/logic/instances.lean#L84-L90

It is very inefficient, and will be deleted in the future. 
It is based on an experiment Jeremy and I performed last summer.

**Comment by leodemoura** [comment]
I analyzed the example, it is not used the `subst` for `iff`.
It applies the `iff.refl` here:
https://github.com/leanprover/lean/blob/master/src/library/tactic/rewrite_tactic.cpp#L1394-L1397
This should not be hard coded. I will use the new `reflexivity` tactic instead.

**Comment by leodemoura** [comment]
I made the modification
https://github.com/leanprover/lean/commit/84deddcca96779d1fd26da498bff2d63ae7105b7

Now, after a rewrite, the `reflexivity` tactic is applied (if the goal does not have metavariables). 
So, the theorem should work for HoTT mode since we have 
https://github.com/leanprover/lean/blob/master/hott/init/logic.hlean#L187-L189

The condition "if the goal does not have metavariables" is needed to prevent reflexivity from being applied to goals of the form

``` lean
... |- ?M = t
```

It turns out, this happens quite often in the HoTT library where `apply concat` is used quite often.

**Comment by fpvandoorn** [comment]
Great! My original example now works.

I think the change to apply `reflexivity` is good, including the no-metavariable-requirement.
