### ISSUE TITLE
implicit variable that only appears in tactics don't show up on the argument list

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#595]
I have a section variable of type Prop. I found that if I only use the variable in a tactic, it does not get added to the argument list of the definition/lemma. I don't know if this is a known issue or this is by design.

**Comment by avigad** [comment]
I am pretty sure this is expected. There are subtle interplays between the preprocessing phase, the elaboration phase, and tactics, that make things hard. (See the paper on the elaborator here: http://leanprover.github.io/files/constr.pdf.) If I understand correctly, the issue here is that variables have to be added fairly early, in a preprocessing phase, while tactics are called (and their arguments analysed and made sense of) relatively late in the game.

The easy workaround is to manually include the thing you need. All of the following work. In my opinion, "using" is the most elegant solution.

``` lean
variable P : Prop
premise H : P

theorem foo : P := H

section
include H
theorem foo2 : P := by apply H
end

theorem foo3 : P := 
using H, 
begin
  apply H
end

theorem foo4 : P := 
using H, by apply H

theorem foo5 : P := 
have H' : _, from H,
begin
  apply H
end

theorem foo6 : P := 
let G := H in
begin
  apply H
end
```

**Comment by htzh** [comment]
Makes sense.
