### ISSUE TITLE
print notation gives wrong output

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#604]
``` lean
print notation dec_trivial
```

Output: ``dec_trivial`:1024 := of_is_true`
Expected output: ``dec_trivial`:1024 := of_is_true trivial`
(same with `print` command)

**Comment by leodemoura** [comment]
Good catch. The notation stores "pre terms", that is, terms before elaboration, but the pretty printer expects fully elaborated terms. Note that, "pre terms" are usually not even type correct.
For example, the type of `of_is_true` is

``` lean
of_is_true : ∀ {c : Prop} [H₁ : decidable c], is_true c → c
```

The pre-term `of_is_true trivial` is a unary function application. This is why the `trivial` disappeared. The pretty printer is assuming it is the first implicit argument of `of_is_true` :-(

The fix is clear: we should be able to pretty print "pre-terms".

**Comment by fpvandoorn** [comment]
Yes, I already thought it had something to do with the fact that `dec_trivial` isn't type-correct on its own. `dec_trivial` a nice trick, but it is also confusing (as review 1 indicates).

**Comment by leodemoura** [comment]
> Yes, I already thought it had something to do with the fact that dec_trivial isn't type-correct on its own. dec_trivial a nice trick, but it is also confusing (as review 1 indicates).

Regarding `dec_trivial` being confusing, if one doesn't care how it works, it is quite simple: it is just running the decision procedure. Note that it is much simpler than tactics such as `cases`. 
I think the problem in the paper is that `dec_trivial` is used but not explained in detail.
This was really unfortunate. If we have explained the `of_is_true` and `is_true` definitions, then everything would be clear.

More confusion was generated by the fact that, as a last resort, we allow type class resolution to run even when there are unassigned meta-variables in the type. This may produce non-termination.
We have this "last resort" heuristic because we want to avoid unnecessary annotations in theorems such as:

``` lean
theorem inv_one : 1⁻¹ = 1  := 
```

Without it, we would have to write `1⁻¹ = @has_one.one A s` instead of `1⁻¹ = 1`.

This "last resort" heuristic is also contradicting what we said in the paper: type class resolution is only fired when all meta-variables in the type have being assigned. Well, this is not totally true, there are exceptions.

My plan is to revise the type class resolution procedure:
1- Allow users to specify which arguments must be fully elaborated before invoking type class resolution.
2- Allow users to specify whether the last resort heuristic above should be used or not.
As far as I can see, this heuristic is only useful when using type classes to implement polymorphism.

By default, all arguments must be fully elaborated, and the last resort heuristic is not used.
The default would prevent the non-termination when executing.

```
check dec_trivial
```

**Comment by fpvandoorn** [comment]
> Without it, we would have to write `1⁻¹ = @has_one.one A s` instead of `1⁻¹ = 1`.

I wouldn't mind if we're required to write `1⁻¹ = (1 : A)` for these theorems.

But an option whether to use the last resort heuristic is even better.

**Comment by leodemoura** [comment]
> I wouldn't mind if we're required to write 1⁻¹ = (1 : A) for these theorems.

This is a good point, `1⁻¹ = (1 : A)` is quite reasonable.

**Comment by leodemoura** [comment]
@fpvandoorn I disabled the "last resort heuristic". I took way longer than I expected. I thought it would be a 5 min change. It took a couple of hours to fix the libraries.

The most counter intuitive fix was this one:

``` lean
protected definition ID {C D : Category} (F : functor C D) : natural_transformation F F := natural_transformation.id
```

The reason: `id` is overloaded, and since `id` is protected, `id` doesn't mean `natural_transformation.id` in the namespace `natural_transformation`. 
I have to investigate more what is going on.

**Comment by leodemoura** [comment]
@avigad @rlewis1988 @javra 
The elimination of the "last resort heuristic" (described in this thread) is an significant change. 
It makes Lean more predictable since type class resolution is never executed if the type still has meta-variables. However, it broke many files. 
See the affected files in the following commit to get an idea of the effects of this change:
https://github.com/leanprover/lean/commit/19361f01965920d2d1ba665b8d86ec900ab06453

If it is too inconvenient, we can add the following option that Floris and I discussed in this thread.

> 2- Allow users to specify whether the last resort heuristic should be used or not.

**Comment by fpvandoorn** [comment]
That required indeed more changes than I expected.

> The most counter intuitive fix was this one:

Interesting that it's different in `nat_trans` in the HoTT library.
Can you remind me how `protected` identifiers work if the corresponding namespace is opened? Is it right that they are only available in shortened form if they are declared in the current (occurrence of the) namespace?

``` lean
namespace bla
protected definition bar := @eq
check bar -- this works
end bla

namespace bla
-- check bar -- this fails
end bla
```

So I think `id` also means `natural_transformation.id`, but the overload `category.id` causes it to fail for some mysterious reason so that `natural_transformation.id` is not even tried.

**Comment by avigad** [comment]
Like Floris, I don't mind annotating 1 and ∅ in statements like 1⁻¹ = 1. Things like this come up occasionally in the library, but in most ordinary contexts there is enough information to infer the type. Most of the other changes are in category theory -- if Floris is happy with those, then all is good.

**Comment by leodemoura** [comment]
@fpvandoorn both `check`s in your example should fail. The first one is a bug, it should also produce an error.
When we discussed the semantics of `protected`, we have decided that the last prefix is never eliminated. For example, `foo.bla.boo` should never be shortened to `boo`. The shortest version should be `bla.boo`.

So, the `natural_transformation` file was only working because of a bug in the way we handle `protected`. 

> Interesting that it's different in nat_trans in the HoTT library. 

I took a quick look in the HoTT library, and I found several `nat_trans.id` instead of just `id`.

**Comment by leodemoura** [comment]
@fpvandoorn  I fixed the problem with `protected`, but the result is not nice. I had to perform many modifications in the library (btw, I did not finish fixing it since I did not really like the result)
https://github.com/leodemoura/lean/commit/72fa3c6371e35afd061b1da8645075d63ea1a13d

I think we should revise how `protected` behaves. The issue is: should we allow `foo.bla.boo` to be shortened to `boo` inside of the namespace `foo.bla`?
For me, the main issue is consistent behavior. That is, both `check`s in your example should fail or both should succeed.

``` lean
namespace bla
protected definition bar := @eq
check bar -- this works
end bla

namespace bla
check bar -- this fails
end bla
```

@avigad any thoughts?
Do you remember why we wanted to force the user to write `nat.rec_on` instead of `rec_on` in the `nat` namespace? I recall a discussion along these lines, but I don't remember the details anymore. I will check my mailbox.

**Comment by leodemoura** [comment]
I found the thread where we discuss how `protected` should behave:
https://github.com/leanprover/lean/issues/426

**Comment by leodemoura** [comment]
Here is the rest of the fix:
https://github.com/leodemoura/lean/commit/436e405317c7e0335d1a154691b9268adb9157f4

Note that this one also contains many weird changes. For example, the definition 

``` lean
definition arrow (ob : Type) (C : category ob) : category (category.arrow_obs ob C) :=
  mk (λa b, category.arrow_hom a b)
     (λ a b c g f, sigma.mk (category.hom_src g ∘ category.hom_src f) (sigma.mk (category.hom_dst g ∘ category.hom_dst f)
        (show category.to_hom c ∘ (category.hom_src g ∘ category.hom_src f) = (category.hom_dst g ∘ category.hom_dst f) ∘ category.to_hom a,
         proof
         calc
         category.to_hom c ∘ (category.hom_src g ∘ category.hom_src f) = (category.to_hom c ∘ category.hom_src g) ∘ category.hom_src f : by rewrite assoc
           ... = (category.hom_dst g ∘ category.to_hom b) ∘ category.hom_src f                     : by rewrite category.commute
           ... = category.hom_dst g ∘ (category.to_hom b ∘ category.hom_src f)                     : by rewrite assoc
           ... = category.hom_dst g ∘ (category.hom_dst f ∘ category.to_hom a)                     : by rewrite category.commute
           ... = (category.hom_dst g ∘ category.hom_dst f) ∘ category.to_hom a                     : by rewrite assoc
         qed)
       ))
     (λ a, sigma.mk id (sigma.mk id (!id_right ⬝ (symm !id_left))))
     (λ a b c d h g f, ndtrip_eq    !assoc    !assoc    !proof_irrel)
     (λ a b f,         ndtrip_equal !id_left  !id_left  !proof_irrel)
     (λ a b f,         ndtrip_equal !id_right !id_right !proof_irrel)
```

is much more verbose after the fix.

**Comment by leodemoura** [comment]
I created a separate issue for discussing `protected`.
