### ISSUE TITLE
consistent behavior for `protected` declarations

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#609]
This issue started at #604

Here is the problem

``` lean
namespace bla
protected definition bar := @eq
check bar -- this works
end bla

namespace bla
check bar -- this fails
end bla
```

The following commits try to fix this issue by making both `check`s fail.
https://github.com/leodemoura/lean/commit/72fa3c6371e35afd061b1da8645075d63ea1a13d
https://github.com/leodemoura/lean/commit/436e405317c7e0335d1a154691b9268adb9157f4
The fix is consistent with the behavior discussed at #426 

Remaining issue: the fix makes some definitions quite verbose.

Alternative fix: both `check`s in the example above succeed. 
The alternative fix reduces verbosity, but it is has the problems discussed at #426

**Comment by leodemoura** [comment]
@fpvandoorn @avigad what do you think?

**Comment by fpvandoorn** [comment]
Some time after the discussion in #426 I realized that I could still often use the shortened form of a protected definition inside the namespace in which it was declared, and I liked how it shortened things (which is why you had to modify a lot of my recent files in your mentioned commits).

So in that sense I would allow both `checks` in the above example.

However, if we do this, the main problem is with overloading. Suppose we have the theorem

``` lean
namespace nat
protected definition inhabited : inhabited nat 
end nat
```

Maybe this is a bad name for this theorem. However, because of the fact that we protect it, it looks like it will be fine. And I think there are examples in the libraries where a protected definition has the same name as a commonly used identifier which either lives in the root namespace or a commonly opened namespace.

So in this example, if we are in the namespace `nat`, what do we mean by `inhabited`? There are three options:
1. We mean `nat.inhabited`: this is bad, because there is no good way to write `inhabited` at the root namespace (writing `_root_.inhabited` is not nice)
2. We mean `_root_.inhabited`: this is strange because all protected definitions in `nat` are available, except `nat.inhabited`, because it is overloaded. Additionally this means that opening a namespace halfway in the file can hide `nat.inhabited`, which is confusing.
3. `inhabited` and `nat.inhabited` are overloaded. This is also not nice: maybe `inhabited` is used a lot in the file, while `nat.inhabited` is never used. This can cause an unnecessary extra strain on the unifier. And there is not even the workaround of using `namespace nat (hiding inhabited)`.

Of these three options I like 2 best: it allows the user to shorten protected definitions almost always, except in the problematic cases. But it is super confusing. An additional confusion point is that `open nat` and `namespace nat` lead to different behavior about whether protected definitions are available in short form (even without any overloading).

So if we didn't have to support overloading, I would accept both `check`s. However, any decision we make with overloaded identifiers is a mess if we do this (unless I'm missing a 4th case which is convenient).

All in all I think it would be best to make both `check`s fail, and let us write the long definition name. If we wanted a shorter name, we shouldn't have protected the definition. It is definitely easiest to explain. I'm also fine with (and maybe secretly hope for) option 2, which allows shortening names almost always, but it is confusing.

**Comment by fpvandoorn** [comment]
In response to the super verbose `arrow` definition in [this comment](https://github.com/leanprover/lean/issues/604#issuecomment-103296967): note that the category folder in the standard library is outdated. Once we have a decent HoTT category library, we should port it to the standard library. I would change a lot about the [`arrow` section](https://github.com/leanprover/lean/blob/master/library/algebra/category/constructions.lean#L308-364) in that file: `arrow_obs` and `arrow_hom` should be structures, and none of these definitions should be protected (and maybe `src` and `dst` should be renamed `source` and `target` or something).

**Comment by avigad** [comment]
No strong opinions here. It seems cleanest and clearest just to keep protected definitions protected even in the namespace. We can always write

namespace foo
protected definition bar : ...
local abbreviation bar := foo.bar

in cases where we want to write foo.bar instead of bar even in the namespace.

**Comment by leodemoura** [comment]
Thanks for the feedback.
I will move the commits to the main branch.
