### ISSUE TITLE
wrong tokens underlined by flycheck

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#626]
In the following example, the wrong tokens are underlined by flycheck

``` lean
-- HoTT
import hit.circle
open circle

definition f (x : S¹) : bool := circle.rec_on x _ _
-- underlinings:             ^^               ^ ^
-- expected underlinings:       ^^^^^^^^^^^^^   ^ ^
```

These two definitions work as expected:

``` lean
import hit.circle
open circle

-- adding a newline:
definition f (x : S¹) : bool := 
circle.rec_on x _ _
-- changing S¹ to circle:
definition f (x : circle) : bool := circle.rec_on x _ _
```

**Comment by leodemoura** [comment]
@soonhokong This is a bug in the Lean scanner. It is producing incorrect column numbers when the superscripts 1, 2 or 3 are used. I'm still investigating, but it seems the problem is that these superscripts are not in the range we are currently checking. See the following table
![image](https://cloud.githubusercontent.com/assets/2778936/7816297/3ec6d1b2-0382-11e5-8cc2-7ba518b7a7a1.png)

**Comment by soonhokong** [comment]
@leodemoura, thank you for the clarification. Please let me know if you need a fix on emacs side as well.
