### ISSUE TITLE
Incomplete definition makes compilation slow

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#632]
If you remove [lines 203 and 204 from `hit.circle`](https://github.com/leanprover/lean/blob/master/hott/hit/circle.hlean#L203-204), the compilation of that file is super slow. (~34 seconds instead of the regular ~1 second)

The problematic definition is [`decode_add`](https://github.com/leanprover/lean/blob/master/hott/hit/circle.hlean#L238).

Strangely enough, replacing the two relevant lines by `exact sorry` does make the file compile (quickly), so the computational content of _that part_ of the definition is not even used.

**Comment by leodemoura** [comment]
When the elaborator fails to elaborate a definition `D`, it tries to add it as an axiom.
The idea is to avoid an avalanche of errors such as `unknown D`.

After you remove the two lines, `decode` becomes an axiom. Then, `encode_decode` fails too because it tries to unfold the axiom `decode`. 

> Strangely enough, replacing the two relevant lines by exact sorry does make the file compile (quickly), so the computational content of that part of the definition is not even used.

Adding `apply sorry` is quite different since `decode` would still be a definition, and it would provide enough information for elaborating the rest of the file.

**Comment by fpvandoorn** [comment]
I see. Are also all definitions which generate an error added as axioms? 

It's too bad that Lean then tries so hard to unify the proof with some axioms in `decode_add`. It would be nice if Lean would give up earlier in this case, but I don't see a good way to do that (other than lowering the max unifier steps if you add an definition as axiom in this way, but that might lead to other strange results).

If you want you can close this.

**Comment by leodemoura** [comment]
> I see. Are also all definitions which generate an error added as axioms?

Yes, **if** lean succeeds elaborating its type.

**Comment by leodemoura** [comment]
BTW, Lean is looping because of the following dubious case-analysis rule.
- Suppose we have a stuck constraint of the form

``` lean
     C.rec ... (?M ...) ...  =?=  t
```

where (?M ...) is the major premise for `C.rec`. As a last resort, Lean will try to case split by trying to assign (?M ...) to each constructor (C.mk_i ...). This rule is not very useful. The last time I checked only a handful definitions use it. However, it produces non-termination in many cases.
It is implemented here
https://github.com/leanprover/lean/blob/master/src/library/inductive_unifier_plugin.cpp#L41-L48

I think I will remove it. BTW, if we disable it, Lean terminates very quickly in this file.

**Comment by fpvandoorn** [comment]
Ah, I remember that rule. I think it caused confusion before. If it indeed is hardly used, it is probably better to remove it.

**Comment by leodemoura** [comment]
I investigated the issue. It turns out the rule is used quite often for structures and other non-recursive datatypes. However, the recursive case is the one that produces non-termination.
So, I restricted the rule to non-recursive datatypes. 
Now, the file `hit/circle.hlean` fails quickly when the two lines are commented.

**Comment by leodemoura** [comment]
Very few library files were affected by this change.
Here is an example:

``` lean
definition is_trunc_succ_succ_of_is_hset (A : Type) (n : trunc_index) [H : is_hset A]
      : is_trunc (n.+2) A :=
@is_trunc_of_leq A (-2.+1.+1) _ star _
```

Before the change, the term `-2.+1.+1` was being synthesized by applying the case-analysis rule above.

**Comment by leodemoura** [comment]
I closed this issue since the file fails quickly after commit https://github.com/leanprover/lean/commit/dc6411b90385344b69f16512a28ce190a01e722b

**Comment by fpvandoorn** [comment]
>  So, I restricted the rule to non-recursive datatypes. 

I think that is a good restriction. With a structure, you're not case-splitting when you assign a metavariable to the unique constructor. With an inductive type there's much less chance you will find the right solution, and it can result in ~~termination~~ looping.

In the example you posted it is very reasonable to require more information than was given.
