### ISSUE TITLE
*lean-info* for HoTT

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#633]
In the standard (non-HoTT) lean-mode, there is a `*lean-info*` buffer which displays the goal of a tactic proof when you hover over a comma. There doesn't seem to be such a buffer for HoTT mode. Could that be added?

**Comment by soonhokong** [comment]
@fpvandoorn, I will add it.

**Comment by soonhokong** [comment]
@fpvandoorn, [the current implementation](https://github.com/leanprover/lean/blob/master/src/emacs/lean-type.el#L79-L81) always outputs to `*lean-info*` buffer whenever there is something to output, regardless of current sub-mode (`standard` or `HoTT`).

Could you give me a file and point information (col/line numbers) where you expect to have info message? I'll double-check that.

**Comment by leodemoura** [comment]
@soonhokong Recall that the _lean-info_ buffer has a bug that we never understood.
Sometimes it stops receiving information, and the only way to fix it is to restart emacs.
I eventually stopped using _lean-info_ because of this bug.

This is why I suggested https://github.com/leanprover/lean/issues/499
It would be a reliable and extensible way to extract information from a Lean file.
However, we also had reliability problems with https://github.com/leanprover/lean/issues/499 
I still thing #499 is the way to go if we can make it reliable. 
It would provide a boost in productivity for most Lean users.

**Comment by soonhokong** [comment]
@leodemoura, I see. I'll investigate #499.

**Comment by leodemoura** [comment]
> @leodemoura, I see. I'll investigate #499.

I would be great if could solve it. It would be super easy to add new commands.
Moreover, we would be able to remove _lean-info_.

**Comment by fpvandoorn** [comment]
I want to note that today is the first time that `*lean-info*` is working nicely for me in HoTT mode. Usually I got a lot of `pre-message is thrown away`-errors, but today I get useful goals and type information. I think it has to do with the improvements in `lean-flycheck.el` you made last week. So that's really nice! This might have also solved the bug Leo mentioned:

> Recall that the lean-info buffer has a bug that we never understood.
> Sometimes it stops receiving information, and the only way to fix it is to restart emacs.
> I eventually stopped using lean-info because of this bug.

I'll close this issue, but I agree with Leo that implementing #499 would be really nice.

**Comment by fpvandoorn** [comment]
I think the bug mentioned by Leo still exists. But the pre-message bug seems to be solved.
