### ISSUE TITLE
new le and lt for nat

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#638]
I want to redefine `nat.le` and `nat.lt` in the HoTT library as 

``` lean
  inductive le (a : nat) : nat → Type₀ :=
  | base : le a a
  | step : Π {b}, le a b → le a (succ b)

  definition lt [reducible] (n m : ℕ) := succ n ≤ m
```

The current definition is the other way around, `lt` is primitive:

``` lean
  inductive lt (a : nat) : nat → Type₀ :=
  | base : lt a (succ a)
  | step : Π {b}, lt a b → lt a (succ b)

  definition le [reducible] (a b : nat) : Type₀ := a < succ b
```

@leodemoura: Can this potentially break things in the C++ code? `nat.lt` and `nat.le` are not listed in `constants.txt` but I thought that `lt.wf` was used for something.

---

**Motivation**

With the current definition, you cannot induct over `H : n ≤ m`. The reason is that `H` is unfolded to `H : n < succ m`, and `succ m` is not a variable, but is an index for the family `lt`.
You can manually define a recursor for `le`, but that doesn't have the right computation rules _definitionally_, which is a pain.

With the new definition, you can induct over _both_ `H : n ≤ m` and `H : n < m`, because in both cases the index is a variable. I've used this in my [construction of the propositional truncation](https://github.com/fpvandoorn/leansnippets/blob/master/propositional_truncation.hlean) extensively. For example, you can define

``` lean
open nat (hiding le)

inductive le (a : ℕ) : ℕ → Type₀ :=
| base : le a a
| step : Π {b}, le a b → le a (succ b)

local infix `≤` := le

variables {A : ℕ → Type} (f : Π{n : ℕ}, A n → A (succ n))
include f

definition fr {n m : ℕ} (a : A n) (H : n ≤ m) : A m := -- repeatedly apply f
begin
  induction H with m H b,
  { exact a},
  { exact f b},
end
```

I used this definition a lot. And it was important to make this definition as simple as possible, because not only did I need to prove properties about `f_repeat`, such as

``` lean
definition fr_f {n m : ℕ} (a : A n) (H : n ≤ m) (H2 : succ n ≤ m) : fr a H = fr (f a) H2
```

I also needed to show that the definition `fr_f` satisfied certain properties (so 2-dimensional paths).

**Comment by leodemoura** [comment]
I think this is a good change, and it doesn't affect the C++ code.
I did not implement the automation for well-founded recursion yet: https://github.com/leanprover/lean/issues/392

**Comment by fpvandoorn** [comment]
Ok, then I'll implement it. 

By the way: I want to say that the `induction` tactic is very useful and works great. I use it a lot.

**Comment by fpvandoorn** [comment]
closed by 14fb580885170ef2ebbe257395d344dc2452e317 (but not yet merged into `master`)

**Comment by avigad** [comment]
Shouldn't we make the same change in the standard library? @fpvandoorn, how much more work would it be to move the change there?

**Comment by fpvandoorn** [comment]
Yes, I'm going to make the same change in the standard library. That shouldn't be much work.

Initially I thought I shouldn't do it for the standard library, because the motivation example - the definition of `fr` - is not possible in the standard library, because you would have to eliminate from `Prop` to `Type`. Or is there a trick to still do this?

However, to keep the libraries as similar to each other as possible (to make future porting easier), it's indeed important that the underlying definitions are the same.

**Comment by avigad** [comment]
I haven't thought about this carefully, but for predicates `A : nat -> Prop`, does this give you useful forms of induction? For example, can you use it to prove "total induction"?

**Comment by leodemoura** [comment]
@avigad The main motivation for the new declaration is that it is easier to work with.
Indexed families are usually a mess to work with, but there is an exception.
We say it is "easy" to apply induction on a hypothesis `h : C A i`, where `C` is an inductive type, `A` parameters and `i` the indices, when all indices in `i` are pairwise distinct variables.
For example, `le` has one parameter and one index, then `h : le x y` and `h : le (succ x) y` are "easy" because in both cases the index is the variable `y`. On the other hand, `le x (succ y)` is not.
The induction tactic process "easy" cases by reverting any hypothesis that depends directly or indirectly on `h` or its indices, then it applies the induction, and then reintroduces everything back.
For user-defined induction principles, we think this is the best we can do automatically.

In the master branch, we define `le x y` as `lt x (succ y)`. Floris noticed this is bad because we will never have an "easy" hypothesis.  Suppose we have `(h : le x y)`, and say `induction h`. Then, Lean will say "failed to apply lt.rec_on because `succ y` is not a variable". However, if we define `le` as the inductive datatype above, and `lt x y` as `le (succ x) y`. Then, both `(h : le x y)` and `(h : lt x y)` are "easy" hypothesis.   

For builtin induction principles, we can use dependent pattern matching (e.g., `cases`-tactic) when the index contains constructors. However, the current implementation uses proof irrelevance, and only works reliably on the standard library. So, for the standard library, the change doesn't make a big difference, but I think we should do it anyway to make sure both libraries use similar definitions.

**Comment by avigad** [comment]
Thanks -- this explanation is very helpful.

**Comment by fpvandoorn** [comment]
Unfortunately, the standard library depends in quite some places on the fact that `succ n ≤ m` and `n < m` are definitionally equal. I made the changes here: 23711d9296762cbf9c204cfef793350f13d679f8.

There was one bigger issue: bounded quantification is defined as

``` lean
  definition bex (n : nat) (P : nat → Prop) : Prop := ∃ x, x < n ∧ P x
  definition ball (n : nat) (P : nat → Prop) : Prop := ∀ x, x < n → P x
```

Previously, bounded quantification with `≤` was a special case of this:

``` lean
(∃ x, x ≤ n ∧ P x) ≡ bex (succ n) P
(∀ x, x ≤ n → P x) ≡ bex (succ n) P
```

Now those definitional equalities are only equivalences. Moreover, if we define `bex` and `ball` using `≤`, then `<` would still not be a special case (for `n = 0`).

To make sure that [test/lean/run/bquant](https://github.com/fpvandoorn/lean/blob/master/tests/lean/run/bquant.lean) compiled, I had to define two more instances in [bquant](https://github.com/fpvandoorn/lean/blob/master/library/data/nat/bquant.lean#L82-92). 

This is why the test suite is useful! Otherwise I wouldn't have noticed. Hopefully this is the only thing that broke (the standard library + test suite compiles, so if something else broke, it is not yet used).
