### ISSUE TITLE
meaning of !

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#641]
In my copy of the repository, I just changed the order of arguments in 

```
theorem mul_le_mul_left {n m : ℕ} (H : n ≤ m) (k : ℕ) : k * n ≤ k * m := ...
```

in order.lean to

```
theorem mul_le_mul_left {n m : ℕ} (k : ℕ) (H : n ≤ m) : k * n ≤ k * m := ...
```

In other words, I moved `k` before `H`. The reason the new order is better is that we can write

```
!mul_le_mul_left H
```

in the proof of a theorem, rather than

```
!mul_le_mul_left H _
```

On the other hand, in a sense, the original order was better, because it works better with partial application, `mul_le_mul_left H`.

It occurred to me that there is an alternative semantics for "!" that would erase the distinction, and might make more sense. Right now, "!" means "make all arguments implict, _until we reach an argument that cannot be inferred from a later argument or the conclusion_." An alternative is, "make all arguments implicit _that cannot be inferred from a later argument or the conclusion_." In other words, don't stop at the first argument that has to be made explicit.

In most situations, the answer comes out the same both ways. It only makes a difference in examples like the one above.

I don't feel strong about this either way, but I thought I would raise it for discussion. If we keep the semantics of "!" as it is now, I think the general practice will be to always list arguments before hypotheses, so that "!" makes everything implicit.

**Comment by fpvandoorn** [comment]
I don't feel strongly about the semantics of `!`. Maybe the proposed one is a little better, because it is simpler to understand for users.

I agree that the new order of arguments is better. Could you also change this for `add_le_add_[left|right]`?
And arguably the new order is actually better with partial application, if you interpret this theorem as the functoriality of `mul k` between posets.

**Comment by leodemoura** [comment]
I'm fine with the new order.

Regarding the new semantics for `!`, I think this is very low priority. The current behavior is not buggy, and the new one is a very small improvement. Most users will never notice the difference. 

BTW, it is also not clear to me how complicated is the modification. It affects one of the biggest files in the code-base: the elaborator preprocessor.

**Comment by avigad** [comment]
I am glad to hear from Floris that there is a principled reason to put k before H. If we do this in general, there is no need to change the meaning of !. 

I will:
- make this change also for add_le_add, and also in the HoTT library
- say something about argument order and implicit/explicit is library_style.org.

**Comment by avigad** [comment]
I started making the changes for add_le_add and friends, and then I got cold feet. I am not sure which order I like better. These theorems are used in lots of places, and sometimes the change is an improvement, and sometimes not. E.g. sometimes instead of "rewrite [add_le_add_left H]" we will have to write "rewrite [!add_le_add_left H]".

My inclination is to leave it like it is for now, and wait until I have a stronger feeling one way or the other. So I will close this issue now. But @fpvandoorn If you have a strong feeling about this, let me know. I can easily be convinced to make the changes. (It will only take about a half hour or so.)

**Comment by fpvandoorn** [comment]
I don't feel too strongly about it either. But I still like the changed version a little better. It's also a little simpler to remember.

> E.g. sometimes instead of "rewrite [add_le_add_left H]" we will have to write "rewrite [!add_le_add_left H]".

Can you rewrite with an inequality?

I think this is an instance of a more general problem. The problem is that we want different arguments implicit in declarative mode and tactic mode. I've noticed this for a while, but I have no good solution for it.

Consider the two theorems:

``` lean
theorem mul_le_mul_left {n m : ℕ} (H : n ≤ m) (k : ℕ) : k * n ≤ k * m -- (1)
theorem lt_of_mul_lt_mul_left {n m k : ℕ} (H : k * n < k * m) : n < m -- (2)
```

Which arguments should be explicit? Surely in both cases `H` should be explicit, and `n` and `m` should be implicit. However, for `k` it's not so clear, for both theorems. 

The current way is perfect for declarative style proofs. In declarative style proofs, the type of the conclusion is not always known, which is why we want it explicit in (1). On the other hand, the term `H` is written down explicitly, so its type can be usually inferred, and that gives us `k` in (2).

For tactic proofs this is the other way around. The current goal is known exactly (and almost always without metavariables), but `H` might be given in a later tactic. For example, if you write `apply lt_of_mul_lt_mul_left,` on the goal `n < m`, the new goal becomes `?M_1 * n < ?M_1 * m`. So in that case we want to specify `k` explicitly. On the other hand, having `k` explicit in (1) is almost always unnecessary, since the conclusion is known.

The distinction is not completely clear-cut, for example if you write a longer term in tactic mode (in for example a `refine` or `exact` tactic)

**Comment by avigad** [comment]
> Can you rewrite with an inequality?

Sorry, my mistake. It was used in "calc" mode.

The internal policy I have been using is that an argument is marked implicit if it appears in a later hypothesis -- if it only appears in the conclusion, I make it explicit. As you say, sometimes that is what you want, and sometimes it isn't. At least it gives me an easy rule to follow when I am writing down theorems.

I will keep this issue on my to do list, and mull it over, and maybe eventually make the change we have been talking about.
