### ISSUE TITLE
Lifting sequences to a quotient space

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#649]
I am trying to prove (constructively) that R is complete. Since the proof goes via rational approximations of reals, it seems necessary to prove it for "prereals" (regular sequences of rationals) and lift this to R. The proof would look like this:
- Define Cauchy sequences of prereals and show the definition respects equivalence.
- Show that every Cauchy sequence of prereals {s_n} has a limit.
- Show that for any two Cauchy sequences of prereals {s_n} and {t_n} with s_n ≃ t_n for all n, we have lim s_n ≃ lim t_n.
- Lift the Cauchy property and limit functions to R.

The first three points seem possible. I'm not so sure about the fourth. The quotient library allows us to lift functions on n-tuples of the base space, but lifting the limit seems stronger. @leodemoura @fpvandoorn  and others: do you think this is doable with the current lifting property?

**Comment by avigad** [comment]
For the record, my guess is that it is not doable without adding an axiomatically stronger lifting property. My guess is that one can cook up crazy models where a function on sequences doesn't lift that way. Which is a little depressing...

**Comment by avigad** [comment]
See chapter 11.3 in the HoTT book:

https://hottheory.files.wordpress.com/2013/03/hott-online-611-ga1a258c.pdf

I don't know what "solution" they have in mind with the countable axiom of choice (i.e. what background axiomatic system they implicitly have in mind). Anyhow, I don't see a solution for us, other than to postulate a stronger lifting property.

**Comment by leodemoura** [comment]
Could you post the stronger lifting property needed (as a Lean axiom)?

**Comment by fpvandoorn** [comment]
With prereal you mean a regular sequence?
Is there a difference with `≃` (in your post) and `≡`, in `real.basic`?

It sounds right to me that you need some property like countable choice to prove this. Informally, I think the argument goes like this:

Given a Cauchy sequence `(r_n)_n` of reals. Use countable choice to choose, for each `r_n` a prereal `s_n` such that `[s_n]=r_n` (`[...]` is the quotient map). Now construct a limit of `(s_n)_n` in prereal (the limit  `s` can be something like `s(n)=s_{2n}(2n)`, I think). Now take `r=[s]` and show that `r` is the limit of `r_n`.

So the axiom needed is something like 

```
forall (f : nat -> @quot A s), exists (g : nat -> A), forall n, [g n] = f n
```

But I would rather have an axiom like that in the classical folder than in `init.quot`.

**Comment by leodemoura** [comment]
We can define 

``` lean
forall (f : nat -> @quot A s), exists (g : nat -> A), forall n, [g n] = f n
```

if `A` is `encodable`, and the setoid equivalence relation is decidable.
https://gist.github.com/leodemoura/6e5260847c1d36ae9c81#file-lift-lean-L37-L38
Unfortunately, this construction doesn't help since `prereal` is not encodable :-(

**Comment by avigad** [comment]
The usual computation rule for quotients says

```
lift f [[a]] = f a
```

We can also use "lift" to lift binary functions, ternary function, etc.

What we need here is a strengthening, `liftseq`, that allows `f` to be a function which takes a nat-indexed sequence of elements of the type that is being quotiented. Given a function `f : (nat -> A) -> B` and a proof that `f` respects the pointwise equivalence relation on `nat -> A`, we get the new function `liftseq f : (nat -> quot A) -> B`, satisfying the rule

```
liftseq f (fun n, [[a n]]) = f (fun n, a n)
```

It is probably enough if this rule holds propositionally instead of definitionally. Rob would use this to define the limit of a Cauchy sequence of reals (with an explicit function giving the rate of Cauchyness). I think he would also need the corresponding induction principle, allowing one to prove `forall s, P s` from `forall t, P (fun n, [[t n]])``. In other words, to show that some property holds of any sequence of reals, it is enough to show that the property holds for a sequence of reals represented by prereals.

These are both generalizations of what is in the current quotient package. I don't know whether they count as constructive, or what properties they have. We can move this discussion to lean-discuss if that would be helpful -- Bas Spitters or Ulrik Buchholz may have some ideas.

Classically, there is no issue. Using Hilbert choice, Rob can define a function `repr : quot A -> A` with the property that `[[repr a]] = a`. Using `repr`, he can then define the lift and induction principle described above. 

For the moment, that might be the best way to proceed. The approach will use Hilbert choice, but it will be "almost constructive." Someone who wants to work with the reals constructively will then have to decide what they want to do. Two possibilities are working with prereals, or adding these stronger principles. Either way, they can adapt the really nice work that Rob has done.

**Comment by robertylewis** [comment]
> Could you post the stronger lifting property needed (as a Lean axiom)?

What you and Floris posted would do the trick perfectly.

> With prereal you mean a regular sequence?
> Is there a difference with ≃ (in your post) and ≡, in real.basic?

Yes, and no- I just copied the symbol over from a different file.

> It sounds right to me that you need some property like countable choice to prove this. 

Yes, I think this is right. The HoTT book makes this claim, and Jeremy and I roughly sketched the idea yesterday. 

> But I would rather have an axiom like that in the classical folder than in init.quot.

I generally agree. Ultimately, this comes down to what we want out of the "constructive" reals. If we allow Hilbert choice, then solving this issue is (relatively) easy. Is there a reason to prefer reals that are built with a new, classical-ish lifting axiom (roughly countable choice) over reals built with Hilbert choice?

**Comment by avigad** [comment]
By the way, Floris' axiom will allow us to prove that a limit exists, but we still won't be able to write "lim s M" (where M is the rate of Cauchyness) without using Hilbert choice. I don't think that is of any use constructively. For example, we can't define sqrt 2 or pi. Classically, it is only useful with Hilbert choice, for the same reason. And, in that case, we don't need the axiom.

**Comment by leodemoura** [comment]
@avigad Are you are suggesting the following `liftseq` and reduction rule `liftseq_eq` (written as an axiom here).

``` lean
constant liftseq
  : Π {A B : Type} {s : setoid A} (F : (nat → A) → B),
    (∀ (g₁ g₂ : nat → A), (∀ n : nat, g₁ n ≈ g₂ n) → F g₁ = F g₂) → (nat → quot s) → B

axiom liftseq_eq :
  ∀ {A B : Type} 
    {s : setoid A} 
    (F : (nat → A) → B)
    (c : ∀ (g₁ g₂ : nat → A), (∀ n : nat, g₁ n ≈ g₂ n) → F g₁ = F g₂) 
    (f : nat → A), 
    liftseq F c (λ n : nat, ⟦f n⟧) = F f
```

I don't see how to implement a computational rule such as `liftseq_eq`, 
Given a term `liftseq F c g`, we could try to normalize `g`. Assume it normalizes to a lambda (and it will if the term is closed and there are no axioms). The next step doesn't work, the body of the lambda expression is not a closed term. So, it may not reduce to a term of the form `⟦f n⟧` (i.e., a term starting with `quot.mk`. The computation would get stuck at this point.

**Comment by avigad** [comment]
Good point. So maybe it is not a nice constructive axiom. 

This and the comments in the HoTT book lead me to believe that there is not a nice constructive treatment of the reals using quotients. That's depressing. The alternatives are to use the setoid approach (which Rob's formalization does support), or to do something like what is in the HoTT book, which requires more powerful inductive types.

**Comment by leodemoura** [comment]
> This and the comments in the HoTT book lead me to believe that there is not a nice constructive treatment of the reals using quotients. That's depressing.

Yes, I agree. It is depressing. Now, the hard question: is the builtin type `quot` really useful?.
One of the main motivations for implementing `quot` was the reals.
We don't need `quot` for defining `int` and `rat`. Both of them are "definable quotients" in ITT (using the terminology from http://www.cs.nott.ac.uk/~txa/publ/defquotients.pdf). 
We could have defined `finset A` as the subtype of ordered lists without duplicates. It is not as general as the current `finset A`, but the extra generality doesn't seem to buy us much.
The `reals` is the first example of "undefinable quotient" that we have tried, if `quot` doesn't really help, what is the point of having `quot`?

On the positive side, I believe `quot` makes the system more convenient to use. 

BTW, in the HoTT book, they claim the lift can be done using just the law of the excluded middle. Have you tried that?

**Comment by avigad** [comment]
Right now int doesn't use quotients at all, and yes, rat can be rewritten to avoid them as well. So I don't see any strong argument for keeping them, other than the fact that they have been so pleasant to use. On the other hand, maybe the pleasantness can be restored by reviving @fpvandoorn's quotient library. I will think about it. I will also look into what is going on with the law of the excluded middle.

**Comment by leodemoura** [comment]
I have been thinking about the `quot` issue today.
One issue in favor of the current `quot` builtin type is computational behavior.

Suppose we define `finset A` as the subtype of sorted lists without duplicates. Then, to use `finset A` we  need an order on `A`. Moreover, functions such as `union : finset A -> finset A -> finset A` would have to return a sorted list. We can derive a "default" order for any encodable type. However, this order is horrible in terms of performance since they would convert `A` into `nat` and then use `<` for `nat`. The natural numbers generated by the `encodable` module are extremely huge for any non-trivial value. 
So, if users want to compute with this new `finset A`, they would be forced to implement an "efficient" order relation. This looks annoying. 
In the current `finset A`, we only need to show that `A` has decidable equality.

**Comment by avigad** [comment]
It will make me happy to keep `quot`. As I said, it is nice to use.

Here is another argument. We also have to decide whether to "keep" `funext` and `propext`. I would be more reluctant to give those up. They make a big difference as far as usability: they let us rewrite propositions, rewrite sets in a calculation, rewrite expressions under in a summation, etc. The coding trick I described for finsets only makes sense if we have `setext` (which we get from `funext` and `propext`), because we want to finsets to be equal if they have the same elements.

The argument is simply this: if we keep `funext`, `quot` doesn't seem that much worse. So we may as well keep that too.

**Comment by spitters** [comment]
Quick answer. @rlewis1988 seems to need the [Presentation Axiom](http://ncatlab.org/nlab/show/presentation+axiom). It's constructive, but does not hold in some topos models. Also, it is not provable in HoTT. This is the reason that we used Higher Inductive Inductive types in the book.

Since LEAN does not have such HIITs. You seem to need to add an axiom, the one mentioned above is a countable version of this.

An alternative would be to use a (predicative) version of Dedekind reals. There is a discussion about this in the HoTT book.

**Comment by avigad** [comment]
Hi, Bas. The translation from category theory to type theory is not obvious. Could you write down a type-theoretic formulation of what you have in mind?

Will it give us the existence of a limit, as a proposition, or will it actually let us construct the limit?

Are there any computation / reduction rules associated with the axiom?

Thanks!

**Comment by spitters** [comment]
I am at the [agda meeting](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.AIMXXI). LEAN has come up a couple of times.

I'll try to find follow-up discussions, but the source for such choice axioms valid in the setoid model are discussed in [Hofmann's thesis](http://www.lfcs.inf.ed.ac.uk/reports/95/ECS-LFCS-95-327/). Sec. 5.1.7.

**Comment by avigad** [comment]
Thanks, that's helpful. I am struck by his observation that if we treat the reals as a quotient, we can't compute any nontrivial function to the rationals or reals, e.g. we can't even compute the first digit of Pi. That, to me, strongly suggests that it is a bad idea to develop the constructive reals as a quotient.

But anyhow, I don't think the extension described in his thesis makes it possible to define the limit of a Cauchy sequence with a fixed rate of convergence.

**Comment by spitters** [comment]
Every (definable, total) function on the reals is continuous.
Hence, every function to a discrete space is constant, as the reals are
connected.
This means that reals don't have a decimal expansion.

However, positivitively irrational functions do have a decimal expansion.
In particular, we _can_ compute the decimals of pi.

Also, defining continuous functions on a quotient should not be a problem.

I'll try to think about precisely which choice axiom is needed. In any
case, that is possible in the setoid model and Hofmann is internalizing
that type theory. This was of course continued in observational type theory.

**Comment by leodemoura** [comment]
@spitters Thanks for the pointers. They are quite useful.

It is not clear to me how useful Hofmann's choice is. The Q-choice rule looks really restrictive. I agree with @avigad, I don't see how to define the limit of a Cauchy sequence using it.
As far as I understand, Hofmann is addressing the issue: when is it "safe" to access the internal representation of a quotient value?

He provides an example, where he shows how to use his choice to convert a `real` into a `prereal` in the _empty_ context. I agree this is useful, but I don't see how it would solve our problem.  

@avigad I think the comment you made about `Prop` (at #650) is also applicable to `quot`: 
"`Prop` is one of those parking lots you can pull into but can't back out of, at least not without severe tire damage." :-)
Well, `quot` is a slightly better "garage", we can back out under special conditions, but sometimes it is quite tricky or impossible. 
Extracting the first digit is one of these messy situations. Suppose we try to use `quot.lift_on` to implement this function. It gives us access to the internal representation `f : nat -> rat`, but we have to show that for any other equivalent `g : nat -> rat`, the function produces the same result :-(

**Comment by leodemoura** [comment]
@spitters 

> This was of course continued in observational type theory.

BTW, @avigad, @codyroux and I had a long email exchange about OTT. 
I was planning to support OTT in Lean. However, there are some technical issues. 
It would be great to have your feedback. 
I will create an issue on github, and list all the problems we found.

**Comment by leodemoura** [comment]
@spitters #654 is the summary of the OTT thread I mentioned in the previous comment. 
Comments are very welcome :-)

**Comment by spitters** [comment]
I'll try to answer tomorrow. I am speaking tomorrow morning on the cubical
model in the agda meeting.
Having an implementation of OTT in LEAN seems very interesting.

**Comment by leodemoura** [comment]
I had lunch today with Abhishek Anand. He is one of Constable’s current PhD students, and he is doing an internship with Nikhil. Abhishek works on Constructive Analysis (http://www.cs.cornell.edu/~aa755/ROSCoq/), and is a power user of Bas' CoRN library. 

I asked him about reals in NuPRL, he said they do **not** use quotient types for defining the reals. He said they use the following "rule of thumb" in NuPRL: one should only use quotient types when they can compute a canonical representative. Otherwise, you can get stuck inside the quotient. 

BTW, Bishop also makes a relevant remark in the "Constructivist Manifesto":
"The axiom of choice is used to extract elements from equivalence classes where they should never have been put in the first place. For example, a real number should **not** be defined as an equivalence class of Cauchy sequences of rational numbers; there is no need to drag in the equivalence classes".

**Comment by leodemoura** [comment]
> I'll try to answer tomorrow. I am speaking tomorrow morning on the cubical model in the agda meeting.
> Having an implementation of OTT in LEAN seems very interesting.

Thanks!

**Comment by leodemoura** [comment]
I'm closing this issue (of course, feel free to continue the discussion).
Here is summary (feel free to add more items).
- Quotient types are nice but they do not solve all problems. In some cases, we still have rely on setoids. We should keep in mind the heuristic suggested by Abhishek for deciding whether to use a quotient or not: "one should only use quotient types when they can compute a canonical representative. Otherwise, you can get stuck inside the quotient."
- Reals are **not** implemented using quotient types in NuPRL.
- This thread raises another issue: should the algebraic hierarchy be based on setoids? That is, should  the root of the algebraic hierarchy be a setoid? Of course, we can only make this change after we have the simplifier. The rewrite tactic (and eq.rec) are extensively used in the algebraic hierarchy, they only support `eq`.

**Comment by avigad** [comment]
A small comment regarding the last bullet point: using quotients, it is routine to translate first-order statements about equality-based structures to the corresponding structure based on equivalences. You simply rewrite with rules like

``` lean
  (∀x, p x) ↔ (∀u, p ⟦u⟧)
  (∃x, p x) ↔ (∃u, p ⟦u⟧)
  ⟦u⟧ = ⟦v⟧ ↔ u = v
  ⟦u⟧ ≤ ⟦v⟧ ↔ u ≤ v
  ⟦u⟧ * ⟦v⟧ = ⟦u * v⟧ 
  ⟦u⟧ + ⟦v⟧ = ⟦u + v⟧

```

This does involve using quotients to get the setoid-based versions, though, which is less pure than deriving them directly.
