### ISSUE TITLE
What is 'cast' field in 'binder_info'?

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#667]
Hi,

`m_cast` and `m_implicit` are both fields of `binder_info`: 

https://github.com/leanprover/lean/blob/master/src/kernel/expr.h#L215-L222

When parsing binders, the comments say that '[' denotes `cast`, but the parsing function itself makes an `inst_implicit` binder instead:

https://github.com/leanprover/lean/blob/master/src/frontends/lean/parser.cpp#L821-L823

The `cast` field doesn't seem to be used anywhere important. Does it represent a discontinued alternative or am I missing some subtlety?

Thanks,

Daniel

**Comment by leodemoura** [comment]
You are correct, the `cast` is not being used anywhere right now. 
The original goal was to support coercions to/from [subtypes](https://github.com/leanprover/lean/blob/master/library/data/subtype.lean).
An automatic coercion from `{x : A | P x}` to `A` is easy to support.
The reverse direction `A` to `{x : A | P x}` is more expensive, since the system would generate a new goal forcing us to prove that for a given argument `a : A`, we have `P a`.
We also planned to allow the user to provide "tactic-hints" that would discharge the simple cases automatically.
Since a new goal would be generated, the new binder annotation would allow users to control whether this feature is used or not. The idea is similar to the binder annotation used for triggering type-class resolution. 

Regarding the comment at `expr.h`, it is incorrect. It was written before we have implemented type-classes in Lean. I will fix it.

**Comment by dselsam** [comment]
Thank you for clarifying. Is the idea is that a user would have been able to write something like: 

``` Lean
definition f (x : T) {# Px : P x by <tactic>} := <body>
```

and then call `f x` somewhere and have Lean try to prove `P x` automatically using the provided tactic? If so, it seems like an interesting generalization of the generic Prolog-like search used in type-class resolution, though I have no specific use cases in mind. 

Have you considered a similar binder annotation that means 'synthesize an instance of the `decidable` type-class and extract the proof if it succeeds'? There may already be a way to do this with the existing type-class mechanism, but I haven't read the code carefully enough yet to know.

**Comment by leodemoura** [comment]
> and then call f x somewhere and have Lean try to prove P x automatically using the provided tactic?

This is a nice suggestion. 
We had a slightly different approach in mind.
We would associate tactics with constants. Suppose we define `pos (x : nat) := x > 0`, and associate a tactic `T` with the constant `pos`. Then, whenever we have an annotated binder `{# px : pos x }`, we would try to synthesize it using the tactic `T`. We can view these constants as tags to mark a class of propositions that we want to synthesize automatically using a tactic. 

> Have you considered a similar binder annotation that means 'synthesize an instance of the decidable type-class and extract the proof if it succeeds'? There may already be a way to do this with the existing type-class mechanism, but I haven't read the code carefully enough yet to know.

I'm not sure if I understood the question. Are you suggesting to use tactics to synthesize some instances of the `decidable` type-class? This would be useful. 
We will be able to do it after we implement the approach we are discussing in this thread.
For example, we could associate a tactic with the constant `decidable`. Then, this tactic would be used instead of the type class resolution procedure whenever we use the `{# ...}` binder annotation instead of `[...]`.

**Comment by dselsam** [comment]
> I'm not sure if I understood the question. Are you suggesting to use tactics to synthesize some instances of the decidable type-class? 

No, sorry I wasn't clear. I don't think the suggestion is a good one, but I'll share it in case it inspires a better idea in the future. No need to read or respond.

When a function has decidable preconditions, one can often pass `dec_trivial` as an argument. This is always the case when computing:

``` Lean
definition xs : list ℕ := [1,2,3]
definition xs_last : ℕ := last xs dec_trivial
```

but can also be true with partially opaque values:

``` Lean
constant xs : list ℕ 
constant x : ℕ
definition y : ℕ := last (x :: xs) dec_trivial
```

This is not a problem, but it seems a little awkward. It would be nice if Lean could infer these automatically, but the obvious issue is that the number of meta-variables is fixed during preprocessing, so we would probably need a new syntactic construct to indicate whether we want the decidable preconditions to be synthesized or not. It does not seem worth the additional complexity.

**Comment by dselsam** [comment]
By the way, I don't know what the social conventions are for closing issues, and I would appreciate any instructions or feedback. I closed it because you answered all of my concrete questions, though I did not mean to end the discussion on alternative binders prematurely.

**Comment by leodemoura** [comment]
> When a function has decidable preconditions, one can often pass dec_trivial as an argument. This is always the case when computing:

`last` is a good example. 
I agree it would be nice to have a mechanism to synthesize this kind of argument automatically. 
I think the mechanism we discussed in this thread may help.
For example, consider the following code fragment

``` lean
import data.list
open list nat

definition mytac : tactic :=
tactic.exact dec_trivial

definition notnil [reducible] {T : Type} (l : list T) := 
l ≠ []

definition mylast {T : Type} (l : list T) {h : notnil l} : T :=
last l h

tactic_hint mytac  

constant xs : list ℕ
constant x : ℕ
definition y : ℕ := mylast (x::xs)
```

It works in current Lean, but it has a nasty side-effect. Lean will try to use `mytac` to synthesize **any** unassigned metavariable. It would be nice if we could say that `mytac` should only be used to synthesize a particular kind of argument (e.g., `notnil` propositions). 

``` lean
tactic_hint mytac notnil
```

We would not even need to create a new kind of binder annotation.
The drawback is that it forces users to create definitions (e.g., `notnil`) whose only purpose is to tag arguments that should be synthesized by tactics.
What do you think?

**Comment by leodemoura** [comment]
> By the way, I don't know what the social conventions are for closing issues, and I would appreciate any instructions or feedback. I closed it because you answered all of my concrete questions, though I did not mean to end the discussion on alternative binders prematurely.

No problem. 
We do the same thing.

BTW, thanks for all the feedback and suggestions.

**Comment by dselsam** [comment]
I agree that needing to annotate a binder with a tactic like 

``` Lean
definition mylast {T : Type} (l : list T) {h : l ≠ [] # mytac} : T
```

could get cumbersome, since certain predicates are likely to be preconditions to several different functions, in which case it would be preferable to store the tactic hint once and for all. 

Requiring a special definition (e.g. `notnil`) is a fine solution, though understanding when definitions get unfolded and when they don't seems to be one of the most subtle parts of the system, and all things being equal it seems preferable to minimize the number of places that users need to consider this issue. If performance were not a concern, I might suggest a slight variant:

``` Lean
tactic_hint mytac (λ {T : Type} (l : list T) := l ≠ [])
```

or

``` Lean
tactic_hint mytac pattern:(_ ≠ [])
```

and then allow users to write 

``` Lean
definition mylast {T : Type} (l : list T) {h : l ≠ []} : T
```

without wrapping it in a definition.

**Comment by avigad** [comment]
For the original idea, do we really need a new binder? Instead, we could think of it as an extension of the usual class inference procedure, and use `[foo : bar]`. The mechanism would be this: if there is a special tactic registered for `bar`, Lean uses that, otherwise it does class inference as usual.

I can think of two advantages to this:

(1) We avoid yet another binder syntax.

(2) Users can install special tactics that "replace" type classes inference, e.g. special handling for "finite" or "decidable". (A tactic could perhaps do something special, and then call regular type class inference if it wants to.)

**Comment by leodemoura** [comment]
> For the original idea, do we really need a new binder? 

We don't. 
See the comment: https://github.com/leanprover/lean/issues/667#issuecomment-111568006

**Comment by leodemoura** [comment]
> Instead, we could think of it as an extension of the usual class inference procedure, and use [foo : bar]. The mechanism would be this: if there is a special tactic registered for bar, Lean uses that, otherwise it does class inference as usual.

I want to keep the type class resolution procedure simple, and it should not invoke the tactic framework. Otherwise, it would be even trickier to create the shortcuts we are discussing at #666.

Remark: it is fine to invoke type class resolution from the tactic framework.
