### ISSUE TITLE
check_expr and other tactics don't agree

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#672]
Lean has trouble with le_of_lt with implicit arguments:
https://github.com/htzh/leanproved/blob/30f1a88648fa709e2dd3fdd1ec731b62458890bc/group_theory/action.lean#L448

Note that if I use the expression in `check_expr @sub_add_cancel (succ n) iv (le_of_lt ilt)`, rewrite would fail. If I try to rewrite in a different order so that I can use the expression in apply or exact the proof still fails. But check_expr shows the correct signature. The only way to make it work is to spell out the implicit arguments for le_of_lt.

**Comment by leodemoura** [comment]
The problem is that `le_of_lt` and `sub_add_cancel` are both overloaded. 
We have `nat.le_of_lt` and `algebra.le_of_lt`. Same for `sub_add_cancel`. 
Moreover, the rewrite tactic `rewrite [t]` first elaborates the term `t`, and then tries to rewrite using it.
Note that when it elaborates `t`, Lean doesn't know which subterm will be rewritten using it.
In your file, the namespace `algebra` is opened before `nat`. So, Lean will give preference to `algebra`.

The tactic `rewrite [sub_add_cancel (le_of_lt ilt)]` fails because the `algebra` version is being used.
The tactic `rewrite [@sub_add_cancel (succ n) iv (le_of_lt ilt)]` fails because the `le_of_lt` was elaborated into `algebra.le_of_lt`, and the proof term still contains unsolved metavariables. 
Note that the error messages suggests that

```
invalid 'rewrite' tactic, rewrite step failed using pattern
  nat.succ n - iv + iv
matching failures in the goal
  -lemma still contains meta-variables
    nat.sub_add_cancel (algebra.le_of_lt ilt)
  after the equation source has been unified with subterm
    nat.succ n - iv + iv
proof state:
n : ℕ,
madd_left_inv : ∀ (i : fin (nat.succ n)), group.madd (group.minv i) i = fin.zero n,
iv : ℕ,
ilt : iv < nat.succ n
⊢ (nat.succ n - iv + iv) mod nat.succ n = 0
```

If we print it in full detail we will see many unassigned metavariables. 

The tactic `rewrite [sub_add_cancel (@le_of_lt iv (succ n) ilt), mod_self]` succeeds because the explicit arguments "force" the `nat.le_of_lt` to be chosen.

Another option that works is `rewrite [nat.sub_add_cancel (nat.le_of_lt ilt)]` where we explicitly say that we want the `nat` versions. This one also works `rewrite [sub_add_cancel (nat.le_of_lt ilt)]`.

~~We can also use `#nat t` to force Lean to use the `nat` declarations (and notation) when parsing `t`. So, the following also works~~

``` lean
rewrite [#nat sub_add_cancel (le_of_lt ilt)],
```

I will extend the command `override <namespace>`. This commands overrides the notation using the ones defined in the given namespace. I will also make it override the "short names". Then, we will also be able to avoid the problem you had by writing:

``` lean
override nat
lemma madd_left_inv : ∀ i : fin (succ n), madd (minv i) i = zero n
| (mk iv ilt) := eq_of_veq begin
  rewrite [val_madd, ↑minv, ↑zero, mod_add_mod],
  rewrite [sub_add_cancel (le_of_lt ilt)],
  rewrite mod_self
  end
end
```

**Comment by avigad** [comment]
For what it is worth, I found that once I became sensitive to the issue, it was easy to recognize when rewrite was failing because of the wrong choice of overload and work around it.

It is a common problem, though. When a rewrite fails, would it be hard to detect that some of the symbols are overloaded and point that out? ("Note: the following symbols are overloaded...").

**Comment by htzh** [comment]
Is there a reason why check_expr sees the correctly resolved expression but exact or apply does not?

> I found that once I became sensitive to the issue, it was easy to recognize when rewrite was failing because of the wrong choice of overload

I agree but it takes some time and then the sensitivity may fade (like immunization shot). I am fairly sensitized to finset/set overload resolution. I just started working with the algebraic aspect of nat so have not become inoculated yet.

**Comment by leodemoura** [comment]
> Is there a reason why check_expr sees the correctly resolved expression but exact or apply does not?

It doesn't. It also uses the `algebra` version for `le_of_lt`. If we use `set_option pp.implicit true`, we will see that the term `@sub_add_cancel (succ n) iv (le_of_lt ilt)` was not fully elaborated and still contains many unassigned metavariables.

**Comment by htzh** [comment]
> Is there a reason why check_expr sees the correctly resolved expression but exact or apply does not?

I see after I `set_option pp.all true` that check_expr didn't exactly succeed.

**Comment by leodemoura** [comment]
> It is a common problem, though. When a rewrite fails, would it be hard to detect that some of the symbols are overloaded and point that out? ("Note: the following symbols are overloaded...").

I will try to improve. The main complication is that the failure occurs after the elaboration step.
Here is the summary:
To apply `rewrite t`, lean first elaborates `t` (this is done by the elaboration module), then the elaborated term is used to rewrite the goal (this part is implemented in the rewrite_tactic module).
On Haitao's theorem, the elaboration step "succeeds", but the rewrite step fails.
Note that the rewrite tactic is unaware that "overloads" even exist. 
It is "receiving" an elaborated term, and is trying to find subterms that can be rewritten using it, since it doesn't find any it fails.

**Comment by leodemoura** [comment]
I pushed the following improvements:
- `override <namespace>` and `# <namespace> t` also override aliases, before they were overriding only notation declarations.
- rewrite error messages include list of overloaded symbols
