### ISSUE TITLE
induction doesn't unify correctly

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#682]
In [this branch](https://github.com/fpvandoorn/lean/tree/issue682), in the following snippet the tactic `induction p'` doesn't unify correctly with the goal:

``` lean
-- HoTT
import types.pointed
open pointed eq

  definition my_pwhisker_left {A B C : Pointed} {f g : A →* B} (h : B →* C) (p : f ~* g)
    : ap (pmap.map h) (to_homotopy p pt) ⬝ respect_pt (h ∘* g) = respect_pt (h ∘* f) :=
  begin
    induction A with A a, induction B with B b, induction C with C c,
    induction f with f pf, induction g with g pg, induction h with h ph,
    induction p with p p', esimp at *,
    state,
    induction p',
    state,
  end
```

(modified) output:

```
proof state
(...)
pf : f a = b,
(...)
p' : p a ⬝ pg = pf
⊢ ap h (p a) ⬝ (ap h pg ⬝ ph) = ap h pf ⬝ ph

proof state
(...)
pf : f a = b
⊢ ap h (p a) ⬝ (ap h pg ⬝ ph) = ap h pf ⬝ ph
```

The expected second goal is `ap h (p a) ⬝ (ap h pg ⬝ ph) = ap h (p a ⬝ pg) ⬝ ph`

Note: I tried copying the goal at the first `state` to a new example (with option `pp.all` set to true), but in that case the `induction p'` tactic works as expected.

**Comment by leodemoura** [comment]
@fpvandoorn The problem you reported in this thread "re-activated" a concern I have regarding the representation we use in Lean.
In Lean, a free variable (aka local constant in the C++ code) is represented by a pair (string, type).
The main advantage of this representation is that we don't need a context to type check and/or normalize a term. It is also really easy to "cache" results. For example, in the type checker, the cache is simply a mapping from terms to terms. For the predicate `is_def_eq(t,s)`, we use the union-find data-structure to cache the result. Again, everything is simple because the result of `is_def_eq` doesn't depend on any context. It only depends on the environment, and the environment is fixed when we are elaborating some declaration. 
However, this representation has some problems. 
Suppose, we have a term 

``` lean
fun (x_1 : A_1) ... (x_n : A_n[x_1, ... x_{n-1]), t[x_1, ..., x_n]
```

and we want to process `t[x_1, ...,x_n]`, then we replace the `x_i`s with free variables `a_i`s annotated with their types.

``` lean
   t[(a_1:A_1), 
   (a_2 : A_2[a_1:A_1]), 
   ... 
   (a_n : A_n[a_1:A_1, a_2:A_2[a_1:A_1], a_3[a_1:A_1, a_2:A_2[a_1:A_1]], ...])]
```

Initially, everything is fine since all `a_i:A_i` are shared. The term `t` above is really a DAG and not a tree. However, if we apply a transformation that breaks the sharing, we may be in deep trouble. The first problem is performance, I suspect this is a problem, but I don't have data to support this claim. It 
The second problem is the bug you reported.
In your example, the bug was at `esimp at *`. The `esimp` was updating the type of the hypothesis `p`, but it was not updating the the type of the `p` occurring at `p'`.

**Comment by fpvandoorn** [comment]
I'm afraid that my lack of background of computer science becomes clear here. I'm don't know what you mean by

> we want to process `t[x_1, ...,x_n]`

and 

> all `a_i:A_i` are shared

I think I understand the reason why the bug I reported occurred. When modifying the type of a hypothesis `p`, the type associated with all `p`'s occurring in future hypotheses and the conclusion were not updated. Then, when `induction` searches the context for `p`, it doesn't match with the `p`'s which have a different type annotation? If this is true, is there a reason why `induction` wants to match both the string and the type, isn't matching the string enough?

So the fix was to update the types of the variable `p` throughout the goal? Given that the bug is now fixed, is this still a problem for the representation of variables in Lean?

**Comment by leodemoura** [comment]
> we want to process t[x_1, ...,x_n]

I should have been more precise. In this sentence, "process" can be replaced with operations such as "infer the type of", "normalize", "elaborate", etc.

> all a_i:A_i are shared

Internally, the terms are not trees but direct-acyclic-graphs, and "all `a_i:A_i` are shared" means "there is only one node representing `a_i:A_i`". This is quite important because if we represent `t[(a_1:A_1), ...]` as tree it would be very expensive.

The performance problem may occur whenever we update the type of `a_i:A_i` (e.g., instantiate a meta-variable occurring in `A_i`). When this happen we may be breaking the sharing. We create a new `a_i:A_i'`, but we still have other nodes connected to the old `a_i:A_i`.

> When modifying the type of a hypothesis p, the type associated with all p's occurring in future hypotheses and the conclusion were not updated. Then, when induction searches the context for p, it doesn't match with the p's which have a different type annotation?

Correct.

> If this is true, is there a reason why induction wants to match both the string and the type, isn't matching the string enough?

Yes, we match strings/names, but the dependencies were incorrectly computed. After the `esimp`, different occurrences of `p` had different dependencies. 

> So the fix was to update the types of the variable p throughout the goal? 

Yes, this is correct.

> Given that the bug is now fixed, is this still a problem for the representation of variables in Lean?

Yes, we fixed this occurrence. I'm concerned this may be a recurrent issue. 
Another problem is the performance issue. I think it affects files that make heavy use of dependent types. It is hard to say whether this is really an issue or not.

**Comment by fpvandoorn** [comment]
Sorry for my slow response and thanks for the extra explanation. 

> When this happen we may be breaking the sharing.

Do you mean that it is sometimes necessary to break the sharing, or that it sometimes "accidentally" happens? I can't think of a reason where it is required to break the sharing, because it sounds like that would make the term type incorrect.

About your original concern: As far as I can currently see, I think the current method is still better than the alternative of not storing the type of a string. It looks like the advantages you mentioned outweigh the problems. But I think you can judge it much better.

**Comment by leodemoura** [comment]
> Do you mean that it is sometimes necessary to break the sharing, or that it sometimes "accidentally" happens?

It is accidental. To maintain the sharing, we have to use caching whenever we are applying substitutions and instantiating meta-variables. For example, suppose the `A` in `(a : A)` contains meta-variables, and we want to instantiate them. We have to make sure that every term that "points to" `(a : A)` will now point to `(a : A')` where `A'` is `A` after we instantiate the meta-variables.

As we solve unification constraints, we create new ones, and we start having many constraints that reference `(a : A)`.

Here is another example, suppose we have a goal `... |- C[(a : A)]  /\  D[(a : A)]`. The `(a : A)` is shared, i.e., it is the same in `C` and `D`. Now, suppose we use `split`, we will create two subgoals. Now, suppose we use `esimp` to simplify `a : A` to `a : A'` in the first goal. The sharing is also lost. The second goal is still using `(a : A)`. 

> About your original concern: As far as I can currently see, I think the current method is still better than the alternative of not storing the type of a string. It looks like the advantages you mentioned outweigh the problems. But I think you can judge it much better.

I agree. 
I spent a lot of time thinking about this issue last week. I didn't find a better solution.
If we start using contexts, we will have to give up the cache in the type checker and `is_def_eq`.
I also talked with @nikswamy about this issue (he develops F*). He also doesn't see how to keep the caches and use contexts.
