### ISSUE TITLE
checking an explicit cast

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#684]
``` lean
open nat

variable p : nat → Prop
variable H : p (2 + 2)

check H          -- p (2 + 2)
check (H : p 4)  -- p (2 + 2)
```

Shouldn't the second "check" return "p 4"?

**Comment by leodemoura** [comment]
No, it shouldn't. The expression `(H : p 4)` is forcing `H` to have a type definitionally equal to `p 4`. Since `p (2+2)` is definitionally equal to `p 4`, the output is correct. We don't want to add any extra annotation around `H`. Lean will only add "extra" stuff (e.g., coercions) when needed. If coercions are not needed, then `(t : T)` elaborates into `t`. This is really important, I recently fixed a nasty problem in the algebraic hierarchy because this was not the case until very recently.

**Comment by avigad** [comment]
That is reasonable. Would it make sense to restore the "typeof" identity function (without any special notation) to allow users to force the type of a term to look a certain way?

I'll close the issue, but let me know if I should add typeof.

**Comment by leodemoura** [comment]
> Would it make sense to restore the "typeof" identity function (without any special notation) to allow users to force the type of a term to look a certain way?

I'm not sure. It produces counter intuitive behavior if for example it is used in the type of a theorem and/or "have" expression.
This happened in the algebraic hierarchy. Recall that Floris also had problems with it.

**Comment by fpvandoorn** [comment]
> It produces counter intuitive behavior if for example it is used in the type of a theorem and/or "have" expression.

Do you have an example of this after we made it an `abbreviation`?

> Recall that Floris also had problems with it.

What are you referring to here? I don't recall any problems with it after we made it an `abbreviation`.

---

In the last few days I've had a couple of cases where the old behavior would have been useful. I'll post an example tomorrow.

**Comment by leodemoura** [comment]
> Do you have an example of this after we made it an abbreviation?

The first problem I encountered was the "trace" of the abbreviation. 
The term `(t : A)` is notation for `@typeof A t`. Then after we expand `typeof`, we get

``` lean
(lambda (A : Type) (a : A), t) A t`.
```

We don't beta-reduce it because we use the lambda when pretty printing abbreviations.
If we beta-reduce we would also loose the `p 4` data at

``` lean
check (H : p 4)  -- p (2 + 2)
```

There is a second problem. We only expand the abbreviations after the declaration is fully elaborated. Then, I had a problem with `have`-expressions

``` lean
have aux : (1 : A) = t, from ...
```

The term is not really what we expect since the abbreviation has not been eliminated when we try to  use `aux` inside the theorem.

> > Recall that Floris also had problems with it.
> > What are you referring to here? I don't recall any problems with it after we made it an abbreviation.

I was referring to adding annotations around terms. You changed `(t : A)` to use an abbreviation because extra data was creating problems. 
I agree that moving to abbreviation minimizes the issue, but it doesn't solve it completely. 

> In the last few days I've had a couple of cases where the old behavior would have been useful. I'll post an example tomorrow.

We can still use the previous approach. We just need to use a different notation for it.

I think the default behavior for `(t : A)` should not leave any "trace". The `A` is just a hint. 
I think this is the most common case.

**Comment by fpvandoorn** [comment]
I agree now that it is better to not leave a trace at all. We can still use the previous approach with an explicit lambda.
