### ISSUE TITLE
rewrite at {n}

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#686]
The following rewrite doesn't appear to work:

```
lemma upto_step : ∀ {n : nat}, upto (succ n) = (map succ (upto n))++[0]
| 0        := rfl
| (succ n) := begin rewrite [upto_succ at {2}] end
```

But this works correctly:

```
lemma upto_step : ∀ {n : nat}, upto (succ n) = (map succ (upto n))++[0]
| 0        := rfl
| (succ n) := begin apply eq.symm, rewrite [upto_succ] end
```

**Comment by leodemoura** [comment]
You can also use

``` lean
rewrite [{upto (succ n)}upto_succ] 
```

The notation `{}` allows us to specify a pattern. When it is not provided, the left hand side of the equation is used.

**Comment by htzh** [comment]
I think I understand what is going on. `upto_succ` takes an argument. When it is not provided it binds with the first pattern that matches, and then use the **bound** argument to look for further occurrences. Because the two subterms have different arguments it does not consider the second one to be the second occurrence. The following works correctly by explicitly binding the argument desired:

```
lemma upto_step : ∀ {n : nat}, upto (succ n) = (map succ (upto n))++[0]
| 0        := rfl
| (succ n) := begin rewrite [upto_succ n, map_cons, append_cons, -upto_step] end
```

It may make sense to give some feedback in the failed case? Right now it silently succeeds without doing anything.

**Comment by leodemoura** [comment]
> The following rewrite doesn't appear to work:

The semantics of the rewrite tactic.
1- Find a subterm `t` that matches the given pattern or the left-hand-side of the equation.
2- Compute the new `t'`.
3- Replace `t` with `t'`. If `at` is not provided, then all instances of `t` are replaced. Otherwise only the specified ones.

This may not be the ideal semantics, but it is the one that is currently implemented.
So, in you first declaration, `rewrite` finds the subterm `upto (succ (succ n))`. There is only one occurrence of this term, so nothing happens with a `at {2}`. We should have signed an error instead of silently doing nothing.

It is not clear that the ideal semantics for `at {i}` is: pick the ith match.
First, `at` allows many indices (e.g., `at {2, 4}`). Moreover, sometimes we really want to simultaneously change many instances of a term `t`.

**Comment by leodemoura** [comment]
Sorry, I was writing the previous message while you were writing the second message.

> It may make sense to give some feedback in the failed case? Right now it silently succeeds without doing anything.

Yes, we should sign the failure.

**Comment by htzh** [comment]
> Sorry, I was writing the previous message while you were writing the second message.

:-)
