### ISSUE TITLE
instance inference

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#687]
The following inductive or match definitions only work with the nat annotation on the cases:

```
section rot
open nat fin eq.ops algebra

definition rotr₁ {n : nat} : fin n → fin n := match n with 
| (0:nat)      := take i, elim0 i
| (nat.succ k) := madd (-maxi)
end

definition rotr₂ : ∀ {n : nat}, fin n → fin n
| (0:nat)        := take i, elim0 i
| (nat.succ n) := madd (-maxi)

end rot
```

Even enclosing the definition in its own section still requires annotation of succ:

```
section
open nat
definition rotr : ∀ {n : nat}, fin n → fin n
| 0      := take i, elim0 i
| (nat.succ n) := madd (-maxi)
end
```

Otherwise group over `madd` is not inferred.
None-inductive definition does not have the same problem:

```
definition rotr {n : nat} : fin (succ n) → fin (succ n) := madd (-maxi)
```

works.

**Comment by leodemoura** [comment]
This is one is quite tricky. We have overloaded notation
- `0` can be `nat.zero` or `algebra.has_zero.zero`
- `succ` can be `nat.succ` or `fin.succ`

We have coercions : num->nat, nat->int, num->int, num->fin, fin->nat

Note that `int` is being imported indirectly (and its coercions are in the top-level).

We need to use type class resolution for elaborating `-maxi`, `fin` does not define `-`. So, in this example, Lean is actually using `algebra.has_neg.neg`.

Another problem is that the library is not uniform. Example, in `nat` we migrate the algebra theorems and definitions. In the `fin` module, we have the instance `madd_is_comm_group : add_comm_group (fin (succ n))`. For `nat`, the coercions are in the `nat` namespace. For `int` and `fin`, they are in the top-level (so we cannot hide them).

For example, here is a possible interpretation for `0` in this example: 

```
has_zero.zero (fin ...) (comm_group_to_has_zero (madd_is_comm_group ...))
```

This is a `fin ...` type, since we have a coercion `fin->nat` we can convert it into a `nat` 

It took me several hours to understand what is going on in this issue.

@avigad @fpvandoorn I think we need to reconsider how to use coercions in the standard library.
Jeremy already pointed out that he experienced counter-intuitive behavior more than once when he mixed coercions with overloaded notation. In this issue, the trick `- [coercions]` does not work since the `fin` and `int` coercions are in the top-level.

I managed to fix this issue but the complexity is getting too high. 
Eventually, it will be too hard to understand what is happening. 

Regarding coercions between numeric types, I think we should have only num->nat, num->int, num->real by default. These are the ones that are really handy. The other ones (nat->int, nat->real, int->real, fin->nat) should be in a separate namespace, and users have to explicitly open this auxiliary namespace for using them.

I also think the concrete structures should use a uniform approach. That is, they should all migrate theorems and define their own notation; or they should all use the ones from algebra.

It would also help to have the `algebra` notation available only when we are working with abstract structures.

**Comment by avigad** [comment]
Why are the fin and int coercions currently declared at top level? If I understand correctly, we needed them there when Lean did not compute the transitive closure of the coercion graph, but that has been changed.

I agree with these two statements:

(1) Only the coercions from num should be declared at top level.
(2) Concrete structures (like fin) should not use algebra.

I will add these to my to do list (unless someone else wants to do it). 

BTW are nat and int are both open with coercions here:

  https://github.com/leanprover/lean/blob/master/library/theories/number_theory/bezout.lean

The coercions did not cause any problems. Things worked quite nicely. I will pay closer to attention to the coercions now.

**Comment by avigad** [comment]
I moved the coercion `int.of_nat` inside the `int` namespace. Absolutely nothing at all in the library broke when I did that, so I just added it to the pull request that is pending.

I started to migrate the theorems in `fin (succ n)`, and then realized that there is a problem: `fin (succ n)` depends on the parameter `n`. The `migrate` command can't handle that yet, can it?

**Comment by avigad** [comment]
I also moved the coercion `fin.val` inside `fin`. Again, no problems.

**Comment by leodemoura** [comment]
> Why are the fin and int coercions currently declared at top level? If I understand correctly, we needed them there when Lean did not compute the transitive closure of the coercion graph, but that has been changed.

The transitive closure is only being computed for the instance graph. The transitive closure of the coercion graph is still an open issue #668 

> The coercions did not cause any problems. Things worked quite nicely. 

This is a much simpler example. The namespace `algebra` was not open, and it uses only two concrete structures. The extra complication in this issue is that it is mixing: overloaded operators, coercions, and type class resolution. And the library is not defined in a uniform way.

> I started to migrate the theorems in fin (succ n), and then realized that there is a problem: fin (succ n) depends on the parameter n. The migrate command can't handle that yet, can it?

It cannot.
