### ISSUE TITLE
induction + esimp bug [2]

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#690]
Probably related to #682, the following example fails because we `esimp` only a particular assumption.

``` lean
-- HoTT
import types.sigma
open sigma sigma.ops eq
definition dpair_sigma_eq {A : Type} {B : A → Type} {u v : Σa, B a} (p : u.1 = v.1) (q : u.2 =[p] v.2)
  : ⟨(sigma_eq p q)..1, (sigma_eq p q)..2⟩ = ⟨p, q⟩ :=
begin 
  induction u,
  induction v,
  esimp at q, -- it works if we replace this by     esimp at *,
  induction q,
  reflexivity
end
```

> I'm concerned this may be a recurrent issue. 

I'm starting to get concerned about this, too.

**Comment by leodemoura** [comment]
EDIT: I forgot to include my modified version of the example. My message does not make sense without it.

``` lean
import types.sigma
open sigma sigma.ops eq
definition dpair_sigma_eq {A : Type} {B : A → Type} {u v : Σa, B a} (p : u.1 = v.1) (q : u.2 =[p] v.2)
  : ⟨(sigma_eq p q)..1, (sigma_eq p q)..2⟩ = ⟨p, q⟩ :=
begin
  induction u with u₁ u₂,
  induction v with v₁ v₂,
  esimp at q, 
  induction q, -- Should fail here since index p depends one index v₂
  reflexivity
end
```

I analyzed this issue. Fortunately, it is not related to #682.
The problem is in the code that checks whether the `induction` tactic is applicable or not.
Right now, we just check whether all indices are pair-wise distinct local constants.
In your example, the indices are: `v₁ p v₂`. 
However, since `p : ⟨u₁, u₂⟩.1 = ⟨v₁, v₂⟩.1,` was not simplified, it still depends on `v₂`.
So, the induction tactic produces an ill-formed `pathover.rec` application.
The fix is to reject `induction q` because `p`'s type depends on `v₂`.

Note that, the example also works when we execute `esimp at p, esimp at q`.

**Comment by fpvandoorn** [comment]
Yes, that makes sense. The new error message is nice!
