### ISSUE TITLE
folding inductive definitions

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#692]
Suppose we define a function `f` by induction on the natural numbers. We often want to give such `f` the `[unfold-c _]` attribute, because then `f` is simplified when it is applied to either `0` or `succ`.

However, the inductive calls of `f` should be folded back. For example, `f (succ n)` should reduce to `F n (f n)` and not to `F n (nat.rec_on n _ F)`. Example:

``` lean
-- standard
import data.nat
open nat
definition f [unfold-c 1] (n : ℕ) : ℕ := nat.rec_on n 1 (λn' p, succ (succ p))

example (n : ℕ) : f n = 2 * n + 1 :=
begin
  induction n,
  { reflexivity},
  { esimp, state, fold (f a), state, rewrite [mul_succ, v_0]}
end
```

Here the `fold` command should be done automatically.

I think we briefly discussed this in the past (although I cannot find it now), but didn't find a good solution. However, I think it is an imortant issue, since I'm now doing a lot of folding by hand:
https://github.com/fpvandoorn/lean/blob/9bb703eeec28e9f289a417f3599e22de409421a6/hott/algebra/e_closure.hlean#L99-106

Here's my idea: EDIT: This idea doesn't work
- ~~when we run `esimp`, we keep a list of items which should be folded afterwards~~
- ~~e.g. if `esimp` unfolds `f (succ n)`, we add `f n` to the list~~
- ~~after we are done with esimp, we run `try fold x` for every element `x` in the list~~
- ~~If we execute `esimp [f]` I think we should _not_ add any terms with head `f` to the list.~~
- ~~The main challenge is to determine which terms to add to the list. Difficulties:~~
  - ~~If we unfold `f (succ (succ n))` we should add `f n` but don't need to add `f (succ n)`. So we need to strip constructors until we the head of the argument is not a `[constructor]` anymore. Here `n` needs not be a variable, as long as its head is not a `[constructor]`~~
  - ~~For inductive families we should also adapt indices: If we unfold `g` in `g (succ n) (vector.cons a v)`, we should store `g n v`. The relevant indices can be read of from the type of the constructor.~~
  - ~~Unfolding/Folding should be done in the right order: if we simplify `f (succ (f (succ n)))` we want to fold both `f`'s back~~
  - ~~EDIT: another reason folding has to be done in the right order: if `g` is defined to be `f` (and both are marked with `[unfold-c]`), then `g (succ n)` should become an expression involving `g n` (i.e. `f n` has to be folded back, and then `g n` has to be folded)~~
  - ~~One unfold can lead to multiple folds, e.g. if we define~~

``` lean
inductive tree (A : Type) : Type :=
| leaf : A → tree A
| node : tree A → tree A → tree A
```

~~and we unfold `f (node a b)` we need to add both `f a` and `f b`. And of course, it can lead to zero unfolds, for example if we unfold `f leaf`~~

**Comment by leodemoura** [comment]
Random comments:
- Yes, this is a very useful feature. I usually do not use `esimp [f]` when `f` is a recursive function because we don't have this feature. My current workaround is to copy the goal into a `change` tactic, and perform the unfold by hand. I agree this is not nice. Example:
  https://github.com/leanprover/lean/blob/d43e0891ae47457dd1d2682e3fbdf6328ad84130/library/data/vector.lean#L83
- `f` may have multiple arguments. We need to know which one the recursion is on, and we need to figure out the other arguments for each recursive applications. I think "guessing" the terms would not work reliably. If we want something reliable, we have to look into the actual definition and extract the information from there. However, this can be quite tricky since users may use custom recursors. 
- For functions defined using the definitional package, we can store the hints: which recursive applications should be folded. 
- For other definitions, we can let the user provide hints. We can try to pre-compute the hints using heuristics. I think we can do it for definitions using a single builtin recursors and simple user-defined recursors. Anyway, this is a tricky problem. I guess it will take time to polish.

**Comment by fpvandoorn** [comment]
You're right. I was only working with special cases so far, but in general you cannot guess how to fold without looking at the exact definition. For example if you define:

``` lean
open nat
-- f a n = a * 2^n
definition f (a n : ℕ) : ℕ := nat.rec_on n (λa', a') (λn' f' a', f' (a' * 2)) a
```

then `f a (succ n)` reduces to `f (a * 2) n`.

> I think we can do it for definitions using a single builtin recursors [...]

That would be very helpful, and cover 90+% of all cases.

**Comment by leodemoura** [comment]
I worked today on this issue. It is quite messy.
The commit above contains one nice example.
Now, `esimp` only unfolds a recursive function if it can `fold` the recursive applications.
`unfold` always unfold. There are several rough spots.
The implementation only support builtin recursors and the automatically generated ones (e.g., `brec_on`).
I will the problems later.
