### ISSUE TITLE
define something in root namespace while in a namespace

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#699]
This is a very minor issue, but it would be nice if we could define something in the root namespace when we are currently in a namespace. This is especially useful when you're also currently in a section. Something like:

``` lean
namespace foo
  section
  definition _root_.bar := _
  end
end foo
```

Currently a workaround is to define an abbreviation after the section and namespace are closed.

**Comment by leodemoura** [comment]
I have been thinking about this one.
I think this is not a nice feature. It is adding more complexity to the namespace management system for a problem that can be solved existing features (e.g., `abbreviations` and `export` command).
In the current system, if we define `bar.boo` in the namespace `foo`, we are defining `foo.bar.boo`, but the metadata is stored in `foo` instead of `foo.bar`.
With this change, we have an exception when `bar` is `_root_`. First, the definition goes to a different place, we would also have to decide where the metadata goes. What about `_root_.bar.boo`? 

We have the `export` command for moving data and metadata across namespaces. We should use it.

BTW, we should improve the `export` command. It currently creates an abbreviation, but it should create an alias.

**Comment by fpvandoorn** [comment]
The abbreviation command doesn't completely solve the issue, since you still need to sometimes unfold abbreviations in a tactic proof. But the `export` command is indeed the best way to do this, once the export command creates aliases. I created a separate issue for that, and I will close this one.

For future reference, the following will export _only_ the name `foo.bar` to the root namespace (metadata about `foo.bar` is not exported).

``` lean
namespace foo
  definition bar := @eq
  definition baz := @eq
  attribute bar [reducible]
end foo

export [declarations] foo (bar)
```
