### ISSUE TITLE
induction using variable lists

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#701]
Whenever you write a list of variable names to be introduced into the context (e.g. `intros a b c` or `induction x with a b c`) in Coq there is a very useful notation to quickly perform case analysis on these new variables. For example, if the goal is `(A ∨ (B ∧ C)) → H`, you can use `intro [a | [b c]]` to immediately create two new subgoals `a : A ⊢ H` and `b : B, c : C ⊢ H`. 

See [section 8.3.2](https://coq.inria.fr/refman/Reference-Manual010.html#hevea_tactic35) in the Coq manual. Maybe we can implement something similar using the induction tactic?

**Comment by dselsam** [comment]
It might be nice to have some support for this in `assume` as well, e.g.

``` Lean
example (A B : Prop) : A ∧ B → ... :=
  assume [(a : A) (b : B)],
  ...
```

instead of

``` Lean
example (A B : Prop) : A ∧ B → ... :=
  assume ab : A ∧ B,
  have a : A, from and.left ab,
  have b : B, from and.right ab,
  ...
```

**Comment by leodemoura** [comment]
We have `obtain`.

``` lean
example (A B : Prop) (h : A ∧ B) :... :=
  obtain (a : A) (b : B), from h,
  ...
```

It can handle any datatype with a single constructor.
Examples:
https://github.com/leanprover/lean/search?utf8=%E2%9C%93&q=obtain

**Comment by dselsam** [comment]
That is nice. For some reason I thought `obtain` only worked for `exists`. It still seems unfortunate to need to name the compound assumption before destructing it though.

**Comment by leodemoura** [comment]
> For some reason I thought obtain only worked for exists

The new `obtain` is very recent feature. 

> It still seems unfortunate to need to name the compound assumption before destructing it though.

It is feasible to create a `assume+obtain` hybrid.
Note that, it will not subsume the current `obtain`. 
With the current `obtain`, we can write
https://github.com/leanprover/lean/blob/d28eb919f149ce64254b92218335eaa6315283b0/library/data/finset/card.lean#L79

It would be nice to use a different notation for the hybrid `assume+obtain`. In proof term mode, the `[ ... ]` may confuse Lean since it is a binder annotation.

**Comment by leodemoura** [comment]
BTW, one related issue. One thing that bothers me about the `induction` tactic is that the order of the minor premises matters. I think this produces incomprehensible proofs whenever we have many constructors. The same happens if we use the recursor/eliminator in proof term mode:
https://github.com/leanprover/lean/blob/master/library/logic/examples/propositional/soundness.lean#L113
At least in proof-term mode, we can use the definitional package and the differents cases can be provided in an arbitrary order. 
https://github.com/leanprover/lean/blob/master/library/logic/examples/propositional/soundness.lean#L113
However, this is not a full solution since the definitional package does not support user-defined recursors.

In tactic mode, we could address this issue by providing a concise way of specifying which goal we want to discharge. 

Another related issue: it would be really great to have a `induction` construct in proof-term-mode.
It would be a structured version of the `induction` tactic. Right now, if we want to use a user-defined recursor/eliminator in a convenient way, we have to switch to tactic mode.
Example:
https://github.com/leanprover/lean/blob/master/library/data/finset/card.lean#L69
A simple version would be:

``` lean
induction H
|  vars := ...
...
|  vars := ... 
```

This is not complicated to implement, but we would have to provide the different cases in the right order. Again, it would be nice to have a way to provide the different cases in an arbitrary order.

**Comment by fpvandoorn** [comment]
I agree that tactic proofs with `induction` tend to become unreadable. However, tactic proofs are unreadable most of the time anyway, since you only see one half of a dialogue between the user (providing the tactics) and Lean (providing the goals). But it can sometimes be useful to make them more readable.

For proof-term-mode, maybe we can have a syntax similar to `match-with` where all "induction hypotheses" are specified by a `with`-command.

```
induction n
| 0 := ...
| succ k with IH := ...
```

(all variables in the context should just have the name they had before, and should not be given, even if they depended on `n`).

For tactics maybe something like this is feasible:

``` lean
induction n,
  case 0, { ... },
  case (succ k) with IH, { ... },
```

Here the semantics of the `case` tactic (which might need a better name) is that it moves the goal corresponding to that case to the top of the goal list and renames any "induction hypotheses" to the given variable name. This probably requires storing some extra information with the goals (such as to which case this goal corresponds and what are the "minor premises").

**Comment by leodemoura** [comment]
@fpvandoorn any ideas on how to cover user-defined recursors? What would be a reasonable syntax for your applications? It would be nice if we could cover all the user-defined recursors we can cover with the induction tactic.

**Comment by fpvandoorn** [comment]
Oh yes, I forgot about those. It's hard to specify the minor premises for user-defined recursors, especially non-dependent ones. The only thing I can think of is identifying the minor premises by the names specified by the user. So if the recursor is

``` lean
definition circle.elim {P : Type} (Pbase : P) (Ploop : Pbase = Pbase) (x : circle) : P
```

then `Pbase` and `Ploop` refer to the different steps. But this is not very nice, and it doesn't work well for automatically generated induction principles.

**Comment by avigad** [comment]
While I am thinking of it, it would be nice to have `cases` handle nested constructors, so that instead of

``` lean
    cases foo with [y Hy],
    cases Hy with [Hy1 Hy2],
```

we could write

``` lean
  cases foo with [y [Hy1 Hy2]],
```

**Comment by leodemoura** [comment]
I'm planning to mark this feature as `postponed` and close it. Unless someone volunteers to implement it.
I will not work on it.

**Comment by avigad** [comment]
It would be nice to have prettier syntax for proof by induction and proof by cases, but it is not essential.

I think we should revisit it after we have some automation. Then we can think about how we want proofs to look.

**Comment by fpvandoorn** [comment]
That's too bad, but I understand.

**Comment by robertylewis** [comment]
This is one issue I'm sad to see go (particularly @avigad 's suggestion for cases handling nested constructors). I may take a shot at this if I have time -- it doesn't seem like it should be too tricky, although the cases tactic looks a little more complicated than I expected!

**Comment by leodemoura** [comment]
@rlewis1988 It doesn't have to go. I just said I will not do it in the near future. 
Automation is consuming and will continue to consume all my cycles. 
If you want to volunteer, we should reopen this issue.
I'm just trying to setup expectations, and close enhancements that nobody will work on in the foreseeable future.

**Comment by robertylewis** [comment]
I understand! As nice as it would be to see this implemented, more automation will be way better.

Let's leave the issue closed for now. I'll take a look soon and see what I can do.
