### ISSUE TITLE
Parameters inside tactic proofs

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#736]
The following theorem only works when the commented line is uncommented. It seems like the parameter S isn't being added to the signature of foo otherwise.

``` lean
import data.nat
open nat

section
parameter s : ℕ

theorem foo : ∃ n : ℕ, n ≥ 0 :=
  -- let t := s in
  begin
    existsi s,
    apply zero_le
  end

end
```

**Comment by leodemoura** [comment]
This is the expected behavior. 
The tactics are too dynamic, and the scope is not clear until we execute the tactic.
So, parameters appearing only inside tactics are not automatically included into the signature.
Here are some alternatives:

1- use `include` command to force a parameter to be included.

``` lean
include s
theorem foo₁ : ∃ n : ℕ, n ≥ 0 :=
  begin
    existsi s,
    apply zero_le
  end
```

2- use proof-term mode

``` lean
theorem foo₂ : ∃ n : ℕ, n ≥ 0 :=
exists.intro s !zero_le
```

3- `using` expression

``` lean
theorem foo₃ : ∃ n : ℕ, n ≥ 0 :=
using s,
begin
  existsi s,
  apply zero_le
end
```

**Comment by robertylewis** [comment]
I see. Thanks for the clarification!
