### ISSUE TITLE
Erratic behavior in *Lean Goal* buffer

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#788]
In the following example, Lean Goal displays the correct goals on each line of the (incomplete) proof:

``` lean
import data.int
open nat

example (a : ℕ) : a = a :=
  begin
    induction a,
    rewrite [-nat.add_zero]
  end
```

However, if I take the same example and paste it at the bottom of data/int/order.lean, Lean Goal will not update on the second line (or any lines added after that). Replacing -nat.add_zero with rfl makes it work, and the issue does not appear if I do the same in data/int/basic.lean.

I can't figure out what it is specifically about order.lean that's causing this...

**Comment by leodemoura** [comment]
I can't reproduce the problem. Could you please include a link to the modified `data/int/order.lean` that triggers the problem? Then, could you provide the precise line/col numbers where you are pressing `Ctrl-c-Ctrl-g`. 

Thanks, Leo

**Comment by robertylewis** [comment]
https://gist.github.com/rlewis1988/1927c0c07dea8bda25cf

Line 393. A bit more info: I completed the proof, saved, quit and restarted emacs, and tried again; the issue was gone. When I deleted the lines I added to finish the proof, the issue returned.

**Comment by leodemoura** [comment]
I still can't reproduce the problem.

> When I deleted the lines I added to finish the proof, the issue returned.

which lines?

**Comment by robertylewis** [comment]
Sorry, that explanation was unclear.

I produce the problem, and then complete the proof:

``` lean
example (a : ℕ) : a = a := begin
  induction a,
  rewrite [-nat.add_zero],
  apply rfl
 end
```

The issue is still present: C-c C-g only works on the line "induction a".
Then I save and restart emacs. The problem is gone (C-c C-g prints the goals on all lines of the proof). I delete the line "apply rfl", and the problem returns.

I'll try this on a fresh clone of the repo. But I don't think I have any relevant local changes.

**Comment by robertylewis** [comment]
@soonhokong, were you able to reproduce?

**Comment by robertylewis** [comment]
Confirmed, I still have the problem on a completely fresh build.

**Comment by soonhokong** [comment]
@rlewis1988, not yet. Do you have a small and self-contained example? I was using the following example and it seems that it's working even after I delete the line `apply rfl`..

``` lean
import standard
example (a : ℕ) : a = a := begin
  induction a,
  rewrite [-nat.add_zero],
  apply rfl
end
```

**Comment by leodemoura** [comment]
I managed to reproduce the problem by adding and removing the `apply rfl` line.
@soonhokong I think the problem is on the Emacs side. I get the correct answer when I use the command line options `--goal --line=<num> --col=<num>`.
I think there is a race condition. `flycheck` is running on the background and is updating the cache file `.clean`. In the meantime, lean-mode starts another lean process for extracting the goal, and this process is trying to read the `.clean` that is being updated by the `lean` process being executed by `flycheck`.
I think this is another instance of the race condition problem I told you about when you visited MSR.

**Comment by soonhokong** [comment]
@leodemoura, I see.. For now, `C-c C-g` is using cache if the buffer is not modified. Otherwise, the buffer is first saved to a temporary file and `lean` is called without `--cache` option.

What could be a solution for this?
1. do not use cache with `C-c C-g`.
2. we can postpone the execution of `C-c C-g` until the flycheck is completed.
3. a hybrid of  1 and 2: if flycheck process is running, wait for n sec, if it's still running, do not use cache..

**Comment by leodemoura** [comment]
I think option 1 is really bad. `C-c C-g` would be way less responsive.
Option 2 is better, and seems to be a good compromise for now.

In the long term, I think we will have to implementation a "compilation server" for Lean.
This server would take care of recompiling dependencies, updating the cache files, and handling requests using the command line options `--goal --line --col`.

**Comment by soonhokong** [comment]
@leodemoura, I see. I'll implement option 2, issue #790. @rlewis1988, I'm closing this one. Please follow #790.

**Comment by robertylewis** [comment]
Ah, great- glad you were able to find the issue! Option 2 sounds perfectly reasonable to me. I would have guessed that things worked that way already.

**Comment by soonhokong** [comment]
@leodemoura and @rlewis1988, I can confirm that this is due to the location of a temporary file that lean-mode generates.
- Copy `library/data/int/order.lean` to a temp directory (outside of library dir).
- Add the above 'example' at the bottom of the copied file
- Run `lean --lean --line 396 --col 7 --goal <tmp_file>`.

It gives the following errors:

```
 /var/folders/wz/6j2w2jp510g6b0ty330hqs7r0000gn/T/flymake4181yL2lean
/var/folders/wz/6j2w2jp510g6b0ty330hqs7r0000gn/T/flymake4181yL2lean:9:8: error: invalid import, unknown module 'basic'
/var/folders/wz/6j2w2jp510g6b0ty330hqs7r0000gn/T/flymake4181yL2lean:12:5: error: invalid namespace name 'int'
/var/folders/wz/6j2w2jp510g6b0ty330hqs7r0000gn/T/flymake4181yL2lean:16:31: error: unknown identifier 'ℤ'
/var/folders/wz/6j2w2jp510g6b0ty330hqs7r0000gn/T/flymake4181yL2lean:17:21: error: unknown identifier 'ℤ'
...
```

It failed to handle the first import `.basic`.

**Comment by soonhokong** [comment]
I'll make a quick-fix to make a temporary file under the same directory. I think I had some issues with this solution previously. But now I don't recall them..

**Comment by leodemoura** [comment]
@soonhokong 
One possibility is to add a new option that specifies the current directory.
Something like `lean --lean --dir=~/project/lean/library/data/int --line=396 --col=7 --goal <tmp-file>`
When the option is not provided, Lean will assume the current directory is the directory where the file is located. What do you think?

**Comment by soonhokong** [comment]
@leodemoura, I like it!
