### ISSUE TITLE
Namespaces and choice

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#792]
The following works:

``` Lean
open nat
definition zero := bool.ff
eval zero + succ zero
```

if and only if there are no active namespaces. The reason is that if a name is found in an active namespace, it is committed to without the possibility of choice:

https://github.com/leanprover/lean/blob/master/src/frontends/lean/parser.cpp#L1271-L1281

while on the other hand if an exact name is given, aliases are tried as backup options:

https://github.com/leanprover/lean/blob/master/src/frontends/lean/parser.cpp#L1297-L1310

What is the rationale for the different behavior?

**Comment by leodemoura** [comment]
> The reason is that if a name is found in an active namespace, it is committed to without the possibility of choice

Correct. This is important in a couple of places. One example is notation declaration.
Suppose we are defining `real`, and the symbol `add` is overloaded: `nat.add`, `int.add`, ...
When declare the notation 

``` lean
infix + := add
```

we want it to be 

``` lean
infix + := real.add
```

instead of a choice `nat.add | int.add | rat.add | real.add`.
This is also the semantics in some programming languages.

> while on the other hand if an exact name is given, aliases are tried as backup options:

I agree this is hackish, but I think it is quite useful. 
For example, we have a type called `empty`.  It is defined in the top-level. 
Without this mechanism, we would not be able to use `empty` to refer to the `finset.empty` and `set.empty` since it would always refer to the `empty` type.

If we remove this hack, we should definitely rename the `empty` type to something else (e.g., `empty_type`). 
BTW, `empty` is not the only case. There are other problematic names.

**Comment by dselsam** [comment]
I think the semantics of implicitly "opening" `init` are intuitive. What I think some users may find confusing is that their own definitions are immediately treated differently depending on whether or not a namespace is active. I think the current version is fine, but another (possibly worse) option might be to also commit if the exact name is found in the current module.

**Comment by leodemoura** [comment]
> I think the current version is fine, but another (possibly worse) option might be to also commit if the exact name is found in the current module.

@avigad @fpvandoorn What do you think?
I'm on the fence. I agree with Daniel that the current semantics is confusing.
The solution, in the quote above, minimizes the problem, but it is also not perfect nor uniform.

I don't see a good alternative. All alternatives considered here have some problem.

**Comment by avigad** [comment]
I have thought about this for a minute or two, but I am finding it hard to form an opinion. In all the time I have been using Lean, I don't think I have ever come across something I took to be unintuitive in this regard.

The proposal only seems to effect a very special case, e.g. I define "empty" at top level in the current file and there is also finset.empty in the context.

I would suggest leaving it alone until someone has a strong opinion that it should be changed.

**Comment by leodemoura** [comment]
I'm marking it as "postponed", and closing it.

**Comment by fpvandoorn** [comment]
I also think that although the current behavior is not uniform, it is intuitive, so I'm fine keeping it the way it is.
