### ISSUE TITLE
Any thoughts on matrix inverses?

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#804]
Similar to #650, there are many options for representing matrix inverses. I'll list a few that come to mind.

``` Lean
definition inverse_of (M : matrix A n n) (N : matrix A n n) :=
M * N = I ∧ N * M = I
```

(1) We can use type-class inference to propagate `∃ N, inverse_of M N` along e.g. multiplication and transpose, and then use classical choice:

``` Lean
definition invertible [class] (M : matrix A n n) :=  ∃ N, inverse_of M N
noncomputable definition inverse (M : matrix A n n) := classical.epsilon (inverse_of M)
notation A⁻¹ := inverse A 
lemma inverse_spec (M : matrix A n n) [M_invertible : invertible M] 
: inverse_of M M⁻¹ := classical.epsilon_spec M_invertible
```

Pros: simple
Cons: does not compute, returns meaningless matrix if not invertible.

(2) We can use type-class inference to propagate a proposition that a specific inverse algorithm takes as an argument, and then use that algorithm itself:

``` Lean
definition invertible [class] (M : matrix A n n) := det M ≠ 0
definition compute_inverse (M : matrix A n n) [M_invertible : invertible M]
:= (det M)⁻¹ * adjugate M
notation A⁻¹ := compute_inverse A 
lemma inverse_spec (M : matrix A n n) [M_invertible : invertible M] 
: inverse_of M M⁻¹ := ... -- an actual proof
```

Pros: constructive
Cons: no algorithm choice

(3) We can use type-class inference to propagate the actual inverse as data, and can toggle between inverse algorithms by setting priorities for the base case:

``` Lean
definition invertible [class] (M : matrix A n n) := Σ N, inverse_of M N
definition project_inverse (M : matrix A n n) [M_invertible : invertible M]
:= M_invertible
notation M⁻¹ := (project_inverse M).1
lemma inverse_spec (M : matrix A n n) [M_invertible : invertible M] 
: inverse_of M M⁻¹ := (project_inverse M).2
```

Pros: constructive, algorithmically flexible
Cons:  `M⁻¹` may not be definitionally equal `M⁻¹`

(I haven't given up hope that subsingleton-equality can be handled nicely in the elaborator, though maybe I am alone on this.)

There are of course several other options as well. One of the main design issues seem to be how much to support computing using the same symbols and data-structures we use for math. One hypothesis is that they are such separate endeavors that one should switch to an entirely different mode when one needs to compute efficiently. 

Any thoughts?

**Comment by dselsam** [comment]
After browsing the existing ring theory, I think talking about matrix inverses is skipping a step, since there does not seem to be any support yet for multiplicative inverses for general rings, so e.g. `(det M)⁻¹` is not even defined. What do you think about the sigma-type approach for general rings, e.g.:

``` Lean
variable {A : Type}
variable [r : ring A]
include r

definition invertible [class] (x : A) := Σ y, x * y = 1 ∧ y * x = 1
definition invertible_1 [instance] : invertible (1:A) := ...
definition invertible_prod [instance] (x y : A) 
[x_inv : invertible x] [y_inv : invertible y] : invertible (x * y) 
:= ...

definition project_inverse (x : A) [x_inv : invertible x]
:= x_inv
notation x⁻¹ := (project_inverse x).1
```

Then we can define:

``` Lean
definition matrix.compute_inverse [instance] (M : matrix A n n) 
[M_inv : invertible (det M)] : invertible M
:= sigma.mk ((det M)⁻¹ * adjugate M) <proof>
```

and bootstrap on the generic ring notation. Or we could switch everything to `Prop` and use choice.

**Comment by avigad** [comment]
The first post is a very nice presentation of the options. 

For the (classical) analysis library, we will to go with (1) for things like limits, derivatives, etc., because we are not worrying about computation there.

You've accurately captured my concern about (3), i.e. carrying data in implicit arguments. It would be nice if it could be made to work, but I don't have a sense of how hard it will be to overcome the problems.

What is the con for (2)? It seems like a good solution. Do you mean that we have to commit to a particular algorithm in the definition?

As far as the second post, one concern is that field inherits from ring, so we'd have to either unify the notations for inverse or let the user load one or another. One option is to axiomatize a class of rings with an invertibility predicate and an inverse, similar to our axiomatization of field. We can make the inverse a total function, but stay silent about what it does on noninvertible elements (or declare that their inverses are all 0, if that is more convenient).

It seems that with (2) above and this approach, we can make the theory e.g. matrices over Q constructive. After all, invertibility is decidable, and we can define the inverse to be 0 on noninvertible elements. It would be nice to do this, I think, even if the computation is not efficient enough to be feasible. Getting a good computational theory eventually seems to be within reach.

**Comment by leodemoura** [comment]
> (I haven't given up hope that subsingleton-equality can be handled nicely in the elaborator, though maybe I am alone on this.)

You are not alone :-)
I didn't give up either.

That being said, the `matrix` type should be viewed as a "reference type" for matrices.
We are defining it as `fin n -> fin m -> A`. 
Similarly, `nat` is the reference type for natural numbers.
Both of them are simple, but do not have good computational behavior.  
So, I think it is not very useful to support multiple implementations.
In the long term, we will define "efficient representations" for theses types (e.g., a sparse representation for matrices), prove equivalences between them, and transport results/theorems.

**Comment by dselsam** [comment]
I just noticed that in a `field`, the inverse operator is total. I was expecting that it would only be defined on non-zero elements, with type-classes propagating that property. My previous posts on this issue assumed that it would not be acceptable to ever return a nonsense value, such as returning the zero matrix as the inverse of a non-invertible matrix. If the accepted style in the algebraic hierarchy is to use total functions and return nonsense when an output is not defined, then we may as well do the same for matrices. 

So here is a fourth option, close to the approach taken in the mathematical components library:

``` Lean
definition inverse (M : matrix A n n) := (det M)⁻¹ * adjugate M
notation A⁻¹ := inverse A 
lemma inverse_spec (M : matrix A n n) : det M ≠ 0 → inverse_of M M⁻¹ 
:= ... -- an actual proof
```

The behavior of `inverse` on non-invertible matrices will depend on the behavior of `inverse` in the underlying ring or field, and we can at least avoid injecting any additional arbitrariness.

Does this work for everybody?

**Comment by avigad** [comment]
Yes, I think this is the right way to go. If you decide at some point to axiomatize rings-with-inverses, this would be a natural instance.

**Comment by dselsam** [comment]
Great, I'll implement it next week, over fields to start.
