### ISSUE TITLE
overloaded numerals

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#808]
``` lean
notation 1 := eq
postfix `x`:(max+1) := eq
postfix [priority 1] `y` := eq
definition foo [priority 1] := @eq
definition bar [unfold 1] := @eq
```

gives the following errors

```
unexpected occurrence of 'choice' expression
invalid priority expression, it contains overloaded symbols
invalid priority expression, it contains overloaded symbols
```

(`[unfold 1]` is accepted)

**Comment by dselsam** [comment]
There are a few issues here.

First, it is strange that the precedence and priority errors give different error messages. The issue is that when parsing priorities, we check for choice expressions:

https://github.com/leanprover/lean/blob/master/src/frontends/lean/util.cpp#L459-L463

but do not when parsing precedences, so that it fails later during `whnf` when trying to expand a choice macro.

Second, I think that those uses should be accepted, and that we should ignore overloaded numerals when parsing precedences and priorities. Right now `parse_numeral_expr` takes `user_notation` as an argument:

https://github.com/leanprover/lean/blob/master/src/frontends/lean/parser.cpp#L1535

but the entry-point when parsing precedences and priorities is `parse_expr`:

https://github.com/leanprover/lean/blob/master/src/frontends/lean/notation_cmd.cpp#L44
https://github.com/leanprover/lean/blob/master/src/frontends/lean/util.cpp#L458,

so we cannot pass `false` without threading it through `parse_expr`. However, it would be easy to add `m_user_notation` to the `parser` class and use fluid lets instead.

Third, `[unfold 1]` works because it is not trying to parse an expression, only a numeral. So the following gives the sensible error:

``` Lean
definition x := 1
definition bar [unfold x] := @eq -- error: (small) natural number expected
```

**Comment by leodemoura** [comment]
@dselsam Thanks for analyzing the problem. It was very helpful.
