### ISSUE TITLE
Syntax highlighting in "set_option pp.universes true"

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#837]
This is a minor issue if there every was one: When I type the line above, lean-emacs doesn't seem to recognize pp.universes as a keyword (?) and colors it differently to when I type e.g. "set_option set_option class.trace_instances true".

**Comment by leodemoura** [comment]
> This is a minor issue if there every was one: When I type the line above, lean-emacs doesn't seem to recognize pp.universes as a keyword (?) 

I fixed this one. The issue is that there is a conflict between two different highlighting directives.
`universes` is a keyword and we instruct emacs to highlight the identifier occurring after `set_option`.

> and colors it differently to when I type e.g. "set_option set_option class.trace_instances true".

This is expected. `class.trace_instances` is not a keyword. We have a single `set_option` highlighting directive, we simply highlight the identifier occurring after `set_option`.

**Comment by soonhokong** [comment]
@leodemoura, thank you!

**Comment by fpvandoorn** [comment]
I'll also try to fix some other syntax highlighting bugs I've encountered myself.

Question: Which of the following do we want to add to `lean-constants`?
- all notation defined in the standard or HoTT library
- `|` or `:`
- digits
