### ISSUE TITLE
coercions + implicit arguments

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#851]
Below, the first example works, but if we add a coercion to `[fun-class]` the example fails, even if we give all implicit arguments explicitly. Is this a bug?

``` lean
-- HoTT
example (A : Type) : Π{a : A}, a = a :=
begin exact sorry end

open equiv.ops

print coercions

example (A : Type) : Π{a : A}, a = a :=
begin exact sorry end

example (A : Type) : Π{a : A}, a = a :=
begin exact @sorry (Π{a : A}, @eq A a a) end
```

**Comment by leodemoura** [comment]
No, this is not a bug, and it is not really related with coercions.
For example, we also get an error in the following example.

``` lean
example (A : Type) : Π {a : A}, a = a :=
begin exact @sorry (Π {a : A}, @eq A a a) end
```

Recall that the elaborator preprocessor automatically adds a `_` after `t` IF the type of `t` can be inferred at preprocessing time, and it is of the form `Pi {a : A}, ...`.

First example works because the type of `sorry` is unknown at preprocessing time. So, no `_` is added.

Second example fails because Lean postpones the elaboration of `sorry` until it can decide whether a coercion around it is needed or not. When we finally process `sorry`, Lean knows the type is of the form `Pi {a : A}, ...`.

Third example fails because we are explicitly providing the type of the sorry as `Pi {a : A}, ...`.
It will work, if we write

``` lean
example (A : Type) : Π{a : A}, a = a :=
begin exact @sorry (Π (a : A), a = a) end
```

It also works if we write:

``` lean
open equiv.ops

example (A : Type) : Π {a : A}, a = a :=
begin exact @sorry (Π (a : _), _) end  -- just changing the binder annotation to `( )`
```
