### ISSUE TITLE
Tricky elaboration problems

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#856]
Every once in a while the elaborator fails for a mysterious reason, though I am usually able to print everything and add implicit arguments to work around these failures. I think that given the extreme difficulty of the elaboration problem, these workarounds are completely reasonable, and it is rarely worth even trying to figure out why elaboration failed. 

To reiterate, I am not suggesting we try to investigate more deeply nor modify the elaborator at all. However, there might come some point in the future where somebody might want to try to do so, and these problematic cases seem like they might eventually provide some value.

Is there any sense in setting up a wiki as part of this repository where users can post elaboration problems that failed for mysterious reasons?

**Comment by avigad** [comment]
It couldn't hurt. Is it hard to set up a wiki?

**Comment by javra** [comment]
Wasn't there a plan to set up some contrib repository for lean code that is in some way interesting but should not go in the standard library? I think such a repo could also include slow or non-compiling theories.

**Comment by fpvandoorn** [comment]
> Is it hard to set up a wiki?

Nope: On Github you get a wiki automatically with a repository, there is an icon below the "issues" and "pull requests" icon.

However, I'm afraid that if we add a wiki page where we post such elaboration problems there is an implied obligation to look at them at some point, which (to quote Daniel) is rarely worth it.

**Comment by avigad** [comment]
@javra I think it would be a good idea to eventually set up a contrib repository. Maybe we should wait until the core library is a little more settled (it is getting there) and the user base is a little bigger.

Regarding a Wiki, I have no strong feeling about this. We have an extras/ folder, so a less prominent solution is to put an "elaboration_examples" folder there. If it just gathers dust for a while, we can eventually delete it.

**Comment by leodemoura** [comment]
The contrib folder is a good idea. However, I think it is too early for that. 
We need major some refactoring in several parts of the code base:
- Simplify elaboration process (suggestions are welcome).
- `have`-expressions as checkpoints (i.e., the new elaborator should elaborate the type/proof of the `have` before elaborating the body) BTW, several proofs in the libraries will break with this change.
- Transparent `let`-expressions in tactic mode, and make sure they are visible in tactic mode.
- Simplify `calc` mode (it should be based on `simp` instead of higher-order unification and `eq.rec`)
- Reduce complexity of the standard library using `blast` and `simp`
- ...
  My point is that it would be hard to keep up with all these changes in a separate repository.
  We have to put Lean in a stable state first.

Daniel and I are working on `blast/simp`. I think it will take several months to make it stable and robust. There is nobody else is actively working on the code base. So, all issues above are in the TODO list.

Regarding a Wiki, I don't have time to read/investigate any new problem. 
We know the elaboration step is very brittle, and it has many open issues.
I think we should fix the issues listed above before listing the new problems in a Wiki.

**Comment by avigad** [comment]
A minor comment regarding this:
- have-expressions as checkpoints (i.e., the new elaborator should elaborate the type/proof of the have before elaborating the body) BTW, several proofs in the libraries will break with this change.

I think this is a good thing to do. One thing that would make it easier would be to have a "have ..., from+ ..." that duplicates the old behavior. It is not elegant, but at least we will be able to fix many of the more subtle problems that way.

**Comment by leodemoura** [comment]
@avigad Yes, this is a good idea.

**Comment by leodemoura** [comment]
I'm closing this issue, it seems we reached a consensus, and there is no real issue.
We can reopen if we want to discuss more.
