### ISSUE TITLE
Code compiles in web version but does not in the native one

### ISSUE THREAD

**Issue by bbentzen** [leanprover/lean3#857]
I just found that the following lemma `apconc` does not compile on the native version, but works perfectly fine in the web version of Lean:

``` javascript
lemma path_conc {A : Type} {x y z: A} (p : x = y) (q : y = z) : x = z := eq.rec_on q p

lemma ap {A B : Type} {x y : A} (f : A → B) (p : x = y) : f x = f y := eq.rec_on p (eq.refl (f x))

lemma apconc {A B : Type} {x y z : A} {f : A → B} {p : x = y} {q : y = z} : ap f (path_conc p  q) = path_conc (ap f p) (ap f q) :=
    calc
    ap f (path_conc p  q) = ap f (path_conc p  q) : rfl
    ... = eq.rec_on (path_conc p  q) (eq.refl (f x)) : ap f (path_conc p  q)
    ... = path_conc (ap f p) (ap f q) : path_conc p q

/- type error in placeholder assigned to
  λ (A : Type) (B : Type) (x y z : A) (f : A → B) (p : x = y) (q : y = z),
    ap f (path_conc p q)
placeholder has type
  f ?M_3 = f ?M_4
but is expected to have type
  ?M_9
the assignment was attempted when processing
    none of the overloads is applicable: ap eq.ap -/
```

I wonder why it is happening. Is this a bug or both versions simply don't have the "same output for the same input" as I expected?

**Comment by soonhokong** [comment]
1. The javascript version is outdated (was updated Sep 4). I'll updated it by Monday.
2. Which version of lean are you using? I just check that the above example compiles without a problem. I'm using `Lean (version 0.2.0, commit d508ceccecf8, Release)`. You can check the version via `lean -v` command.

**Comment by robertylewis** [comment]
This example is valid in standard (non-HoTT) Lean, which is what the browser Lean implements. It only fails for me if I save it as a .hlean file.

**Comment by bbentzen** [comment]
That's true indeed. In my example I was using a .hlean file. I just saved it as a .lean file and it worked.

But I suppose it should work as a .hlean file too isn't?

**Comment by soonhokong** [comment]
@bbentzen wrote:

> Is this a bug or both versions simply don't have the "same output for the same input" as I expected?

There are some limitations in the current Javascript version:
- It only supports the standard (non-HoTT) Lean (at least, for now).
- It only loads a subset of the standard libraries. Specifically, it loads every subdirectory under `library` except `theories`. This is due to the size of `lean.js` file.

**Comment by soonhokong** [comment]
@bbentzen wrote:

> But I suppose it should work as a .hlean file too isn't?

@fpvandoorn, could you help?

**Comment by bbentzen** [comment]
Thanks for the information, @soonhokong

I'm pretty sure my version of Lean is the newest one. How do I use the `lean -v` command in the emacs more?

**Comment by robertylewis** [comment]
I'm not really familiar with HoTT Lean, so hopefully Floris or @javra can chime in. But since the equality rules are quite different, I can imagine that calc mode needs to be used differently.

Putting your second justification `ap f (path_conc p  q)` in curly brackets `{ap f (path_conc p  q)}` makes that line go through. The curly brackets tell Lean to substitute the justification into the previous line, instead of just trying to use transitivity. (I think standard Lean will automatically try this if its first shot fails.) I can't find a simple fix like this for the third line though.

**Comment by soonhokong** [comment]
@bbentzen 

> I'm pretty sure my version of Lean is the newest one. How do I use the lean -v command in the emacs more?

We don't have an emacs-command for checking lean version, yet. You need to do it in the command-line. But, at this point, I'm pretty sure that this is not a version issue.

**Comment by avigad** [comment]
@bbentzen, I do not understand the proof that you have in mind. The reason that it works in the standard library is that there equality is "proof irrelevant," so any two equality proofs that establish the same equality are definitionally equal. So, in fact, this simpler proof also works:

``` lean
lemma path_conc {A : Type} {x y z: A} (p : x = y) (q : y = z) : x = z := eq.rec_on q p

lemma ap {A B : Type} {x y : A} (f : A → B) (p : x = y) : f x = f y := eq.rec_on p (eq.refl (f x))

lemma apconc {A B : Type} {x y z : A} {f : A → B} {p : x = y} {q : y = z} : ap f (path_conc p  q) = path_conc (ap f p) (ap f q) :=
eq.refl _
```

In HoTT, the standard way to prove the identity you are trying to prove is to use equality induction. So, in a .hlean file, this works:

``` lean
definition path_conc {A : Type} {x y z: A} (p : x = y) (q : y = z) : x = z := eq.rec_on q p

definition ap {A B : Type} {x y : A} (f : A → B) (p : x = y) : f x = f y := eq.rec_on p (eq.refl (f x))

definition apconc {A B : Type} {x y z : A} {f : A → B} {p : x = y} {q : y = z} : ap f (path_conc p  q) = path_conc (ap f p) (ap f q) :=
eq.rec_on q (eq.rec_on p (eq.refl _))
```

The proof "contracts" both p and q to the identity path. 

Notice also that in HoTT, you should use "definition" instead of "lemma". Using "lemma" makes the definition opaque while the file is being checked.

I hope this helps.

**Comment by fpvandoorn** [comment]
Jeremy is exactly right. Also, take a look at [init.path](https://github.com/leanprover/lean/blob/master/hott/init/path.hlean) in the HoTT library, where we proof similar theorems.

**Comment by bbentzen** [comment]
@avigad 

> Notice also that in HoTT, you should use "definition" instead of "lemma". Using "lemma" makes the definition opaque while the file is being checked.

That's interesting. Is it just a good practice or it actually helps the elaborator?

(`apconc` is lemma 2.2.2 (i) of HoTT book (p.93).)

Thanks!

**Comment by fpvandoorn** [comment]
> That's interesting. Is it just a good practice or it actually helps the elaborator?

Lemmas, theorems and propositions are never unfolded, so if you rely on a definition reducing, you should make it a definition. In your example, you really need to unfold `ap` and `path_conc` to define `apconc`, so `ap` and `path_conc` must be definitions (and if you want to later prove coherence properties of `apconc`, you also need to make that a `definition`.

One reason for this is that in the web version, we do not load any of the proofs for lemmas, theorems and propositions to reduce the file size, so we need to make sure that a definitions doesn't depend on how you proved a particular theorem.

**Comment by bbentzen** [comment]
I see, thanks!
