### ISSUE TITLE
Type class inference fails with multiple namespaces open

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#869]
I think I remember some discussions related to this when the new typeclass mechanism was under development. (I can't find the email now, though.) The following examples work only if the real namespace is not open. Once you open real, Lean fails to find the correct instances for int. The instance int.int_has_mul is still present.

``` lean
import data.int data.real
open int real -- if you don't open real, there are no issues
example : has_mul ℤ := _ -- works
example : (1 : ℤ) * (1 : ℤ) = (1 : ℤ) := sorry -- cannot synthesize has_mul ℤ
example : (1 : ℤ) * 1 = 1 := sorry -- cannot synthesize has_mul ℤ or has_one ℤ
```

**Comment by robertylewis** [comment]
A related problematic example ( @leodemoura , this is the root of what I emailed about yesterday):

``` lean
import data.int
open int algebra
example : has_mul int := _ -- works only when algebra is not open
```

**Comment by avigad** [comment]
It occurs to me that it might be valuable to have an explanation of the problem in the public record, so I am taking the liberty of pasting in information from two Leo's e-mails.

---

e-mail from Leo on November 11, 2015:

The problem is that there are many coercions being defined in the namespace algebra.
Several of them are explicit, and others are implicit (when we define a sub-structure).

The elaborator uses the following procedure to decide whether a coercion must be considered or not.
Suppose the expected type is A and the given type is B.
1-     If A and B are not meta-variables and do not match, then try coercion at preprocessing time.

2-     If A is a meta-variable, and there are coercions from B, then add choice-point

3-     If B is a meta-variable, and there are coercions to A, then add choice-point

In Rob’s example, A is (has_mul int) and B is a meta-variable (case 3).
The choice-point derails the elaboration process and is preventing the type class resolution from running.
This only happens when the namespace algebra is opened since all coercions are defined there.

One source of complexity is mixing type class resolution and coercions.
There are very few places in the standard library where we need the coercions between algebraic structures.
They are only needed when we want to bypass the type class resolution procedure and provide the instance manually without coercing manually (Arghhh…)
Here is a place where this happens:

definition ordered_comm_group.to_ordered_cancel_comm_monoid [trans_instance] [reducible]
    [s : ordered_comm_group A] : ordered_cancel_comm_monoid A :=
⦃ ordered_cancel_comm_monoid, s,
  add_left_cancel       := @add.left_cancel A s,
  add_right_cancel      := @add.right_cancel A s,
  le_of_add_le_add_left := @ordered_comm_group.le_of_add_le_add_left A s,
  lt_of_add_lt_add_left := @ordered_comm_group.lt_of_add_lt_add_left A s⦄

The “s” is given explicitly but it is has the wrong type and coercions are used to fix the issue.
Note that, we can completely avoid the coercions by just replacing “s” with “_” and rely on the type class resolution to synthesize these arguments.

definition ordered_comm_group.to_ordered_cancel_comm_monoid [trans_instance] [reducible]
    [s : ordered_comm_group A] : ordered_cancel_comm_monoid A :=
⦃ ordered_cancel_comm_monoid, s,
  add_left_cancel       := @add.left_cancel A _,
  add_right_cancel      := @add.right_cancel A _,
  le_of_add_le_add_left := @ordered_comm_group.le_of_add_le_add_left A _,
  lt_of_add_lt_add_left := @ordered_comm_group.lt_of_add_lt_add_left A _⦄

So, I think we should use coercions only for structures that are _not_ classes.
Mixing type class resolution and coercions seem a recipe for disaster.

We can also refine the coercion placement procedure, and never consider coercions around “_”.
I will also add a flag that disable coercions during the elaboration problem.

---

From Leo again, later that day:

I’ve submitted the following changes

1- Removed the coercions between algebraic structures in the standard and HoTT libraries.
2- Added (set_option elaborator.coercions false) for disabling coercions in the elaborator.
3- Restricted the number of places where coercions are considered.
     Now, lean will not consider a coercion around a term of the form (?m …) where ?m is a meta-variable
