### ISSUE TITLE
Funny error message for induction tactic

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#876]
In my code, I get the message

```
invalid 'induction' tactic, hypothesis 'Γ' must have a type that is associated with a recursor
proof state:
Γ : unit + Type.{?M_1}
⊢ Type.{l_2}
```

which is pretty misleading. The actual error should be a universe level related error insted (if at all?).

``` lean
open is_trunc sum

structure foo [class] :=
  (carrier     : Type)
  (to_fun      : carrier → Type)

set_option pp.universes true

definition some_foo : foo :=
begin
  fapply foo.mk,
  { exact unit + Type },
  { intro Γ, induction Γ, },
end
```

**Comment by fpvandoorn** [comment]
This is weird. I don't think this is related to universe levels. Here is a more minimal example, which doesn't have any unknown universe levels:

``` lean
set_option pp.all true
example : Σ(X : Type₀), X → unit :=
begin
  fapply sigma.mk,
  { exact unit},
  { intro x, induction x, } -- error
end
```

---

Note: in the original example, you need to give the universe variables to `some_foo` explicitly, since tactics cannot change the universe variables of a type, and you only construct a `foo` which does not live in the lowest universe level:

``` lean
definition some_foo.{u} : foo.{u+1 _} :=
begin
  fapply foo.mk,
  { exact unit + Type},
  { refine sum.rec _ _, }, -- workaround
end
```

**Comment by javra** [comment]
Yes, I figured out that I had to give the level explicitly. But somehow I wasn't able to separate the bug from that, thanks for doing that :wink:
