### ISSUE TITLE
Variable declarations in sections don't use overrode notation.

### ISSUE THREAD

**Issue by 11Kilobytes** [leanprover/lean3#957]
Consider the following code

``` lean
section test
  definition union (A : Type) (B : Type) := A + B + B
  notation A `+` B := union A B

  definition idn {A : Type} {B : Type} {C : A + B → Type} (f : Π (a : A), C (sum.inl (sum.inl a))) (a : A) : A := a
  check idn
end test
```

If you set `pp.notation = false` you see that `@idn : Π {A : Type} {B : Type} {C : union A B → Type} ...`
However, if you try to declare the parameters for idn using `variables` like this, you get a type error.

``` lean
section test
  definition union (A : Type) (B : Type) := A + B + B
  notation A `+` B := union A B

   variables {A : Type} {B : Type} {C : A + B → Type} (f : Π (a : A), C (sum.inl (sum.inl a)))
   check C
end test
```

Lean assumes `C : sum A B →  Type`, ignoring the information provided by the type of f, which demonstrates that the correct type is `C : union A B → Type`. This is a problem, since by merely declaring variables separately from the definition of a function, one can get a type error.

**Comment by avigad** [comment]
@11Kilobytes Thanks for this. I don't think this should be considered a problem, though.

Overloading is inherently problematic. Sometimes it is useful; it is nice to be able to use `+` for sum types and arithmetic, we find it convenient to use `⁻¹` to turn around an equation as well as to take an inverse, and it is nice to use `++` for concatenating lists and vectors. But it should be used sparingly, because it introduces ambiguities. So, for example, we "hide" the type constructor `+` in the `sum` namespace, and we put `⁻¹` in `eq.ops`, so they are not overloaded by default. And, in these cases, the overloads rarely cause problems, because the context makes it clear which one is meant. 

In your example, I think it is just a bad idea to use `+` for two different binary type constructors at once. It is possible to fix your example by making the new operation higher priority:

``` lean
import data.sum
open sum

section test
  definition union (A : Type) (B : Type) := A + B + B
  notation [priority std.priority.default+1] A `+` B := union A B

   variables {A : Type} {B : Type} {C : A + B → Type} (f : Π (a : A), C (sum.inl (sum.inl a)))
   check C
end test
```

But in this case, I would recommend using another token, either a new unicode character, or some funny combination of keyboard symbols like `+!+`.

Is there a compelling example where you really need such an ambiguous overload?

**Comment by 11Kilobytes** [comment]
@avigad, I don't know if this is really compelling, but originally I was constructing sum types in terms of sigma types. The definition in terms of sigma types played the role of the function `union` here. However, this is just a theoretical exercise with no practical relevance (even in pure math).

**Comment by avigad** [comment]
That sounds like a good exercise. If I understand correctly, the point is to relate the two different definitions of the sum type. If you still want to have `+` available for the original sum, I'd suggest using a notation like `+'` or `+₂`. You can do that like this:

``` lean
  infix ` +₂ `:65 := union
```

I used the same binding strength that `+` has, as defined in `library/init/reserved_notation.lean`. Adding the spaces tells the pretty printer to use the extra spaces when printing.

Alternatively, you can leave the `sum` namespace closed (or use `open - [notation] sum` to open it without the notation), and then use `sum A B` for the old sum and `A + B` for the new one.

I hope that helps!

**Comment by 11Kilobytes** [comment]
K. Feel free to close this issue @avigad, and thanks for helping me (even if this wasn't quite the venue).

**Comment by avigad** [comment]
My pleasure! The venue is perfectly reasonable. Could you close the issue? Leo and Soonho manage the repository, so otherwise they will have to do it.

**Comment by leodemoura** [comment]
Some additional information.
Lean uses constraint solving for disambiguating the user input.
The example `definition idn ...` works because Lean treats it as a "single" elaboration problem.
On the other hand, the `variables ...` command creates independent problems. It is really "syntax sugar" for:

``` lean
variable {A : Type} 
variable {B : Type} 
variable {C : A + B → Type} 
variable (f : Π (a : A), C (sum.inl (sum.inl a)))
```

So, `C : A + B → Type` is fully elaborated before Lean even starts processing `f`.
`+` is overloaded in your example, and both interpretations are acceptable before we process `f`.

Jeremy suggested several workarounds, here is another one.
Where it is necessary to disambiguate, Lean allows us to precede an expression with the notation `#<namespace>` to specify the namespace in which notation is to be interpreted.
So, you can also write:

``` lean
namespace test
  definition union (A : Type) (B : Type) := A + B + B
  notation A `+` B := union A B

   variables {A : Type} {B : Type} {C : #test A + B → Type} (f : Π (a : A), C (sum.inl (sum.inl a)))
   check C
end test
```
