### ISSUE TITLE
Extending a namespace after opening it

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#963]
Is it intended behaviour that this fails and I have to open eq again after extending it? Or is it just more convenient to have it that way because lean makes the changes to the available definitions based on the line where I put the `open` command?

``` lean
open eq

namespace eq

  definition def1 : Type₀ := bool

end eq

check def1
```

**Comment by dselsam** [comment]
The `open` command does a one-time iteration over all the declarations in the environment. When it finds a declaration whose name begins with the prefix in question (i.e. `eq.` in your example), it adds an alias to the environment so that the declaration can be referenced without using the prefix. Note that the fact that `eq` is "open" is not stored anywhere. When you add a new declaration to the environment later on with the prefix `eq.`, Lean does not do anything special with it.

**Comment by javra** [comment]
Thanks for the explanations, I didn't expect it to be so... lexical.
