### ISSUE TITLE
identical expressions: one typechecks, another doesn't

### ISSUE THREAD

**Issue by zraffer** [leanprover/lean3#997]
Currently the file at https://github.com/groupoid/exe/blob/07f60df9401d5c34813e515e876a178e9dac45a4/prelude/lean/Adjunction.lean
emits a type error when the spuriously errorneous expression is placed in `definition` clause

```
Adjunction.lean:88:13: error: type mismatch at application
  eq_and_hom C (Adj.counit adj/$$/f)
term
  Adj.counit adj/$$/f
has type
  Mor.SquareProp C ((L⊗R)$$/f) (𝟙$$/f) (Adj.counit adj/$$(L$$X)) (Adj.counit adj/$$Y)
but is expected to have type
  CatType.Mul C$(Adj.counit adj/$$Y)$(L$$/(R$$/f)) ≡ ((L⊗R)$$(L$$X)⇒C⇒Y)≡CatType.Mul C$f$(Adj.counit
     adj/$$(L$$X))
```

however, the identical expression (at the commented block above in the same file) typechecks well in a `check` clause. I consider the type inferred by `check` as correct.

Am I missing something?

**Comment by fpvandoorn** [comment]
This error message means the elaborator is unable to find all implicit arguments in your expression and you have to help it a bit to find the right solution.

The difference between the definition and the `check` command in your file is that for `check` command it has already elaborated the types of all variables and abbreviations, before it has to elaborate the term inside the `check` command. The following `check` is more similar to the definition you're giving, and that also fails:

``` lean
    check λ(C D : CatType) (L : D⟶C) (R : C⟶D)
           (adj : Adj L R) (X : D) (Y : C) (f : L X ⇒C⇒ Y), 
          let ε := Adj.counit adj in let η := Adj.unit adj in 
            (hom_and_eq C (ε /$$ Y) (FunctorType.onMul L (R $$/ f) (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            (CatType.AssocInv C (ε /$$ Y) (L $$/ (R $$/ f)) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            (eq_and_hom C (ε /$$/ f) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            (CatType.Assoc C f (ε /$$ (L $$ X)) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            (hom_and_eq C f (Adj.triangleL adj X)) ⊡(L X ⇒C⇒ Y)⊡
            (CatType.UnitR C f)
```

It's hard to investigate why the elaborator exactly fails in this case, but there are ways to give the elaborator a bit more information, so that it accepts your term:
- You can put the whole definition inside a `proof ... qed` block. This has as result that the elaborator will first elaborate everything outside the `proof ... qed` block (i.e. the arguments of your definition) and after that elaborates everything inside it. This does require you to give the type of your definition explicitly. Example:

``` lean
    definition LeqL
        (C D : CatType) (L : D⟶C) (R : C⟶D)
        (adj : Adj L R) (X : D) (Y : C) (f : L X ⇒C⇒ Y) 
       : CatType.Mul C$(Adj.counit adj/$$Y)$(FunctorType.onHom L$(CatType.Mul D$(R$$/f)$(Adj.unit
       adj/$$X))) ≡ (L$$X⇒C⇒Y)≡f
    := 
      proof 
        let ε := Adj.counit adj, η := Adj.unit adj in 
            (hom_and_eq C (ε /$$ Y) (FunctorType.onMul L (R $$/ f) (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            (CatType.AssocInv C (ε /$$ Y) (L $$/ (R $$/ f)) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            (eq_and_hom C (ε /$$/ f) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            (CatType.Assoc C f (ε /$$ (L $$ X)) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            (hom_and_eq C f (Adj.triangleL adj X)) ⊡(L X ⇒C⇒ Y)⊡
            (CatType.UnitR C f) 
      qed
```

(note: this type is the output of the pretty printer: there is probably a nicer way to write it).
- Another solution is to just put the problematic part of the term inside `proof ... qed`, that sometimes helps:

``` lean
    definition LeqL
        (C D : CatType) (L : D⟶C) (R : C⟶D)
        (adj : Adj L R) (X : D) (Y : C) (f : L X ⇒C⇒ Y)
    := let ε := Adj.counit adj, η := Adj.unit adj in
            (hom_and_eq C (ε /$$ Y) (FunctorType.onMul L (R $$/ f) (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            (CatType.AssocInv C (ε /$$ Y) (L $$/ (R $$/ f)) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            proof (eq_and_hom C (ε /$$/ f) (L $$/ (η /$$ X))) qed ⊡(L X ⇒C⇒ Y)⊡
            (CatType.Assoc C f (ε /$$ (L $$ X)) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡
            (hom_and_eq C f (Adj.triangleL adj X)) ⊡(L X ⇒C⇒ Y)⊡
            (CatType.UnitR C f)
```
- In general, it's good to write proof terms with a bit more explicit information to help the elaborator, or break up the problem into smaller pieces. For example, in the following way we split up the elaboration problem line by line:

``` lean
    definition LeqL
        (C D : CatType) (L : D⟶C) (R : C⟶D)
        (adj : Adj L R) (X : D) (Y : C) (f : L X ⇒C⇒ Y) : 
        CatType.Mul C$(Adj.counit adj/$$Y)$(FunctorType.onHom L$(CatType.Mul D$(R$$/f)$(Adj.unit
       adj/$$X))) ≡ (L$$X⇒C⇒Y)≡f
    := let ε := Adj.counit adj, η := Adj.unit adj in
      begin
        refine (hom_and_eq C (ε /$$ Y) (FunctorType.onMul L (R $$/ f) (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡ _,
        refine (CatType.AssocInv C (ε /$$ Y) (L $$/ (R $$/ f)) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡ _,
        refine (eq_and_hom C (ε /$$/ f) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡ _,
        refine (CatType.Assoc C f (ε /$$ (L $$ X)) (L $$/ (η /$$ X))) ⊡(L X ⇒C⇒ Y)⊡ _,
        refine (hom_and_eq C f (Adj.triangleL adj X)) ⊡(L X ⇒C⇒ Y)⊡ _,
        exact  (CatType.UnitR C f)
      end
```

**Comment by zraffer** [comment]
All solutions work! Thank you.

**Comment by fpvandoorn** [comment]
You're welcome

An unrelated comment about the pretty printer: in `notation` commands you can use spaces to help the pretty printer print things nicer (with spaces). For example if you write

```
notation ab ` ⊡` S `⊡ ` bc := SetoidType.Trans S ab bc
```

it will put a space before the first `⊡` and after the second `⊡`, which might make the output easier to read.
